export interface BldLetterPair {
  id: string
  piece: string
  name: string
  edgesAlgorithm: string
  cornersAlgorithm: string
  learned: boolean
}

export interface BldFlipCase {
  id: string
  piece: string
  name: string
  algorithm: string
  learned: boolean
}

export interface BldTwistCase {
  id: string
  piece: string
  name: string
  algorithm1: string
  algorithm2: string
  learned: boolean
}

const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

export const defaultBldLetterPairs: BldLetterPair[] = [
  { id: "pair-AA", piece: "AA", name: "AA", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-AB", piece: "AB", name: "AB", edgesAlgorithm: "(R2 U' : (S , R2'))", cornersAlgorithm: "(Lw': (U, R' D2 R))", learned: false },
  { id: "pair-AC", piece: "AC", name: "AC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-AD", piece: "AD", name: "AD", edgesAlgorithm: "(L2' U : (S' , L2))", cornersAlgorithm: "(R' D R U2 : (R' D' R , U))", learned: false },
  { id: "pair-AE", piece: "AE", name: "AE", edgesAlgorithm: "(U' M U' : (M' , U2))", cornersAlgorithm: "", learned: false },
  { id: "pair-AF", piece: "AF", name: "AF", edgesAlgorithm: "(U' : (R' E R , U2))", cornersAlgorithm: "(F: (U2, R' D' R))", learned: false },
  { id: "pair-AG", piece: "AG", name: "AG", edgesAlgorithm: "(U : (L' E' L , U2'))", cornersAlgorithm: "(R' D R , U2)", learned: false },
  { id: "pair-AH", piece: "AH", name: "AH", edgesAlgorithm: "(U' : (R E' R' , U2))", cornersAlgorithm: "(U' : (R D' R' , U2))", learned: false },
  { id: "pair-AI", piece: "AI", name: "AI", edgesAlgorithm: "", cornersAlgorithm: "(Lw' D' U : (R D R' , U2))", learned: false },
  { id: "pair-AJ", piece: "AJ", name: "AJ", edgesAlgorithm: "(R' U' : (S , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-AK", piece: "AK", name: "AK", edgesAlgorithm: "(R' F' : (R U R' , E))", cornersAlgorithm: "(D U' : (R D R' , U2))", learned: false },
  { id: "pair-AL", piece: "AL", name: "AL", edgesAlgorithm: "(L U : (S' , L2'))", cornersAlgorithm: "(D : (R' D' R , U2))", learned: false },
  { id: "pair-AM", piece: "AM", name: "AM", edgesAlgorithm: "(U M U : (M' , U2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-AN", piece: "AN", name: "AN", edgesAlgorithm: "(U : (L' E L , U2'))", cornersAlgorithm: "(R' U D R2 : (U' , R' D' R))", learned: false },
  { id: "pair-AO", piece: "AO", name: "AO", edgesAlgorithm: "(U' : (R E R' , U2))", cornersAlgorithm: "(U' : (R D R' , U2))", learned: false },
  { id: "pair-AP", piece: "AP", name: "AP", edgesAlgorithm: "(U : (L E' L' , U2'))", cornersAlgorithm: "(R' D' R , U2)", learned: false },
  { id: "pair-AQ", piece: "AQ", name: "AQ", edgesAlgorithm: "", cornersAlgorithm: "(R' U D : (R D R' , U2))", learned: false },
  { id: "pair-AR", piece: "AR", name: "AR", edgesAlgorithm: "(L' U' : (L2 , S'))", cornersAlgorithm: "", learned: false },
  { id: "pair-AS", piece: "AS", name: "AS", edgesAlgorithm: "(U' R' B R : (S , R2'))", cornersAlgorithm: "(D' U' : (R D R' , U2))", learned: false },
  { id: "pair-AT", piece: "AT", name: "AT", edgesAlgorithm: "(R U : (R2' , S))", cornersAlgorithm: "(D U' : (R D' R' , U2))", learned: false },
  { id: "pair-AU", piece: "AU", name: "AU", edgesAlgorithm: "(U2 , M')", cornersAlgorithm: "(R F' R' U' : (R D R' , U2))", learned: false },
  { id: "pair-AV", piece: "AV", name: "AV", edgesAlgorithm: "(U' : (S , R2'))", cornersAlgorithm: "(R' D R U' R D' R' , U2)", learned: false },
  { id: "pair-AW", piece: "AW", name: "AW", edgesAlgorithm: "(M , U2)", cornersAlgorithm: "(R D' R' : (R' D R , U2))", learned: false },
  { id: "pair-AX", piece: "AX", name: "AX", edgesAlgorithm: "(U : (S' , L2'))", cornersAlgorithm: "(R' D' R : (R U' R' , D))", learned: false },
  { id: "pair-AY", piece: "AY", name: "AY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-AZ", piece: "AZ", name: "AZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-BA", piece: "BA", name: "BA", edgesAlgorithm: "(R2 U' : (R2' , S))", cornersAlgorithm: "(R' B' R : (U' , R D R'))", learned: false },
  { id: "pair-BB", piece: "BB", name: "BB", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-BC", piece: "BC", name: "BC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-BD", piece: "BD", name: "BD", edgesAlgorithm: "(M2' U : (M , U2'))", cornersAlgorithm: "(R F' R' : (R' D R , U))", learned: false },
  { id: "pair-BE", piece: "BE", name: "BE", edgesAlgorithm: "(S' , L F' L')", cornersAlgorithm: "(R : (U , R D R'))", learned: false },
  { id: "pair-BF", piece: "BF", name: "BF", edgesAlgorithm: "(U' , R' E R)", cornersAlgorithm: "(R' : (R' D' R , U'))", learned: false },
  { id: "pair-BG", piece: "BG", name: "BG", edgesAlgorithm: "(U : (L' E' L , U))", cornersAlgorithm: "(R' D R , U)", learned: false },
  { id: "pair-BH", piece: "BH", name: "BH", edgesAlgorithm: "(U' , R E' R')", cornersAlgorithm: "(U' , R D' R')", learned: false },
  { id: "pair-BI", piece: "BI", name: "BI", edgesAlgorithm: "", cornersAlgorithm: "(R2' U' : (D' , R U R'))", learned: false },
  { id: "pair-BJ", piece: "BJ", name: "BJ", edgesAlgorithm: "(E' : (U' , R' E R))", cornersAlgorithm: "", learned: false },
  { id: "pair-BK", piece: "BK", name: "BK", edgesAlgorithm: "(r : (U' R' U , M))", cornersAlgorithm: "(D' : (R' D R , U))", learned: false },
  { id: "pair-BL", piece: "BL", name: "BL", edgesAlgorithm: "(U' , R E2 R')", cornersAlgorithm: "(D : (R' D' R , U))", learned: false },
  { id: "pair-BM", piece: "BM", name: "BM", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-BN", piece: "BN", name: "BN", edgesAlgorithm: "(U : (L' E L , U)", cornersAlgorithm: "", learned: false },
  { id: "pair-BO", piece: "BO", name: "BO", edgesAlgorithm: "(U' , R E R')", cornersAlgorithm: "(U' , R D R')", learned: false },
  { id: "pair-BP", piece: "BP", name: "BP", edgesAlgorithm: "(U : (L E' L' , U)", cornersAlgorithm: "(R' D' R , U)", learned: false },
  { id: "pair-BQ", piece: "BQ", name: "BQ", edgesAlgorithm: "(r' : (U' R U , M'))", cornersAlgorithm: "", learned: false },
  { id: "pair-BR", piece: "BR", name: "BR", edgesAlgorithm: "(U' , R' E2 R)", cornersAlgorithm: "(R2 U : (R' U' R , D))", learned: false },
  { id: "pair-BS", piece: "BS", name: "BS", edgesAlgorithm: "(U M U M')2", cornersAlgorithm: "(D' : (U' , R D R'))", learned: false },
  { id: "pair-BT", piece: "BT", name: "BT", edgesAlgorithm: "(u' : (R E' R' , U))", cornersAlgorithm: "(D : (U' , R D' R'))", learned: false },
  { id: "pair-BU", piece: "BU", name: "BU", edgesAlgorithm: "(L F : (L' S' L , F2'))", cornersAlgorithm: "(R F' : (R' U' R , D))", learned: false },
  { id: "pair-BV", piece: "BV", name: "BV", edgesAlgorithm: "(R' U R' : (S , R2))", cornersAlgorithm: "(R' D R U' R D' R' , U)", learned: false },
  { id: "pair-BW", piece: "BW", name: "BW", edgesAlgorithm: "(r M' : (U' R' U , M2'))", cornersAlgorithm: "(U' , R D' R' U R' D R)", learned: false },
  { id: "pair-BX", piece: "BX", name: "BX", edgesAlgorithm: "U' L' U' L U L U L U' L'", cornersAlgorithm: "(R' B : (D' , R U R'))", learned: false },
  { id: "pair-BY", piece: "BY", name: "BY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-BZ", piece: "BZ", name: "BZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CA", piece: "CA", name: "CA", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CB", piece: "CB", name: "CB", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CC", piece: "CC", name: "CC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CD", piece: "CD", name: "CD", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CE", piece: "CE", name: "CE", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CF", piece: "CF", name: "CF", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CG", piece: "CG", name: "CG", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CH", piece: "CH", name: "CH", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CI", piece: "CI", name: "CI", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CJ", piece: "CJ", name: "CJ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CK", piece: "CK", name: "CK", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CL", piece: "CL", name: "CL", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CM", piece: "CM", name: "CM", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CN", piece: "CN", name: "CN", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CO", piece: "CO", name: "CO", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CP", piece: "CP", name: "CP", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CQ", piece: "CQ", name: "CQ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CR", piece: "CR", name: "CR", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CS", piece: "CS", name: "CS", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CT", piece: "CT", name: "CT", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CU", piece: "CU", name: "CU", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CV", piece: "CV", name: "CV", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CW", piece: "CW", name: "CW", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CX", piece: "CX", name: "CX", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CY", piece: "CY", name: "CY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-CZ", piece: "CZ", name: "CZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-DA", piece: "DA", name: "DA", edgesAlgorithm: "(L2' U : (L2 , S'))", cornersAlgorithm: "(R' D R U' : (R' D' R , U'))", learned: false },
  { id: "pair-DB", piece: "DB", name: "DB", edgesAlgorithm: "(M2' U' : (M , U2))", cornersAlgorithm: "(R F' R' : (U , R' D R))", learned: false },
  { id: "pair-DC", piece: "DC", name: "DC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-DD", piece: "DD", name: "DD", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-DE", piece: "DE", name: "DE", edgesAlgorithm: "", cornersAlgorithm: "(U' R2 : [D , R' U2 R))", learned: false },
  { id: "pair-DF", piece: "DF", name: "DF", edgesAlgorithm: "(U' : (R' E R , U'))", cornersAlgorithm: "(R' D R , U')", learned: false },
  { id: "pair-DG", piece: "DG", name: "DG", edgesAlgorithm: "(U , L' E' L)", cornersAlgorithm: "(U' : (R D' R' , U'))", learned: false },
  { id: "pair-DH", piece: "DH", name: "DH", edgesAlgorithm: "(U' : (R E' R' , U'))", cornersAlgorithm: "(D' : (R' D R , U'))", learned: false },
  { id: "pair-DI", piece: "DI", name: "DI", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-DJ", piece: "DJ", name: "DJ", edgesAlgorithm: "(U , L' E2' L)", cornersAlgorithm: "", learned: false },
  { id: "pair-DK", piece: "DK", name: "DK", edgesAlgorithm: "(l' : (U L U' , M))", cornersAlgorithm: "(D : [R' D' R , U'))", learned: false },
  { id: "pair-DL", piece: "DL", name: "DL", edgesAlgorithm: "(U' : (R E2 R' , U')", cornersAlgorithm: "(U' R' : (U2 , R' D' R))", learned: false },
  { id: "pair-DM", piece: "DM", name: "DM", edgesAlgorithm: "(S , R' F R)", cornersAlgorithm: "", learned: false },
  { id: "pair-DN", piece: "DN", name: "DN", edgesAlgorithm: "(U , L' E L)", cornersAlgorithm: "(U' : (R D R' , U'))", learned: false },
  { id: "pair-DO", piece: "DO", name: "DO", edgesAlgorithm: "(U' : (R E R' , U'))", cornersAlgorithm: "(R' D' R , U')", learned: false },
  { id: "pair-DP", piece: "DP", name: "DP", edgesAlgorithm: "(U , L E' L')", cornersAlgorithm: "(R' D' : (U' , R' D R))", learned: false },
  { id: "pair-DQ", piece: "DQ", name: "DQ", edgesAlgorithm: "(L : (M , U L' U'))", cornersAlgorithm: "(U' R' : (U' , R' D' R))", learned: false },
  { id: "pair-DR", piece: "DR", name: "DR", edgesAlgorithm: "(U' : (R E2 R' , U')", cornersAlgorithm: "(D : (R' D R , U'))", learned: false },
  { id: "pair-DS", piece: "DS", name: "DS", edgesAlgorithm: "(U' M U' M')2", cornersAlgorithm: "(D' : (R' D' R , U'))", learned: false },
  { id: "pair-DT", piece: "DT", name: "DT", edgesAlgorithm: "(U , L E2' L')", cornersAlgorithm: "(x' U' : (R U R', D2))", learned: false },
  { id: "pair-DU", piece: "DU", name: "DU", edgesAlgorithm: "(R' F' : (R S R' , F2))", cornersAlgorithm: "(R' D R U' R D' R' , U')", learned: false },
  { id: "pair-DV", piece: "DV", name: "DV", edgesAlgorithm: "U R U R' U' R' U' R' U R", cornersAlgorithm: "(R D' R' : (R' D R , U'))", learned: false },
  { id: "pair-DW", piece: "DW", name: "DW", edgesAlgorithm: "(l' M' : (U L U' , M2'))", cornersAlgorithm: "(R' D' R : (R U' R' , D))", learned: false },
  { id: "pair-DX", piece: "DX", name: "DX", edgesAlgorithm: "(L U' L : (S' , L2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-DY", piece: "DY", name: "DY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-DZ", piece: "DZ", name: "DZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-EA", piece: "EA", name: "EA", edgesAlgorithm: "(U' M U : (M' , U2))", cornersAlgorithm: "", learned: false },
  { id: "pair-EB", piece: "EB", name: "EB", edgesAlgorithm: "(L F' L' , S')", cornersAlgorithm: "(R2 : (D , R' U R))", learned: false },
  { id: "pair-EC", piece: "EC", name: "EC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ED", piece: "ED", name: "ED", edgesAlgorithm: "", cornersAlgorithm: "(U' R : (U2 , R D R'))", learned: false },
  { id: "pair-EE", piece: "EE", name: "EE", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-EF", piece: "EF", name: "EF", edgesAlgorithm: "(S : (U' , R' E R))", cornersAlgorithm: "(U' R' F : (D , R U R'))", learned: false },
  { id: "pair-EG", piece: "EG", name: "EG", edgesAlgorithm: "(l' U L' : (S' , L2))", cornersAlgorithm: "(U R' : (U' , R' D R))", learned: false },
  { id: "pair-EH", piece: "EH", name: "EH", edgesAlgorithm: "(S : (U' , R E' R'))", cornersAlgorithm: "(R D' : (R D R' , U))", learned: false },
  { id: "pair-EI", piece: "EI", name: "EI", edgesAlgorithm: "", cornersAlgorithm: "(l' U : (R D' R' , U2))", learned: false },
  { id: "pair-EJ", piece: "EJ", name: "EJ", edgesAlgorithm: "(M' : (U' , R S' R'))", cornersAlgorithm: "", learned: false },
  { id: "pair-EK", piece: "EK", name: "EK", edgesAlgorithm: "(l' : (M' , U' L U))", cornersAlgorithm: "(U D' R' : (U' , R' D R))", learned: false },
  { id: "pair-EL", piece: "EL", name: "EL", edgesAlgorithm: "(L' U2 : (L S L' , U))", cornersAlgorithm: "(R U : (R' D R , U))", learned: false },
  { id: "pair-EM", piece: "EM", name: "EM", edgesAlgorithm: "(M U : (M' , U2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-EN", piece: "EN", name: "EN", edgesAlgorithm: "(L' F' : (E , L2))", cornersAlgorithm: "(R' D R2 D' R2' : (U , R2 D R2' D' R2))", learned: false },
  { id: "pair-EO", piece: "EO", name: "EO", edgesAlgorithm: "(R' F R : (S , R2'))", cornersAlgorithm: "(U' R : (R U' R' , D'))", learned: false },
  { id: "pair-EP", piece: "EP", name: "EP", edgesAlgorithm: "(R M U : (M' , U2))", cornersAlgorithm: "(U R' U2 : (R D R' , U))", learned: false },
  { id: "pair-EQ", piece: "EQ", name: "EQ", edgesAlgorithm: "(L' : (U' L U , M'))", cornersAlgorithm: "(R' , F' L F))", learned: false },
  { id: "pair-ER", piece: "ER", name: "ER", edgesAlgorithm: "(U' R F : (R2' , E'))", cornersAlgorithm: "", learned: false },
  { id: "pair-ES", piece: "ES", name: "ES", edgesAlgorithm: "M' : (U M' U M)2", cornersAlgorithm: "(U D R' : (U' , R' D R))", learned: false },
  { id: "pair-ET", piece: "ET", name: "ET", edgesAlgorithm: "(M' : (U' , L' E L))", cornersAlgorithm: "(R U : (R' D' R , U))", learned: false },
  { id: "pair-EU", piece: "EU", name: "EU", edgesAlgorithm: "(L' F' : (L2 , E'))", cornersAlgorithm: "(D' R : (R D' R' , U))", learned: false },
  { id: "pair-EV", piece: "EV", name: "EV", edgesAlgorithm: "(L2 : (L' F' L , S))", cornersAlgorithm: "(U R' D' : (U' , R' D' R))", learned: false },
  { id: "pair-EW", piece: "EW", name: "EW", edgesAlgorithm: "(L' M : (U' L U , M2'))", cornersAlgorithm: "(D R : [R D' R', U))", learned: false },
  { id: "pair-EX", piece: "EX", name: "EX", edgesAlgorithm: "(L F' L' , S))", cornersAlgorithm: "(R : (R D' R' , U))", learned: false },
  { id: "pair-EY", piece: "EY", name: "EY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-EZ", piece: "EZ", name: "EZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-FA", piece: "FA", name: "FA", edgesAlgorithm: "(U : (R' E R , U2))", cornersAlgorithm: "(U2 , R' D R)", learned: false },
  { id: "pair-FB", piece: "FB", name: "FB", edgesAlgorithm: "(R' E R , U')", cornersAlgorithm: "(U , R' D R)", learned: false },
  { id: "pair-FC", piece: "FC", name: "FC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-FD", piece: "FD", name: "FD", edgesAlgorithm: "(U2 : (R' E R , U))", cornersAlgorithm: "", learned: false },
  { id: "pair-FE", piece: "FE", name: "FE", edgesAlgorithm: "(S : (R' E R , U'))", cornersAlgorithm: "(U' , R' D R)", learned: false },
  { id: "pair-FF", piece: "FF", name: "FF", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-FG", piece: "FG", name: "FG", edgesAlgorithm: "(L , U S' U')", cornersAlgorithm: "(U R' : (R' D R , U'))", learned: false },
  { id: "pair-FH", piece: "FH", name: "FH", edgesAlgorithm: "(M' U L : (S' , L2'))", cornersAlgorithm: "(R' U' : (R U R' , D))", learned: false },
  { id: "pair-FI", piece: "FI", name: "FI", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-FJ", piece: "FJ", name: "FJ", edgesAlgorithm: "(E , R U' R')", cornersAlgorithm: "", learned: false },
  { id: "pair-FK", piece: "FK", name: "FK", edgesAlgorithm: "(M2' : (U' L' U , M))", cornersAlgorithm: "(D R' : (F' , R D' R'))", learned: false },
  { id: "pair-FL", piece: "FL", name: "FL", edgesAlgorithm: "", cornersAlgorithm: "(D R' : (F2 , R D' R' D))", learned: false },
  { id: "pair-FM", piece: "FM", name: "FM", edgesAlgorithm: "(M L' U : (M' , U2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-FN", piece: "FN", name: "FN", edgesAlgorithm: "(r U R' : (E , R2))", cornersAlgorithm: "(U : (D , R U' R'))", learned: false },
  { id: "pair-FO", piece: "FO", name: "FO", edgesAlgorithm: "(M' U R' : (E , R2))", cornersAlgorithm: "(U R U : (R' D R , U2))", learned: false },
  { id: "pair-FP", piece: "FP", name: "FP", edgesAlgorithm: "(U E R' : (S , R2))", cornersAlgorithm: "(U D : (R U' R' , D2))", learned: false },
  { id: "pair-FQ", piece: "FQ", name: "FQ", edgesAlgorithm: "(U' L' U , M')", cornersAlgorithm: "(U R' D : (R U' R' , D2))", learned: false },
  { id: "pair-FR", piece: "FR", name: "FR", edgesAlgorithm: "(E' , L U L')", cornersAlgorithm: "(R' U : (R U' R' , D))", learned: false },
  { id: "pair-FS", piece: "FS", name: "FS", edgesAlgorithm: "(U' r' : (R U R' , E))", cornersAlgorithm: "(R B' R' : (R' D R , U))", learned: false },
  { id: "pair-FT", piece: "FT", name: "FT", edgesAlgorithm: "(R2' : (E , R U' R'))", cornersAlgorithm: "(U D : (R U' R' , D))", learned: false },
  { id: "pair-FU", piece: "FU", name: "FU", edgesAlgorithm: "(U R' F2 : (R S R' , F))", cornersAlgorithm: "(R' D R : (D' , R U R'))", learned: false },
  { id: "pair-FV", piece: "FV", name: "FV", edgesAlgorithm: "(U' E' R : (E' , R2'))", cornersAlgorithm: "(U D R D' : (U' , R' D R))", learned: false },
  { id: "pair-FW", piece: "FW", name: "FW", edgesAlgorithm: "(M : (U' L' U , M2'))", cornersAlgorithm: "(U R : (D , R U' R'))", learned: false },
  { id: "pair-FX", piece: "FX", name: "FX", edgesAlgorithm: "(U E L : (E' , L2'))", cornersAlgorithm: "(D U R U' : (F2' , U R' U' R))", learned: false },
  { id: "pair-FY", piece: "FY", name: "FY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-FZ", piece: "FZ", name: "FZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-GA", piece: "GA", name: "GA", edgesAlgorithm: "(U' : (L' E' L , U2'))", cornersAlgorithm: "(U : (R D' R' , U2))", learned: false },
  { id: "pair-GB", piece: "GB", name: "GB", edgesAlgorithm: "(U2' : (L' E' L , U'))", cornersAlgorithm: "(R D' R' , U')", learned: false },
  { id: "pair-GC", piece: "GC", name: "GC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-GD", piece: "GD", name: "GD", edgesAlgorithm: "(L' E' L , U)", cornersAlgorithm: "(U2 : (R D' R' , U))", learned: false },
  { id: "pair-GE", piece: "GE", name: "GE", edgesAlgorithm: "(l' U L : (S' , L2'))", cornersAlgorithm: "(R D' : (U , R D R'))", learned: false },
  { id: "pair-GF", piece: "GF", name: "GF", edgesAlgorithm: "(U S' U' , L)", cornersAlgorithm: "(U' R U' : (R' U R , D'))", learned: false },
  { id: "pair-GG", piece: "GG", name: "GG", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-GH", piece: "GH", name: "GH", edgesAlgorithm: "(U S U' , L')", cornersAlgorithm: "(R' D : (F' , D' R D R'))", learned: false },
  { id: "pair-GI", piece: "GI", name: "GI", edgesAlgorithm: "", cornersAlgorithm: "(R U' D : (R' D R , U2))", learned: false },
  { id: "pair-GJ", piece: "GJ", name: "GJ", edgesAlgorithm: "(L' E' : (L U L' , E'))", cornersAlgorithm: "", learned: false },
  { id: "pair-GK", piece: "GK", name: "GK", edgesAlgorithm: "(U : (L F L' , S))", cornersAlgorithm: "(l' U : (D , R U' R'))", learned: false },
  { id: "pair-GL", piece: "GL", name: "GL", edgesAlgorithm: "(L f' L' : (S , L2))", cornersAlgorithm: "", learned: false },
  { id: "pair-GM", piece: "GM", name: "GM", edgesAlgorithm: "(L F' L : (S' , L2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-GN", piece: "GN", name: "GN", edgesAlgorithm: "(L F' : (E , L2'))", cornersAlgorithm: "(D2 : (R U R' , D'))", learned: false },
  { id: "pair-GO", piece: "GO", name: "GO", edgesAlgorithm: "(R' F R' : (S' , R2))", cornersAlgorithm: "(U R : (R D' R' , U2))", learned: false },
  { id: "pair-GP", piece: "GP", name: "GP", edgesAlgorithm: "(M' U' L' : (E' , L2))", cornersAlgorithm: "(R D' : (R' U' R , D2))", learned: false },
  { id: "pair-GQ", piece: "GQ", name: "GQ", edgesAlgorithm: "(L' : (U' L' U , M'))", cornersAlgorithm: "(D2 , R U R')", learned: false },
  { id: "pair-GR", piece: "GR", name: "GR", edgesAlgorithm: "(S' U' R' : (E' , R2))", cornersAlgorithm: "(U' L U , R)", learned: false },
  { id: "pair-GS", piece: "GS", name: "GS", edgesAlgorithm: "(U l : (L' U' L , E))", cornersAlgorithm: "(U D R' F' : (D , R U' R'))", learned: false },
  { id: "pair-GT", piece: "GT", name: "GT", edgesAlgorithm: "(L E : (L' U L , E))", cornersAlgorithm: "(D2 : (R U R' , D))", learned: false },
  { id: "pair-GU", piece: "GU", name: "GU", edgesAlgorithm: "(L F' : (L2' , E'))", cornersAlgorithm: "", learned: false },
  { id: "pair-GV", piece: "GV", name: "GV", edgesAlgorithm: "(L' F' L , S)", cornersAlgorithm: "(D R U' R' : (R' D R , U2))", learned: false },
  { id: "pair-GW", piece: "GW", name: "GW", edgesAlgorithm: "(U : (S' , L B' L'))", cornersAlgorithm: "(R U' D R' : (R' D R , U2))", learned: false },
  { id: "pair-GX", piece: "GX", name: "GX", edgesAlgorithm: "", cornersAlgorithm: "(R D' R' : (R' D R , U))", learned: false },
  { id: "pair-GY", piece: "GY", name: "GY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-GZ", piece: "GZ", name: "GZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-HA", piece: "HA", name: "HA", edgesAlgorithm: "(U : (R E' R' , U2))", cornersAlgorithm: "R' D R U' R : (F , R' U R U')", learned: false },
  { id: "pair-HB", piece: "HB", name: "HB", edgesAlgorithm: "(R E' R' , U')", cornersAlgorithm: "(R2 U' : (R U R' , D'))", learned: false },
  { id: "pair-HC", piece: "HC", name: "HC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-HD", piece: "HD", name: "HD", edgesAlgorithm: "(U2 : (R E' R' , U))", cornersAlgorithm: "(l' U' : (R D' R' , U2))", learned: false },
  { id: "pair-HE", piece: "HE", name: "HE", edgesAlgorithm: "(S : (R E' R' , U'))", cornersAlgorithm: "(R' D : (F2 , D' R D R'))", learned: false },
  { id: "pair-HF", piece: "HF", name: "HF", edgesAlgorithm: "(M' U L' : (S' , L2'))", cornersAlgorithm: "(R U D : (R' D R , U2))", learned: false },
  { id: "pair-HG", piece: "HG", name: "HG", edgesAlgorithm: "(L' , U S' U')", cornersAlgorithm: "(D' R' D : (F2 , D' R D R'))", learned: false },
  { id: "pair-HH", piece: "HH", name: "HH", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-HI", piece: "HI", name: "HI", edgesAlgorithm: "", cornersAlgorithm: "(R U : (R' D R , U2))", learned: false },
  { id: "pair-HJ", piece: "HJ", name: "HJ", edgesAlgorithm: "(R2 : (E' , R' U' R))", cornersAlgorithm: "", learned: false },
  { id: "pair-HK", piece: "HK", name: "HK", edgesAlgorithm: "(M' : (M' , U' L U))", cornersAlgorithm: "(R' F' R D U : (U2 , R' D' R)", learned: false },
  { id: "pair-HL", piece: "HL", name: "HL", edgesAlgorithm: "(E , L' U L)", cornersAlgorithm: "(R D' U : (R' D R , U2))", learned: false },
  { id: "pair-HM", piece: "HM", name: "HM", edgesAlgorithm: "(R F : (R2' , E'))", cornersAlgorithm: "", learned: false },
  { id: "pair-HN", piece: "HN", name: "HN", edgesAlgorithm: "(u' L : (S' , L2'))", cornersAlgorithm: "(D R U : (R' D' R , U2))", learned: false },
  { id: "pair-HO", piece: "HO", name: "HO", edgesAlgorithm: "(R' F : (R2 , E'))", cornersAlgorithm: "(R U D' : (R' D' R , U2))", learned: false },
  { id: "pair-HP", piece: "HP", name: "HP", edgesAlgorithm: "(l' U' L' : (E' , L2))", cornersAlgorithm: "(R U R' U D : (R D R' , U2))", learned: false },
  { id: "pair-HQ", piece: "HQ", name: "HQ", edgesAlgorithm: "(U' L U , M')", cornersAlgorithm: "(D R' D : (F2 , D' R D R'))", learned: false },
  { id: "pair-HR", piece: "HR", name: "HR", edgesAlgorithm: "", cornersAlgorithm: "(R U : (R' D' R , U2))", learned: false },
  { id: "pair-HS", piece: "HS", name: "HS", edgesAlgorithm: "(U' M : (U , L S L'))", cornersAlgorithm: "", learned: false },
  { id: "pair-HT", piece: "HT", name: "HT", edgesAlgorithm: "(E' , R' U' R)", cornersAlgorithm: "(D' R : (R D' R' , U2))", learned: false },
  { id: "pair-HU", piece: "HU", name: "HU", edgesAlgorithm: "(l' U : (S' , L2))", cornersAlgorithm: "(R U' R' D' : (R' D R , U2))", learned: false },
  { id: "pair-HV", piece: "HV", name: "HV", edgesAlgorithm: "(u' R' : (E , R2))", cornersAlgorithm: "(D R : (R D' R' , U2))", learned: false },
  { id: "pair-HW", piece: "HW", name: "HW", edgesAlgorithm: "(M : (U' L U , M2'))", cornersAlgorithm: "(R : (R D' R' , U2))", learned: false },
  { id: "pair-HX", piece: "HX", name: "HX", edgesAlgorithm: "(u L' : (E , L2))", cornersAlgorithm: "", learned: false },
  { id: "pair-HY", piece: "HY", name: "HY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-HZ", piece: "HZ", name: "HZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-IA", piece: "IA", name: "IA", edgesAlgorithm: "", cornersAlgorithm: "R' D R U' R : (F , R' U R U')", learned: false },
  { id: "pair-IB", piece: "IB", name: "IB", edgesAlgorithm: "", cornersAlgorithm: "(R2 U' : (R U R' , D'))", learned: false },
  { id: "pair-IC", piece: "IC", name: "IC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ID", piece: "ID", name: "ID", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-IE", piece: "IE", name: "IE", edgesAlgorithm: "", cornersAlgorithm: "(D' R' D : (F2 , D' R D R'))", learned: false },
  { id: "pair-IF", piece: "IF", name: "IF", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-IG", piece: "IG", name: "IG", edgesAlgorithm: "", cornersAlgorithm: "(R U D : (R' D R , U2))", learned: false },
  { id: "pair-IH", piece: "IH", name: "IH", edgesAlgorithm: "", cornersAlgorithm: "(U R U' : (F , U R' U' R))", learned: false },
  { id: "pair-II", piece: "II", name: "II", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-IJ", piece: "IJ", name: "IJ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-IK", piece: "IK", name: "IK", edgesAlgorithm: "", cornersAlgorithm: "(R U : (R' D R , U2))", learned: false },
  { id: "pair-IL", piece: "IL", name: "IL", edgesAlgorithm: "", cornersAlgorithm: "(R' F' R D U : (U2 , R' D' R)", learned: false },
  { id: "pair-IM", piece: "IM", name: "IM", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-IN", piece: "IN", name: "IN", edgesAlgorithm: "", cornersAlgorithm: "(R D' U : (R' D R , U2))", learned: false },
  { id: "pair-IO", piece: "IO", name: "IO", edgesAlgorithm: "", cornersAlgorithm: "(D R U : (R' D' R , U2))", learned: false },
  { id: "pair-IP", piece: "IP", name: "IP", edgesAlgorithm: "", cornersAlgorithm: "(R U D' : (R' D' R , U2))", learned: false },
  { id: "pair-IQ", piece: "IQ", name: "IQ", edgesAlgorithm: "", cornersAlgorithm: "(R U R' U D : (R D R' , U2))", learned: false },
  { id: "pair-IR", piece: "IR", name: "IR", edgesAlgorithm: "", cornersAlgorithm: "(D R' D : (F2 , D' R D R'))", learned: false },
  { id: "pair-IS", piece: "IS", name: "IS", edgesAlgorithm: "", cornersAlgorithm: "(R U : (R' D' R , U2))", learned: false },
  { id: "pair-IT", piece: "IT", name: "IT", edgesAlgorithm: "", cornersAlgorithm: "(D' R : (R D' R' , U2))", learned: false },
  { id: "pair-IU", piece: "IU", name: "IU", edgesAlgorithm: "", cornersAlgorithm: "(R U' R' D' : (R' D R , U2))", learned: false },
  { id: "pair-IV", piece: "IV", name: "IV", edgesAlgorithm: "", cornersAlgorithm: "(D R : (R D' R' , U2))", learned: false },
  { id: "pair-IW", piece: "IW", name: "IW", edgesAlgorithm: "", cornersAlgorithm: "(R : (R D' R' , U2))", learned: false },
  { id: "pair-IX", piece: "IX", name: "IX", edgesAlgorithm: "", cornersAlgorithm: "(U D : (R D R' , U2))", learned: false },
  { id: "pair-IY", piece: "IY", name: "IY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-IZ", piece: "IZ", name: "IZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-JA", piece: "JA", name: "JA", edgesAlgorithm: "(R' U : (S , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-JB", piece: "JB", name: "JB", edgesAlgorithm: "(E' : (R' E R , U'))", cornersAlgorithm: "", learned: false },
  { id: "pair-JC", piece: "JC", name: "JC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-JD", piece: "JD", name: "JD", edgesAlgorithm: "(L' E2' L , U)", cornersAlgorithm: "", learned: false },
  { id: "pair-JE", piece: "JE", name: "JE", edgesAlgorithm: "(M' : (R S' R' , U'))", cornersAlgorithm: "", learned: false },
  { id: "pair-JF", piece: "JF", name: "JF", edgesAlgorithm: "(R U' R' , E)", cornersAlgorithm: "", learned: false },
  { id: "pair-JG", piece: "JG", name: "JG", edgesAlgorithm: "(L' E2' : (L U L' , E))", cornersAlgorithm: "", learned: false },
  { id: "pair-JH", piece: "JH", name: "JH", edgesAlgorithm: "(R2 : (R' U' R , E'))", cornersAlgorithm: "", learned: false },
  { id: "pair-JI", piece: "JI", name: "JI", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-JJ", piece: "JJ", name: "JJ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-JK", piece: "JK", name: "JK", edgesAlgorithm: "(M' , U' R U)", cornersAlgorithm: "", learned: false },
  { id: "pair-JL", piece: "JL", name: "JL", edgesAlgorithm: "(R' U' R : (E , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-JM", piece: "JM", name: "JM", edgesAlgorithm: "(R U : (R' S' R , U))", cornersAlgorithm: "", learned: false },
  { id: "pair-JN", piece: "JN", name: "JN", edgesAlgorithm: "(R U' R' , E')", cornersAlgorithm: "", learned: false },
  { id: "pair-JO", piece: "JO", name: "JO", edgesAlgorithm: "(R' f R' : (S' , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-JP", piece: "JP", name: "JP", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-JQ", piece: "JQ", name: "JQ", edgesAlgorithm: "(M , U' R U)", cornersAlgorithm: "", learned: false },
  { id: "pair-JR", piece: "JR", name: "JR", edgesAlgorithm: "(R' U' R' : (E' , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-JS", piece: "JS", name: "JS", edgesAlgorithm: "(U2 : (M , U R U'))", cornersAlgorithm: "", learned: false },
  { id: "pair-JT", piece: "JT", name: "JT", edgesAlgorithm: "(U R' : (S , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-JU", piece: "JU", name: "JU", edgesAlgorithm: "(D' U L : (E' , L2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-JV", piece: "JV", name: "JV", edgesAlgorithm: "U R' U' R' U R U R U R' U2", cornersAlgorithm: "", learned: false },
  { id: "pair-JW", piece: "JW", name: "JW", edgesAlgorithm: "(M2' , U' R U)", cornersAlgorithm: "", learned: false },
  { id: "pair-JX", piece: "JX", name: "JX", edgesAlgorithm: "(U L : (E' , L2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-JY", piece: "JY", name: "JY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-JZ", piece: "JZ", name: "JZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-KA", piece: "KA", name: "KA", edgesAlgorithm: "(R' F' : (E , R U R'))", cornersAlgorithm: "(U D : (R D R' , U2))", learned: false },
  { id: "pair-KB", piece: "KB", name: "KB", edgesAlgorithm: "(R : (U' R' U , M'))", cornersAlgorithm: "(D' : (U , R' D R))", learned: false },
  { id: "pair-KC", piece: "KC", name: "KC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-KD", piece: "KD", name: "KD", edgesAlgorithm: "(L' : (U L U' , M'))", cornersAlgorithm: "(D' : (U' , R' D R))", learned: false },
  { id: "pair-KE", piece: "KE", name: "KE", edgesAlgorithm: "(l' : (U' L U , M'))", cornersAlgorithm: "(D' U R' : (R' D R , U'))", learned: false },
  { id: "pair-KF", piece: "KF", name: "KF", edgesAlgorithm: "(M' : (U' L' U , M'))", cornersAlgorithm: "(U R U' : (F , U R' U' R))", learned: false },
  { id: "pair-KG", piece: "KG", name: "KG", edgesAlgorithm: "(U : (S , L F L'))", cornersAlgorithm: "(U : (R U' R' , D))", learned: false },
  { id: "pair-KH", piece: "KH", name: "KH", edgesAlgorithm: "(M' : (U' L U , M'))", cornersAlgorithm: "(l' U : (R U' R' , D))", learned: false },
  { id: "pair-KI", piece: "KI", name: "KI", edgesAlgorithm: "", cornersAlgorithm: "(R' : (F2 , R D' R' D))", learned: false },
  { id: "pair-KJ", piece: "KJ", name: "KJ", edgesAlgorithm: "(U' R U , M')", cornersAlgorithm: "", learned: false },
  { id: "pair-KK", piece: "KK", name: "KK", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-KL", piece: "KL", name: "KL", edgesAlgorithm: "(U L' U' , M')", cornersAlgorithm: "(R' : (F' , R D' R' D))", learned: false },
  { id: "pair-KM", piece: "KM", name: "KM", edgesAlgorithm: "(r : (U R' U' , M'))", cornersAlgorithm: "", learned: false },
  { id: "pair-KN", piece: "KN", name: "KN", edgesAlgorithm: "(M' : (U R' U' , M'))", cornersAlgorithm: "(U' R' U : (R D R' , U2))", learned: false },
  { id: "pair-KO", piece: "KO", name: "KO", edgesAlgorithm: "(U' : (S' , R' F' R))", cornersAlgorithm: "(U : (R U' R' , D'))", learned: false },
  { id: "pair-KP", piece: "KP", name: "KP", edgesAlgorithm: "(M' : (U R U' , M'))", cornersAlgorithm: "", learned: false },
  { id: "pair-KQ", piece: "KQ", name: "KQ", edgesAlgorithm: "(U' : (S , R' F' R))", cornersAlgorithm: "(D' R' U : (R U' R' , D))", learned: false },
  { id: "pair-KR", piece: "KR", name: "KR", edgesAlgorithm: "(U L U' , M')", cornersAlgorithm: "(U' R' U2 : (R D R' , U))", learned: false },
  { id: "pair-KS", piece: "KS", name: "KS", edgesAlgorithm: "U M' U M U2 M U' M' U", cornersAlgorithm: "(U : (R U' R' , D2))", learned: false },
  { id: "pair-KT", piece: "KT", name: "KT", edgesAlgorithm: "(U' R' U , M')", cornersAlgorithm: "(R U R' U' : (D' , R U R'))", learned: false },
  { id: "pair-KU", piece: "KU", name: "KU", edgesAlgorithm: "", cornersAlgorithm: "(U R U' : (F2' , U R' U' R))", learned: false },
  { id: "pair-KV", piece: "KV", name: "KV", edgesAlgorithm: "(U R' F' R' : (S , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-KW", piece: "KW", name: "KW", edgesAlgorithm: "(D : (R F R' , S'))", cornersAlgorithm: "(U R' D' : (U' , R' D R))", learned: false },
  { id: "pair-KX", piece: "KX", name: "KX", edgesAlgorithm: "(U' L F L : (S' , L2'))", cornersAlgorithm: "(R' D' R : (R U R' , D))", learned: false },
  { id: "pair-KY", piece: "KY", name: "KY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-KZ", piece: "KZ", name: "KZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-LA", piece: "LA", name: "LA", edgesAlgorithm: "(L U' : (S' , L2'))", cornersAlgorithm: "(D' U : (R D' R' , U2))", learned: false },
  { id: "pair-LB", piece: "LB", name: "LB", edgesAlgorithm: "(R E2 R' , U')", cornersAlgorithm: "(D : (U , R' D' R))", learned: false },
  { id: "pair-LC", piece: "LC", name: "LC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-LD", piece: "LD", name: "LD", edgesAlgorithm: "(U2 : (R E2 R' , U))", cornersAlgorithm: "(D : (U' , R' D' R))", learned: false },
  { id: "pair-LE", piece: "LE", name: "LE", edgesAlgorithm: "(L' U' : (L S L' , U'))", cornersAlgorithm: "(R U2 : (R' D R , U'))", learned: false },
  { id: "pair-LF", piece: "LF", name: "LF", edgesAlgorithm: "", cornersAlgorithm: "(D R' U' : (R U R' , D'))", learned: false },
  { id: "pair-LG", piece: "LG", name: "LG", edgesAlgorithm: "(L f' L : (S , L2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-LH", piece: "LH", name: "LH", edgesAlgorithm: "(L' U L , E)", cornersAlgorithm: "(D : (R U R' , D))", learned: false },
  { id: "pair-LI", piece: "LI", name: "LI", edgesAlgorithm: "", cornersAlgorithm: "(R U' : (R' D R , U U))", learned: false },
  { id: "pair-LJ", piece: "LJ", name: "LJ", edgesAlgorithm: "(R' U' R' : (E , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-LK", piece: "LK", name: "LK", edgesAlgorithm: "(M' , U L' U')", cornersAlgorithm: "(D' R' D : (F' , D' R D R'))", learned: false },
  { id: "pair-LL", piece: "LL", name: "LL", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-LM", piece: "LM", name: "LM", edgesAlgorithm: "(M' : (L' S L , U))", cornersAlgorithm: "", learned: false },
  { id: "pair-LN", piece: "LN", name: "LN", edgesAlgorithm: "(L' : (U , L' E L))", cornersAlgorithm: "(U R U D : (R' D' R , U2))", learned: false },
  { id: "pair-LO", piece: "LO", name: "LO", edgesAlgorithm: "(R E2 : (R' U' R , E'))", cornersAlgorithm: "(R D2 : (R' U' R , D'))", learned: false },
  { id: "pair-LP", piece: "LP", name: "LP", edgesAlgorithm: "(L' U L , E')", cornersAlgorithm: "(D , R U R')", learned: false },
  { id: "pair-LQ", piece: "LQ", name: "LQ", edgesAlgorithm: "(M , U L' U')", cornersAlgorithm: "(R' F : (R U' R' , D))", learned: false },
  { id: "pair-LR", piece: "LR", name: "LR", edgesAlgorithm: "(U' L : (S' , L2'))", cornersAlgorithm: "(D R' : (D , R' U R))", learned: false },
  { id: "pair-LS", piece: "LS", name: "LS", edgesAlgorithm: "(U' R' B : (E , R2))", cornersAlgorithm: "(D' R D' : (R' U' R , D2))", learned: false },
  { id: "pair-LT", piece: "LT", name: "LT", edgesAlgorithm: "(R U' R' : (E , R2))", cornersAlgorithm: "(D : (R U R' , D2))", learned: false },
  { id: "pair-LU", piece: "LU", name: "LU", edgesAlgorithm: "(U' D R' : (E , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-LV", piece: "LV", name: "LV", edgesAlgorithm: "(U' R' : (E , R2))", cornersAlgorithm: "(R U' R' : (R' D R , U2))", learned: false },
  { id: "pair-LW", piece: "LW", name: "LW", edgesAlgorithm: "(M2' , U L' U')", cornersAlgorithm: "(D R : (R D' R' , U'))", learned: false },
  { id: "pair-LX", piece: "LX", name: "LX", edgesAlgorithm: "U' L U L U' L' U' L' U' L U2'", cornersAlgorithm: "(D R D : (U , R' D' R))", learned: false },
  { id: "pair-LY", piece: "LY", name: "LY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-LZ", piece: "LZ", name: "LZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-MA", piece: "MA", name: "MA", edgesAlgorithm: "(U M U' : (M , U2))", cornersAlgorithm: "", learned: false },
  { id: "pair-MB", piece: "MB", name: "MB", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-MC", piece: "MC", name: "MC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-MD", piece: "MD", name: "MD", edgesAlgorithm: "(R' F R , S)", cornersAlgorithm: "", learned: false },
  { id: "pair-ME", piece: "ME", name: "ME", edgesAlgorithm: "(M U' : (M' , U2))", cornersAlgorithm: "", learned: false },
  { id: "pair-MF", piece: "MF", name: "MF", edgesAlgorithm: "(M L' U' : (M' , U2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-MG", piece: "MG", name: "MG", edgesAlgorithm: "(L F' L' : (S' , L2))", cornersAlgorithm: "", learned: false },
  { id: "pair-MH", piece: "MH", name: "MH", edgesAlgorithm: "(R F : (E' , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-MI", piece: "MI", name: "MI", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-MJ", piece: "MJ", name: "MJ", edgesAlgorithm: "(R U2' : (R' S' R , U'))", cornersAlgorithm: "", learned: false },
  { id: "pair-MK", piece: "MK", name: "MK", edgesAlgorithm: "(r : (M' , U R' U'))", cornersAlgorithm: "", learned: false },
  { id: "pair-ML", piece: "ML", name: "ML", edgesAlgorithm: "(M' : (U , L' S L))", cornersAlgorithm: "", learned: false },
  { id: "pair-MM", piece: "MM", name: "MM", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-MN", piece: "MN", name: "MN", edgesAlgorithm: "(S' : (U , L' E L))", cornersAlgorithm: "", learned: false },
  { id: "pair-MO", piece: "MO", name: "MO", edgesAlgorithm: "(r U' R : (S , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-MP", piece: "MP", name: "MP", edgesAlgorithm: "(S' : (U , L E' L'))", cornersAlgorithm: "", learned: false },
  { id: "pair-MQ", piece: "MQ", name: "MQ", edgesAlgorithm: "(R : (U R' U' , M'))", cornersAlgorithm: "", learned: false },
  { id: "pair-MR", piece: "MR", name: "MR", edgesAlgorithm: "(M' : (U , R E' R'))", cornersAlgorithm: "", learned: false },
  { id: "pair-MS", piece: "MS", name: "MS", edgesAlgorithm: "M' : (U' M' U' M)2", cornersAlgorithm: "", learned: false },
  { id: "pair-MT", piece: "MT", name: "MT", edgesAlgorithm: "(U L' F' : (L2 , E))", cornersAlgorithm: "", learned: false },
  { id: "pair-MU", piece: "MU", name: "MU", edgesAlgorithm: "(R F : (R2' , E))", cornersAlgorithm: "", learned: false },
  { id: "pair-MV", piece: "MV", name: "MV", edgesAlgorithm: "(R' F R , S')", cornersAlgorithm: "", learned: false },
  { id: "pair-MW", piece: "MW", name: "MW", edgesAlgorithm: "(R M : (U R' U' , M2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-MX", piece: "MX", name: "MX", edgesAlgorithm: "(R2' : (R F R' , S'))", cornersAlgorithm: "", learned: false },
  { id: "pair-MY", piece: "MY", name: "MY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-MZ", piece: "MZ", name: "MZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-NA", piece: "NA", name: "NA", edgesAlgorithm: "(U' : (L' E L , U2'))", cornersAlgorithm: "(R' U D R : (D' , R U' R'))", learned: false },
  { id: "pair-NB", piece: "NB", name: "NB", edgesAlgorithm: "(U2' : (L' E L , U'))", cornersAlgorithm: "", learned: false },
  { id: "pair-NC", piece: "NC", name: "NC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ND", piece: "ND", name: "ND", edgesAlgorithm: "(L' E L , U)", cornersAlgorithm: "(U' R2' : (D' , R U2 R'))", learned: false },
  { id: "pair-NE", piece: "NE", name: "NE", edgesAlgorithm: "(Rw' U' : (M' , U2))", cornersAlgorithm: "(R : (U , R2 D R2 D' R2))", learned: false },
  { id: "pair-NF", piece: "NF", name: "NF", edgesAlgorithm: "(r U R : (E , R2'))", cornersAlgorithm: "(R U' D' R' : (R' U R , D))", learned: false },
  { id: "pair-NG", piece: "NG", name: "NG", edgesAlgorithm: "(L F' : (L2' , E))", cornersAlgorithm: "(U R U' : (R' D R , U2))", learned: false },
  { id: "pair-NH", piece: "NH", name: "NH", edgesAlgorithm: "(u R' : (S , R2))", cornersAlgorithm: "(U R : (U2 , R D' R'))", learned: false },
  { id: "pair-NI", piece: "NI", name: "NI", edgesAlgorithm: "", cornersAlgorithm: "(R' F' R D U : (R' D' R , U2)", learned: false },
  { id: "pair-NJ", piece: "NJ", name: "NJ", edgesAlgorithm: "(E' , R U' R')", cornersAlgorithm: "", learned: false },
  { id: "pair-NK", piece: "NK", name: "NK", edgesAlgorithm: "(M2' : (U R' U' , M))", cornersAlgorithm: "(U' R' U' : (R D R' , U2))", learned: false },
  { id: "pair-NL", piece: "NL", name: "NL", edgesAlgorithm: "(L2' : (E , L U' L'))", cornersAlgorithm: "(U R U' D : (R' D' R , U2))", learned: false },
  { id: "pair-NM", piece: "NM", name: "NM", edgesAlgorithm: "(S' : (L' E L , U))", cornersAlgorithm: "", learned: false },
  { id: "pair-NN", piece: "NN", name: "NN", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-NO", piece: "NO", name: "NO", edgesAlgorithm: "(R , U' S U)", cornersAlgorithm: "(U R U' : (R' D' R , U2))", learned: false },
  { id: "pair-NP", piece: "NP", name: "NP", edgesAlgorithm: "(M' U' R : (S , R2'))", cornersAlgorithm: "(U' R' D U' : (R D' R' , U2))", learned: false },
  { id: "pair-NQ", piece: "NQ", name: "NQ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-NR", piece: "NR", name: "NR", edgesAlgorithm: "(U R' U' , M')", cornersAlgorithm: "(U R2 U' : (D' , R U R'))", learned: false },
  { id: "pair-NS", piece: "NS", name: "NS", edgesAlgorithm: "(E , L U L')", cornersAlgorithm: "(U' R' U' : (R D' R' , U2))", learned: false },
  { id: "pair-NT", piece: "NT", name: "NT", edgesAlgorithm: "", cornersAlgorithm: "(R' F' R D' U : (R' D R , U2))", learned: false },
  { id: "pair-NU", piece: "NU", name: "NU", edgesAlgorithm: "(U M : (U' , l' E l))", cornersAlgorithm: "(U' R' : (R' D R , U2))", learned: false },
  { id: "pair-NV", piece: "NV", name: "NV", edgesAlgorithm: "(r U' : (S , R2'))", cornersAlgorithm: "(D' U' R' : (R' D R , U2))", learned: false },
  { id: "pair-NW", piece: "NW", name: "NW", edgesAlgorithm: "(u' R : (E' , R2'))", cornersAlgorithm: "(U R U' D' : (R' D R , U2))", learned: false },
  { id: "pair-NX", piece: "NX", name: "NX", edgesAlgorithm: "(M : (U R' U' , M2'))", cornersAlgorithm: "(D U' R' : (R' D R , U2))", learned: false },
  { id: "pair-NY", piece: "NY", name: "NY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-NZ", piece: "NZ", name: "NZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-OA", piece: "OA", name: "OA", edgesAlgorithm: "(U : (R E R' , U2))", cornersAlgorithm: "(U : (R D R' , U2))", learned: false },
  { id: "pair-OB", piece: "OB", name: "OB", edgesAlgorithm: "(R E R' , U')", cornersAlgorithm: "(R D R' , U')", learned: false },
  { id: "pair-OC", piece: "OC", name: "OC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-OD", piece: "OD", name: "OD", edgesAlgorithm: "(U2 : (R E R' , U))", cornersAlgorithm: "(U2 : (R D R' , U))", learned: false },
  { id: "pair-OE", piece: "OE", name: "OE", edgesAlgorithm: "(R' F R' : (S , R2))", cornersAlgorithm: "(U' R' F R : (R D R' , U'))", learned: false },
  { id: "pair-OF", piece: "OF", name: "OF", edgesAlgorithm: "(M' U R : (E , R2'))", cornersAlgorithm: "(D' R : (R' U R U' , F))", learned: false },
  { id: "pair-OG", piece: "OG", name: "OG", edgesAlgorithm: "(L F' L : (S , L2'))", cornersAlgorithm: "(U D' : (R U' R' , D2))", learned: false },
  { id: "pair-OH", piece: "OH", name: "OH", edgesAlgorithm: "(R' F : (E' , R2))", cornersAlgorithm: "(R D : (R' U' R , D2))", learned: false },
  { id: "pair-OI", piece: "OI", name: "OI", edgesAlgorithm: "", cornersAlgorithm: "(R D' U' : (R' D R , U2))", learned: false },
  { id: "pair-OJ", piece: "OJ", name: "OJ", edgesAlgorithm: "(R' f R : (S' , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-OK", piece: "OK", name: "OK", edgesAlgorithm: "(U' : (R' F' R , S'))", cornersAlgorithm: "(U : (D' , R U' R'))", learned: false },
  { id: "pair-OL", piece: "OL", name: "OL", edgesAlgorithm: "(R E : (R' U' R , E))", cornersAlgorithm: "(R D : (R' U' R , D))", learned: false },
  { id: "pair-OM", piece: "OM", name: "OM", edgesAlgorithm: "(r U' R' : (S , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-ON", piece: "ON", name: "ON", edgesAlgorithm: "(U' S U , R)", cornersAlgorithm: "(U R U : (R' D' R , U2))", learned: false },
  { id: "pair-OO", piece: "OO", name: "OO", edgesAlgorithm: "", cornersAlgorithm: "(R D' : (R' D R , U))", learned: false },
  { id: "pair-OP", piece: "OP", name: "OP", edgesAlgorithm: "(U' S U , R')", cornersAlgorithm: "(U' R U : (R' U' R , D))", learned: false },
  { id: "pair-OQ", piece: "OQ", name: "OQ", edgesAlgorithm: "(R : (U R U' , M'))", cornersAlgorithm: "(R B' : (R' U' R , D))", learned: false },
  { id: "pair-OR", piece: "OR", name: "OR", edgesAlgorithm: "(R' E' : (R U' R' , E'))", cornersAlgorithm: "(U' : (R' U' R , D'))", learned: false },
  { id: "pair-OS", piece: "OS", name: "OS", edgesAlgorithm: "(U' r' : (R U R' , E'))", cornersAlgorithm: "(U' R' : (R' D R , U))", learned: false },
  { id: "pair-OT", piece: "OT", name: "OT", edgesAlgorithm: "(S U L : (E , L2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-OU", piece: "OU", name: "OU", edgesAlgorithm: "(R' F : (E , R2))", cornersAlgorithm: "(D' U R U' : (F2 , U R' U' R))", learned: false },
  { id: "pair-OV", piece: "OV", name: "OV", edgesAlgorithm: "", cornersAlgorithm: "(U D' R D' : (U' , R' D R))", learned: false },
  { id: "pair-OW", piece: "OW", name: "OW", edgesAlgorithm: "(U' : (S , R' B R))", cornersAlgorithm: "", learned: false },
  { id: "pair-OX", piece: "OX", name: "OX", edgesAlgorithm: "(R F R' , S'))", cornersAlgorithm: "", learned: false },
  { id: "pair-OY", piece: "OY", name: "OY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-OZ", piece: "OZ", name: "OZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
 { id: "pair-PA", piece: "PA", name: "PA", edgesAlgorithm: "(U' : (L E' L' , U2'))", cornersAlgorithm: "(U2 , R' D' R)", learned: false },
  { id: "pair-PB", piece: "PB", name: "PB", edgesAlgorithm: "(U2' : (L E' L' , U'))", cornersAlgorithm: "(U , R' D' R)", learned: false },
  { id: "pair-PC", piece: "PC", name: "PC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-PD", piece: "PD", name: "PD", edgesAlgorithm: "(L E' L' , U)", cornersAlgorithm: "(U' , R' D' R)", learned: false },
  { id: "pair-PE", piece: "PE", name: "PE", edgesAlgorithm: "(R M U' : (M' , U2))", cornersAlgorithm: "(U R' U' : (R D R' , U'))", learned: false },
  { id: "pair-PF", piece: "PF", name: "PF", edgesAlgorithm: "(U' E' L : (S' , L2'))", cornersAlgorithm: "(R' U' : (R U R' , D'))", learned: false },
  { id: "pair-PG", piece: "PG", name: "PG", edgesAlgorithm: "(M' U' L : (E' , L2'))", cornersAlgorithm: "(U R' D' : (R U' R' , D2))", learned: false },
  { id: "pair-PH", piece: "PH", name: "PH", edgesAlgorithm: "(l' U' L : (E' , L2'))", cornersAlgorithm: "(R U R' , D2)", learned: false },
  { id: "pair-PI", piece: "PI", name: "PI", edgesAlgorithm: "", cornersAlgorithm: "(D R U' : (R' D' R , U2))", learned: false },
  { id: "pair-PJ", piece: "PJ", name: "PJ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-PK", piece: "PK", name: "PK", edgesAlgorithm: "(M2' : (U R U' , M))", cornersAlgorithm: "", learned: false },
  { id: "pair-PL", piece: "PL", name: "PL", edgesAlgorithm: "(E' , L' U L)", cornersAlgorithm: "(R U R' , D)", learned: false },
  { id: "pair-PM", piece: "PM", name: "PM", edgesAlgorithm: "(S' : (L E' L' , U))", cornersAlgorithm: "", learned: false },
  { id: "pair-PN", piece: "PN", name: "PN", edgesAlgorithm: "(M' U' R' : (S , R2))", cornersAlgorithm: "(U' R' D U : (R D' R' , U2))", learned: false },
  { id: "pair-PO", piece: "PO", name: "PO", edgesAlgorithm: "(R' , U' S U)", cornersAlgorithm: "(R D' : (U , R' D R))", learned: false },
  { id: "pair-PP", piece: "PP", name: "PP", edgesAlgorithm: "", cornersAlgorithm: "(R' U : (R U' R' , D'))", learned: false },
  { id: "pair-PQ", piece: "PQ", name: "PQ", edgesAlgorithm: "(U R U' , M')", cornersAlgorithm: "", learned: false },
  { id: "pair-PR", piece: "PR", name: "PR", edgesAlgorithm: "(L2 : (E' , L' U L))", cornersAlgorithm: "(R' : (D , R' U R))", learned: false },
  { id: "pair-PS", piece: "PS", name: "PS", edgesAlgorithm: "(U l : (L' U' L , E'))", cornersAlgorithm: "(U R' D' : (R U' R' , D'))", learned: false },
  { id: "pair-PT", piece: "PT", name: "PT", edgesAlgorithm: "(E , R' U' R)", cornersAlgorithm: "(R U R' , D')", learned: false },
  { id: "pair-PU", piece: "PU", name: "PU", edgesAlgorithm: "(U' L F2' : (L' S' L , F'))", cornersAlgorithm: "(R D : (U , R' D' R))", learned: false },
  { id: "pair-PV", piece: "PV", name: "PV", edgesAlgorithm: "(U' E' R' : (E , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-PW", piece: "PW", name: "PW", edgesAlgorithm: "(M : (U R U' , M2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-PX", piece: "PX", name: "PX", edgesAlgorithm: "(U E L' : (E , L2))", cornersAlgorithm: "", learned: false },
  { id: "pair-PY", piece: "PY", name: "PY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-PZ", piece: "PZ", name: "PZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-QA", piece: "QA", name: "QA", edgesAlgorithm: "", cornersAlgorithm: "(R' U' D : (R D R' , U2))", learned: false },
  { id: "pair-QB", piece: "QB", name: "QB", edgesAlgorithm: "(R' : (U' R U , M))", cornersAlgorithm: "", learned: false },
  { id: "pair-QC", piece: "QC", name: "QC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-QD", piece: "QD", name: "QD", edgesAlgorithm: "(L : (U L' U' , M))", cornersAlgorithm: "(R' D' : (R' D R , U'))", learned: false },
  { id: "pair-QE", piece: "QE", name: "QE", edgesAlgorithm: "(l' : (U' L U , M))", cornersAlgorithm: "(F' L F , R')", learned: false },
  { id: "pair-QF", piece: "QF", name: "QF", edgesAlgorithm: "(M' , U' L' U)", cornersAlgorithm: "(R' F : (D , R U R'))", learned: false },
  { id: "pair-QG", piece: "QG", name: "QG", edgesAlgorithm: "(l' : (U' L' U , M))", cornersAlgorithm: "(R' U : (D , R U' R'))", learned: false },
  { id: "pair-QH", piece: "QH", name: "QH", edgesAlgorithm: "(M' , U' L U)", cornersAlgorithm: "(R , U' L U)", learned: false },
  { id: "pair-QI", piece: "QI", name: "QI", edgesAlgorithm: "", cornersAlgorithm: "(R D' U' : (R' D' R , U2))", learned: false },
  { id: "pair-QJ", piece: "QJ", name: "QJ", edgesAlgorithm: "(U' R U , M)", cornersAlgorithm: "", learned: false },
  { id: "pair-QK", piece: "QK", name: "QK", edgesAlgorithm: "(U' : (R' F' R , S)", cornersAlgorithm: "(D' R' U : (D , R U' R'))", learned: false },
  { id: "pair-QL", piece: "QL", name: "QL", edgesAlgorithm: "(U L' U' , M)", cornersAlgorithm: "(R' F : (D , R U' R'))", learned: false },
  { id: "pair-QM", piece: "QM", name: "QM", edgesAlgorithm: "(r : (U R' U' , M))", cornersAlgorithm: "", learned: false },
  { id: "pair-QN", piece: "QN", name: "QN", edgesAlgorithm: "(M' , U R' U')", cornersAlgorithm: "", learned: false },
  { id: "pair-QO", piece: "QO", name: "QO", edgesAlgorithm: "(r : (U R U' , M))", cornersAlgorithm: "(U' R U : (D , R' U' R))", learned: false },
  { id: "pair-QP", piece: "QP", name: "QP", edgesAlgorithm: "(M' , U R U')", cornersAlgorithm: "(R' U : (D' , R U' R'))", learned: false },
  { id: "pair-QQ", piece: "QQ", name: "QQ", edgesAlgorithm: "", cornersAlgorithm: "(R , U' L' U)", learned: false },
  { id: "pair-QR", piece: "QR", name: "QR", edgesAlgorithm: "(U L U' , M)", cornersAlgorithm: "", learned: false },
  { id: "pair-QS", piece: "QS", name: "QS", edgesAlgorithm: "(U' : (R B R' , S))", cornersAlgorithm: "(D R' U : (D , R U' R'))", learned: false },
  { id: "pair-QT", piece: "QT", name: "QT", edgesAlgorithm: "(U' R' U , M)", cornersAlgorithm: "(R U' : (R' U R , D))", learned: false },
  { id: "pair-QU", piece: "QU", name: "QU", edgesAlgorithm: "(U : (S , R' F' R))", cornersAlgorithm: "(D' R U' : (R' U R , D'))", learned: false },
  { id: "pair-QV", piece: "QV", name: "QV", edgesAlgorithm: "(R' : (U' R' U , M))", cornersAlgorithm: "(U R' U' : (R U R' , D'))", learned: false },
  { id: "pair-QW", piece: "QW", name: "QW", edgesAlgorithm: "(U : (S , R B R'))", cornersAlgorithm: "(D R U' : (R' U R , D'))", learned: false },
  { id: "pair-QX", piece: "QX", name: "QX", edgesAlgorithm: "(L : (U L U' , M))", cornersAlgorithm: "(R U' : (R' U R , D'))", learned: false },
  { id: "pair-QY", piece: "QY", name: "QY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-QZ", piece: "QZ", name: "QZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-RA", piece: "RA", name: "RA", edgesAlgorithm: "(L' U : (L2 , S'))", cornersAlgorithm: "", learned: false },
  { id: "pair-RB", piece: "RB", name: "RB", edgesAlgorithm: "(R' E2 R , U')", cornersAlgorithm: "(R2 U : (D , R' U' R))", learned: false },
  { id: "pair-RC", piece: "RC", name: "RC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-RD", piece: "RD", name: "RD", edgesAlgorithm: "(U2 : (R' E2 R , U))", cornersAlgorithm: "(U' R2' : (D' , R U' R'))", learned: false },
  { id: "pair-RE", piece: "RE", name: "RE", edgesAlgorithm: "(U' R F : (E' , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-RF", piece: "RF", name: "RF", edgesAlgorithm: "(L U L' , E')", cornersAlgorithm: "(F , l U' l')", learned: false },
  { id: "pair-RG", piece: "RG", name: "RG", edgesAlgorithm: "(S' U' R : (E' , R2'))", cornersAlgorithm: "(R B' R' : (U , R' D R))", learned: false },
  { id: "pair-RH", piece: "RH", name: "RH", edgesAlgorithm: "", cornersAlgorithm: "(U D R' F' : (R U' R' , D))", learned: false },
  { id: "pair-RI", piece: "RI", name: "RI", edgesAlgorithm: "", cornersAlgorithm: "(R U R' D' : (R' D R , U2))", learned: false },
  { id: "pair-RJ", piece: "RJ", name: "RJ", edgesAlgorithm: "(R' U' R : (E' , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-RK", piece: "RK", name: "RK", edgesAlgorithm: "(M' , U L U')", cornersAlgorithm: "(U' R' U' : (R D R' , U'))", learned: false },
  { id: "pair-RL", piece: "RL", name: "RL", edgesAlgorithm: "(U' L' : (S' , L2))", cornersAlgorithm: "(D R' : (R' U R , D))", learned: false },
  { id: "pair-RM", piece: "RM", name: "RM", edgesAlgorithm: "(M' : (R E' R' , U))", cornersAlgorithm: "", learned: false },
  { id: "pair-RN", piece: "RN", name: "RN", edgesAlgorithm: "(L U L' , E)", cornersAlgorithm: "(U R2 U' : (R U R' , D'))", learned: false },
  { id: "pair-RO", piece: "RO", name: "RO", edgesAlgorithm: "(R' E2 : (R U' R' , E))", cornersAlgorithm: "(R B' : (D , R' U' R))", learned: false },
  { id: "pair-RP", piece: "RP", name: "RP", edgesAlgorithm: "(L2 : (L' U L , E'))", cornersAlgorithm: "(R2' : (U , R D R'))", learned: false },
  { id: "pair-RQ", piece: "RQ", name: "RQ", edgesAlgorithm: "(M , U L U')", cornersAlgorithm: "(U' L' U , R)", learned: false },
  { id: "pair-RR", piece: "RR", name: "RR", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-RS", piece: "RS", name: "RS", edgesAlgorithm: "(U2' : (M , U' L U))", cornersAlgorithm: "(U' R' U' : (R D' R' , U'))", learned: false },
  { id: "pair-RT", piece: "RT", name: "RT", edgesAlgorithm: "(R U' R : (E' , R2'))", cornersAlgorithm: "(D' R2' : (U , R D R'))", learned: false },
  { id: "pair-RU", piece: "RU", name: "RU", edgesAlgorithm: "(D U' R : (E' , R2'))", cornersAlgorithm: "(U' R' : (R' D R , U'))", learned: false },
  { id: "pair-RV", piece: "RV", name: "RV", edgesAlgorithm: "(U' R : (E' , R2'))", cornersAlgorithm: "(D' U' R' : (R' D R , U'))", learned: false },
  { id: "pair-RW", piece: "RW", name: "RW", edgesAlgorithm: "(M2 , U L U')", cornersAlgorithm: "(U R : (D' , R U' R'))", learned: false },
  { id: "pair-RX", piece: "RX", name: "RX", edgesAlgorithm: "U' L' U' L' U L U L U L'", cornersAlgorithm: "(R2 U : (D' , R' U' R))", learned: false },
  { id: "pair-RY", piece: "RY", name: "RY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-RZ", piece: "RZ", name: "RZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-SA", piece: "SA", name: "SA", edgesAlgorithm: "(U R' B R : (S , R2'))", cornersAlgorithm: "(U D' : (R D R' , U2))", learned: false },
  { id: "pair-SB", piece: "SB", name: "SB", edgesAlgorithm: "(M U' M' U')2", cornersAlgorithm: "(D' : (R D R' , U'))", learned: false },
  { id: "pair-SC", piece: "SC", name: "SC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-SD", piece: "SD", name: "SD", edgesAlgorithm: "(M U M' U)2", cornersAlgorithm: "(D : (U' , R' D R))", learned: false },
  { id: "pair-SE", piece: "SE", name: "SE", edgesAlgorithm: "M2' : (U' M U' M')2", cornersAlgorithm: "(D U R' : (R' D R , U'))", learned: false },
  { id: "pair-SF", piece: "SF", name: "SF", edgesAlgorithm: "(U' r' : (E , R U R'))", cornersAlgorithm: "(F , l U2 l')", learned: false },
  { id: "pair-SG", piece: "SG", name: "SG", edgesAlgorithm: "(U l : (E , L' U' L))", cornersAlgorithm: "(U D2 : (R U' R' , D'))", learned: false },
  { id: "pair-SH", piece: "SH", name: "SH", edgesAlgorithm: "(U' M : (L S L' , U))", cornersAlgorithm: "", learned: false },
  { id: "pair-SI", piece: "SI", name: "SI", edgesAlgorithm: "", cornersAlgorithm: "(D R' D : (F2 , D' R D R'))", learned: false },
  { id: "pair-SJ", piece: "SJ", name: "SJ", edgesAlgorithm: "(U2' : (U R U' , M))", cornersAlgorithm: "", learned: false },
  { id: "pair-SK", piece: "SK", name: "SK", edgesAlgorithm: "U M U M' U2 M' U' M U", cornersAlgorithm: "(U : (D2 , R U' R'))", learned: false },
  { id: "pair-SL", piece: "SL", name: "SL", edgesAlgorithm: "(U' R' B : (R2 , E))", cornersAlgorithm: "(D' R D : (R' U' R , D2))", learned: false },
  { id: "pair-SM", piece: "SM", name: "SM", edgesAlgorithm: "M2' : (U M U M')2", cornersAlgorithm: "", learned: false },
  { id: "pair-SN", piece: "SN", name: "SN", edgesAlgorithm: "(U M : (R' S' R , U'))", cornersAlgorithm: "(U' R' U : (R D' R' , U2))", learned: false },
  { id: "pair-SO", piece: "SO", name: "SO", edgesAlgorithm: "(U' r' : (E' , R U R'))", cornersAlgorithm: "(U' : (D' , R' U' R))", learned: false },
  { id: "pair-SP", piece: "SP", name: "SP", edgesAlgorithm: "(U l : (E' , L' U' L))", cornersAlgorithm: "(U R' D' : (D' , R U' R'))", learned: false },
  { id: "pair-SQ", piece: "SQ", name: "SQ", edgesAlgorithm: "(U' : (S , R B R'))", cornersAlgorithm: "(D R' U : (R U' R' , D))", learned: false },
  { id: "pair-SR", piece: "SR", name: "SR", edgesAlgorithm: "(U2 : (U' L U , M))", cornersAlgorithm: "(U' R' U2 : (R D' R' , U))", learned: false },
  { id: "pair-SS", piece: "SS", name: "SS", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ST", piece: "ST", name: "ST", edgesAlgorithm: "(U2' : (U R' U' , M))", cornersAlgorithm: "(D2' R' : (F' , R D' R' D))", learned: false },
  { id: "pair-SU", piece: "SU", name: "SU", edgesAlgorithm: "(D' : (R F R' , S'))", cornersAlgorithm: "(U' D' R' D' : (U' , R D R'))", learned: false },
  { id: "pair-SV", piece: "SV", name: "SV", edgesAlgorithm: "(U L B' L' : (S , L2))", cornersAlgorithm: "(U' D' R' : (R' D R , U))", learned: false },
  { id: "pair-SW", piece: "SW", name: "SW", edgesAlgorithm: "", cornersAlgorithm: "(U R : (D2 , R U' R'))", learned: false },
  { id: "pair-SX", piece: "SX", name: "SX", edgesAlgorithm: "(U' R' B R : (S' , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-SY", piece: "SY", name: "SY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-SZ", piece: "SZ", name: "SZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-TA", piece: "TA", name: "TA", edgesAlgorithm: "(R U' : (R2' , S))", cornersAlgorithm: "(U D : (R D' R' , U2))", learned: false },
  { id: "pair-TB", piece: "TB", name: "TB", edgesAlgorithm: "(E : (R E' R' , U'))", cornersAlgorithm: "(D : (R D' R' , U'))", learned: false },
  { id: "pair-TC", piece: "TC", name: "TC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-TD", piece: "TD", name: "TD", edgesAlgorithm: "(L E2' L' , U)", cornersAlgorithm: "(D' : (U' , R' D' R))", learned: false },
  { id: "pair-TE", piece: "TE", name: "TE", edgesAlgorithm: "(l' : (E , L U' L'))", cornersAlgorithm: "(R U2 : (R' D' R , U'))", learned: false },
  { id: "pair-TF", piece: "TF", name: "TF", edgesAlgorithm: "(R2' : (R U' R' , E))", cornersAlgorithm: "(D' R' U' : (R U R' , D'))", learned: false },
  { id: "pair-TG", piece: "TG", name: "TG", edgesAlgorithm: "(L E2' : (L' U L , E'))", cornersAlgorithm: "(R' D R2 : (U , R' D' R))", learned: false },
  { id: "pair-TH", piece: "TH", name: "TH", edgesAlgorithm: "(R' U' R , E')", cornersAlgorithm: "(D' : (R U R' , D'))", learned: false },
  { id: "pair-TI", piece: "TI", name: "TI", edgesAlgorithm: "", cornersAlgorithm: "(R U' : (R' D' R , U2))", learned: false },
  { id: "pair-TJ", piece: "TJ", name: "TJ", edgesAlgorithm: "(U R : (S , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-TK", piece: "TK", name: "TK", edgesAlgorithm: "(M' , U' R' U)", cornersAlgorithm: "(R U R' U' : (R U R' , D'))", learned: false },
  { id: "pair-TL", piece: "TL", name: "TL", edgesAlgorithm: "(R U' R : (E , R2'))", cornersAlgorithm: "(D' : (R U R' , D2))", learned: false },
  { id: "pair-TM", piece: "TM", name: "TM", edgesAlgorithm: "(R u' R' : (E' , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-TN", piece: "TN", name: "TN", edgesAlgorithm: "", cornersAlgorithm: "(R' F' R D' U' : (R' D R , U2))", learned: false },
  { id: "pair-TO", piece: "TO", name: "TO", edgesAlgorithm: "(S U L' : (E , L2))", cornersAlgorithm: "", learned: false },
  { id: "pair-TP", piece: "TP", name: "TP", edgesAlgorithm: "(R' U' R , E)", cornersAlgorithm: "(D' , R U R')", learned: false },
  { id: "pair-TQ", piece: "TQ", name: "TQ", edgesAlgorithm: "(M , U' R' U)", cornersAlgorithm: "(R U' : (D , R' U R))", learned: false },
  { id: "pair-TR", piece: "TR", name: "TR", edgesAlgorithm: "(R U' R' : (E' , R2))", cornersAlgorithm: "(D' R' : (D , R' U R))", learned: false },
  { id: "pair-TS", piece: "TS", name: "TS", edgesAlgorithm: "(U2 : (M , U R' U'))", cornersAlgorithm: "(D R' D : (F' , D' R D R'))", learned: false },
  { id: "pair-TT", piece: "TT", name: "TT", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-TU", piece: "TU", name: "TU", edgesAlgorithm: "(U R' U : (M' , U2))", cornersAlgorithm: "(D' R : (R D' R' , U'))", learned: false },
  { id: "pair-TV", piece: "TV", name: "TV", edgesAlgorithm: "U R U R U' R' U' R' U' R", cornersAlgorithm: "(D' R D : (U , R' D' R))", learned: false },
  { id: "pair-TW", piece: "TW", name: "TW", edgesAlgorithm: "(M2' , U' R' U)", cornersAlgorithm: "", learned: false },
  { id: "pair-TX", piece: "TX", name: "TX", edgesAlgorithm: "(U L' : (E , L2))", cornersAlgorithm: "(R U' D : (R' U R , D2))", learned: false },
  { id: "pair-TY", piece: "TY", name: "TY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-TZ", piece: "TZ", name: "TZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-UA", piece: "UA", name: "UA", edgesAlgorithm: "(M' , U2)", cornersAlgorithm: "(R F' R' U : (R D R' , U2))", learned: false },
  { id: "pair-UB", piece: "UB", name: "UB", edgesAlgorithm: "(L F' : (L' S' L , F2'))", cornersAlgorithm: "(R F' : (D , R' U' R))", learned: false },
  { id: "pair-UC", piece: "UC", name: "UC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-UD", piece: "UD", name: "UD", edgesAlgorithm: "(R' F : (R S R' , F2))", cornersAlgorithm: "(D' R : (U , R D' R'))", learned: false },
  { id: "pair-UE", piece: "UE", name: "UE", edgesAlgorithm: "(L' F' : (E' , L2))", cornersAlgorithm: "(U' R' U : (D , R U' R'))", learned: false },
  { id: "pair-UF", piece: "UF", name: "UF", edgesAlgorithm: "(U R' F' : (R S R' , F'))", cornersAlgorithm: "(D R U' R' : (U2 , R' D R))", learned: false },
  { id: "pair-UG", piece: "UG", name: "UG", edgesAlgorithm: "(L F' : (E' , L2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-UH", piece: "UH", name: "UH", edgesAlgorithm: "(l' U : (L2 , S'))", cornersAlgorithm: "(R D U' : (R' D' R , U2))", learned: false },
  { id: "pair-UI", piece: "UI", name: "UI", edgesAlgorithm: "", cornersAlgorithm: "(R : (F2 , R' U R U'))", learned: false },
  { id: "pair-UJ", piece: "UJ", name: "UJ", edgesAlgorithm: "(U R U' : (M' , U2))", cornersAlgorithm: "", learned: false },
  { id: "pair-UK", piece: "UK", name: "UK", edgesAlgorithm: "", cornersAlgorithm: "(U' R' : (U2 , R' D R))", learned: false },
  { id: "pair-UL", piece: "UL", name: "UL", edgesAlgorithm: "(U' D R : (E , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-UM", piece: "UM", name: "UM", edgesAlgorithm: "(R F : (E , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-UN", piece: "UN", name: "UN", edgesAlgorithm: "(r U' : (R2' , S))", cornersAlgorithm: "(U' R' : (U , R' D R))", learned: false },
  { id: "pair-UO", piece: "UO", name: "UO", edgesAlgorithm: "(R' F : (E , R2))", cornersAlgorithm: "(R D : (R' D' R , U))", learned: false },
  { id: "pair-UP", piece: "UP", name: "UP", edgesAlgorithm: "(U' L F : (L' S' L , F))", cornersAlgorithm: "(D' R U' : (D' , R' U R))", learned: false },
  { id: "pair-UQ", piece: "UQ", name: "UQ", edgesAlgorithm: "(U : (R' F' R , S)", cornersAlgorithm: "(U' R' : (U' , R' D R))", learned: false },
  { id: "pair-UR", piece: "UR", name: "UR", edgesAlgorithm: "(U' L U : (M' , U2'))", cornersAlgorithm: "(Lw D' U : (R D R' , U2))", learned: false },
  { id: "pair-US", piece: "US", name: "US", edgesAlgorithm: "(D' : (S' , R F R'))", cornersAlgorithm: "(D' R : (U' , R D' R'))", learned: false },
  { id: "pair-UT", piece: "UT", name: "UT", edgesAlgorithm: "(U R' U' : (M' , U2))", cornersAlgorithm: "(U' R' U R : (D , R U' R'))", learned: false },
  { id: "pair-UU", piece: "UU", name: "UU", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-UV", piece: "UV", name: "UV", edgesAlgorithm: "(R' F : (R S' R' , F2))", cornersAlgorithm: "(R U' D2 : (R' U R , D))", learned: false },
  { id: "pair-UW", piece: "UW", name: "UW", edgesAlgorithm: "u2 M' u2 M'", cornersAlgorithm: "", learned: false },
  { id: "pair-UX", piece: "UX", name: "UX", edgesAlgorithm: "(L F' : (L' S L , F2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-UY", piece: "UY", name: "UY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-UZ", piece: "UZ", name: "UZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-VA", piece: "VA", name: "VA", edgesAlgorithm: "(U : (S , R2'))", cornersAlgorithm: "(U2 , R' D R U' R D' R')", learned: false },
  { id: "pair-VB", piece: "VB", name: "VB", edgesAlgorithm: "(R U R' : (S , R2))", cornersAlgorithm: "(U , R' D R U' R D' R')", learned: false },
  { id: "pair-VC", piece: "VC", name: "VC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-VD", piece: "VD", name: "VD", edgesAlgorithm: "R' U' R U R U R U R U' R' U'", cornersAlgorithm: "(U' , R' D U' R D' R')", learned: false },
  { id: "pair-VE", piece: "VE", name: "VE", edgesAlgorithm: "(L2 : (S , L' F' L))", cornersAlgorithm: "(U R' D' : (R' D' R , U'))", learned: false },
  { id: "pair-VF", piece: "VF", name: "VF", edgesAlgorithm: "(U' E' R' : (E' , R2))", cornersAlgorithm: "(U' D' R' U : (D , R U' R'))", learned: false },
  { id: "pair-VG", piece: "VG", name: "VG", edgesAlgorithm: "(S , L' F' L)", cornersAlgorithm: "(U D R D' : (R' D R , U'))", learned: false },
  { id: "pair-VH", piece: "VH", name: "VH", edgesAlgorithm: "(u' R : (E , R2'))", cornersAlgorithm: "(R U' D R' : (U2 , R' D R))", learned: false },
  { id: "pair-VI", piece: "VI", name: "VI", edgesAlgorithm: "", cornersAlgorithm: "(R U' R' U D : (R D R' , U2))", learned: false },
  { id: "pair-VJ", piece: "VJ", name: "VJ", edgesAlgorithm: "U2 R U' R' U' R' U' R U R U'", cornersAlgorithm: "", learned: false },
  { id: "pair-VK", piece: "VK", name: "VK", edgesAlgorithm: "(U R' F' R : (S , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-VL", piece: "VL", name: "VL", edgesAlgorithm: "(U' R : (E , R2'))", cornersAlgorithm: "(R U' R' : (U2 , R' D R))", learned: false },
  { id: "pair-VM", piece: "VM", name: "VM", edgesAlgorithm: "(S' , R' F R)", cornersAlgorithm: "", learned: false },
  { id: "pair-VN", piece: "VN", name: "VN", edgesAlgorithm: "(u' R' : (E' , R2))", cornersAlgorithm: "(U' D' R' : (U2 , R' D R))", learned: false },
  { id: "pair-VO", piece: "VO", name: "VO", edgesAlgorithm: "", cornersAlgorithm: "(D' R : (F2 , R' U R U'))", learned: false },
  { id: "pair-VP", piece: "VP", name: "VP", edgesAlgorithm: "(U' E' R : (E , R2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-VQ", piece: "VQ", name: "VQ", edgesAlgorithm: "(r' : (U' R' U , M'))", cornersAlgorithm: "(U R' U' : (D' , R U R'))", learned: false },
  { id: "pair-VR", piece: "VR", name: "VR", edgesAlgorithm: "(U' R' : (E' , R2))", cornersAlgorithm: "(D' U' R' : (U' , R' D R))", learned: false },
  { id: "pair-VS", piece: "VS", name: "VS", edgesAlgorithm: "(U L B' L : (S , L2'))", cornersAlgorithm: "(U' D' R' : (U , R' D R))", learned: false },
  { id: "pair-VT", piece: "VT", name: "VT", edgesAlgorithm: "R' U R U R U R' U' R' U'", cornersAlgorithm: "(D' R D : (R' D' R , U))", learned: false },
  { id: "pair-VU", piece: "VU", name: "VU", edgesAlgorithm: "(R' F' : (R S' R' , F2))", cornersAlgorithm: "(U' R' U R : (R U' R' , D))", learned: false },
  { id: "pair-VV", piece: "VV", name: "VV", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-VW", piece: "VW", name: "VW", edgesAlgorithm: "(D' R' F : (R S' R' , F2))", cornersAlgorithm: "(D R U' R' : (R' U R , D'))", learned: false },
  { id: "pair-VX", piece: "VX", name: "VX", edgesAlgorithm: "(U' : (S' , R2'))", cornersAlgorithm: "(R U' R' U : (R D' R' , U2))", learned: false },
  { id: "pair-VY", piece: "VY", name: "VY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-VZ", piece: "VZ", name: "VZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-WA", piece: "WA", name: "WA", edgesAlgorithm: "(U2 , M)", cornersAlgorithm: "(R D' R' : (U2 , R' D R))", learned: false },
  { id: "pair-WB", piece: "WB", name: "WB", edgesAlgorithm: "(R : (U' R' U , M2'))", cornersAlgorithm: "(R D' R' U R' D R , U')", learned: false },
  { id: "pair-WC", piece: "WC", name: "WC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-WD", piece: "WD", name: "WD", edgesAlgorithm: "(l' M' : (U L U' , M2'))", cornersAlgorithm: "(R D' R' : (U' , R' D R))", learned: false },
  { id: "pair-WE", piece: "WE", name: "WE", edgesAlgorithm: "(l' : (U' L U , M2'))", cornersAlgorithm: "(D R : (U , R D' R'))", learned: false },
  { id: "pair-WF", piece: "WF", name: "WF", edgesAlgorithm: "(M' : (U' L' U , M2'))", cornersAlgorithm: "(R U' R2' : (U , R D R'))", learned: false },
  { id: "pair-WG", piece: "WG", name: "WG", edgesAlgorithm: "(U : (L B' L' , S'))", cornersAlgorithm: "(U R2 : (U' , R' D R))", learned: false },
  { id: "pair-WH", piece: "WH", name: "WH", edgesAlgorithm: "(M' : (U' L U , M2'))", cornersAlgorithm: "(R D' R' : (U , R' D R))", learned: false },
  { id: "pair-WI", piece: "WI", name: "WI", edgesAlgorithm: "", cornersAlgorithm: "(D R : (U2 , R D' R'))", learned: false },
  { id: "pair-WJ", piece: "WJ", name: "WJ", edgesAlgorithm: "(U' R U , M2')", cornersAlgorithm: "", learned: false },
  { id: "pair-WK", piece: "WK", name: "WK", edgesAlgorithm: "(D : (S' , R F R'))", cornersAlgorithm: "(U R D' : (R' D R , U'))", learned: false },
  { id: "pair-WL", piece: "WL", name: "WL", edgesAlgorithm: "(U L' U' , M2'))", cornersAlgorithm: "(D' R2 : (R' U' R , D'))", learned: false },
  { id: "pair-WM", piece: "WM", name: "WM", edgesAlgorithm: "(r : (U R' U' , M2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-WN", piece: "WN", name: "WN", edgesAlgorithm: "(M' : (U R' U' , M2'))", cornersAlgorithm: "(U R U D' : (R' D R , U2))", learned: false },
  { id: "pair-WO", piece: "WO", name: "WO", edgesAlgorithm: "(U' : (R' B R , S))", cornersAlgorithm: "", learned: false },
  { id: "pair-WP", piece: "WP", name: "WP", edgesAlgorithm: "(M' : (U R U' , M2'))", cornersAlgorithm: "(D R U' : (D' , R' U R))", learned: false },
  { id: "pair-WQ", piece: "WQ", name: "WQ", edgesAlgorithm: "(U : (R B R' , S))", cornersAlgorithm: "(U R2 : (U' , R' D' R))", learned: false },
  { id: "pair-WR", piece: "WR", name: "WR", edgesAlgorithm: "(U L U' , M2')", cornersAlgorithm: "(U R2 : (U' , R' D2 R))", learned: false },
  { id: "pair-WS", piece: "WS", name: "WS", edgesAlgorithm: "", cornersAlgorithm: "(U' R2' : (D , R2 U R2' U' R2))", learned: false },
  { id: "pair-WT", piece: "WT", name: "WT", edgesAlgorithm: "(U' R' U , M2')", cornersAlgorithm: "", learned: false },
  { id: "pair-WU", piece: "WU", name: "WU", edgesAlgorithm: "M' U2 M' U2 M2'", cornersAlgorithm: "(D R U' R' : (D' , R' U R))", learned: false },
  { id: "pair-WV", piece: "WV", name: "WV", edgesAlgorithm: "(D' R' F' : (R S' R' , F2))", cornersAlgorithm: "(R U' R' : (R' U R , D'))", learned: false },
  { id: "pair-WW", piece: "WW", name: "WW", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-WX", piece: "WX", name: "WX", edgesAlgorithm: "(D L F : (L' S L , F2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-WY", piece: "WY", name: "WY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-WZ", piece: "WZ", name: "WZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-XA", piece: "XA", name: "XA", edgesAlgorithm: "(U' : (S' , L2))", cornersAlgorithm: "(R' U' D' R : (D , R U' R'))", learned: false },
  { id: "pair-XB", piece: "XB", name: "XB", edgesAlgorithm: "L U L' U' L' U' L' U L U", cornersAlgorithm: "(R' B : (R U R' , D'))", learned: false },
  { id: "pair-XC", piece: "XC", name: "XC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-XD", piece: "XD", name: "XD", edgesAlgorithm: "(L' U' L : (S' , L2))", cornersAlgorithm: "(R' D' R : (D , R U' R'))", learned: false },
  { id: "pair-XE", piece: "XE", name: "XE", edgesAlgorithm: "(S , L F' L')", cornersAlgorithm: "(R : (U , R D' R'))", learned: false },
  { id: "pair-XF", piece: "XF", name: "XF", edgesAlgorithm: "(U E L' : (E' , L2))", cornersAlgorithm: "(U' D R' U : (D , R U' R'))", learned: false },
  { id: "pair-XG", piece: "XG", name: "XG", edgesAlgorithm: "", cornersAlgorithm: "(D R : (F2 , R' U R U'))", learned: false },
  { id: "pair-XH", piece: "XH", name: "XH", edgesAlgorithm: "(u L : (E , L2'))", cornersAlgorithm: "", learned: false },
  { id: "pair-XI", piece: "XI", name: "XI", edgesAlgorithm: "", cornersAlgorithm: "(R2 U : (R' U R , D'))", learned: false },
  { id: "pair-XJ", piece: "XJ", name: "XJ", edgesAlgorithm: "(U L' : (E' , L2))", cornersAlgorithm: "", learned: false },
  { id: "pair-XK", piece: "XK", name: "XK", edgesAlgorithm: "(U' L F L' : (S' , L2))", cornersAlgorithm: "(R' D' R : (D ,R U R'))", learned: false },
  { id: "pair-XL", piece: "XL", name: "XL", edgesAlgorithm: "U2' L' U L U L U L' U' L' U", cornersAlgorithm: "(D R D : (R' D' R , U))", learned: false },
  { id: "pair-XM", piece: "XM", name: "XM", edgesAlgorithm: "(R2' : (S' , R F R'))", cornersAlgorithm: "", learned: false },
  { id: "pair-XN", piece: "XN", name: "XN", edgesAlgorithm: "(u L' : (E' , L2))", cornersAlgorithm: "(D U' R' : (U2 , R' D R))", learned: false },
  { id: "pair-XO", piece: "XO", name: "XO", edgesAlgorithm: "(S' , R F R')", cornersAlgorithm: "(U D' R D' : (R' D R , U'))", learned: false },
  { id: "pair-XP", piece: "XP", name: "XP", edgesAlgorithm: "(U E L : (E , L2'))", cornersAlgorithm: "(R2 : (R' U' R , D'))", learned: false },
  { id: "pair-XQ", piece: "XQ", name: "XQ", edgesAlgorithm: "(l : (U L U' , M'))", cornersAlgorithm: "(R U' : (D' , R' U R))", learned: false },
  { id: "pair-XR", piece: "XR", name: "XR", edgesAlgorithm: "L U' L' U' L' U' L U L U", cornersAlgorithm: "(R2 U : (R' U' R , D'))", learned: false },
  { id: "pair-XS", piece: "XS", name: "XS", edgesAlgorithm: "(U' R' B R' : (S' , R2))", cornersAlgorithm: "", learned: false },
  { id: "pair-XT", piece: "XT", name: "XT", edgesAlgorithm: "(U L : (E , L2'))", cornersAlgorithm: "(R U' D' : (R' U R , D2))", learned: false },
  { id: "pair-XU", piece: "XU", name: "XU", edgesAlgorithm: "(L F : (L' S L , F2'))", cornersAlgorithm: "(R U' D' : (R' U R , D'))", learned: false },
  { id: "pair-XV", piece: "XV", name: "XV", edgesAlgorithm: "(U' : (R2' , S'))", cornersAlgorithm: "(R U' R' U' : (R D' R' , U2))", learned: false },
  { id: "pair-XW", piece: "XW", name: "XW", edgesAlgorithm: "(D L F' : (L' S L , F2'))", cornersAlgorithm: "(R U' R' : (D' , R' U R))", learned: false },
  { id: "pair-XX", piece: "XX", name: "XX", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-XY", piece: "XY", name: "XY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-XZ", piece: "XZ", name: "XZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YA", piece: "YA", name: "YA", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YB", piece: "YB", name: "YB", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YC", piece: "YC", name: "YC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YD", piece: "YD", name: "YD", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YE", piece: "YE", name: "YE", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YF", piece: "YF", name: "YF", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YG", piece: "YG", name: "YG", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YH", piece: "YH", name: "YH", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YI", piece: "YI", name: "YI", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YJ", piece: "YJ", name: "YJ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YK", piece: "YK", name: "YK", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YL", piece: "YL", name: "YL", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YM", piece: "YM", name: "YM", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YN", piece: "YN", name: "YN", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YO", piece: "YO", name: "YO", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YP", piece: "YP", name: "YP", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YQ", piece: "YQ", name: "YQ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YR", piece: "YR", name: "YR", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YS", piece: "YS", name: "YS", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YT", piece: "YT", name: "YT", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YU", piece: "YU", name: "YU", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YV", piece: "YV", name: "YV", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YW", piece: "YW", name: "YW", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YX", piece: "YX", name: "YX", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YY", piece: "YY", name: "YY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-YZ", piece: "YZ", name: "YZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZA", piece: "ZA", name: "ZA", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZB", piece: "ZB", name: "ZB", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZC", piece: "ZC", name: "ZC", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZD", piece: "ZD", name: "ZD", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZE", piece: "ZE", name: "ZE", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZF", piece: "ZF", name: "ZF", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZG", piece: "ZG", name: "ZG", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZH", piece: "ZH", name: "ZH", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZI", piece: "ZI", name: "ZI", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZJ", piece: "ZJ", name: "ZJ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZK", piece: "ZK", name: "ZK", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZL", piece: "ZL", name: "ZL", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZM", piece: "ZM", name: "ZM", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZN", piece: "ZN", name: "ZN", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZO", piece: "ZO", name: "ZO", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZP", piece: "ZP", name: "ZP", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZQ", piece: "ZQ", name: "ZQ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZR", piece: "ZR", name: "ZR", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZS", piece: "ZS", name: "ZS", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZT", piece: "ZT", name: "ZT", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZU", piece: "ZU", name: "ZU", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZV", piece: "ZV", name: "ZV", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZW", piece: "ZW", name: "ZW", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZX", piece: "ZX", name: "ZX", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZY", piece: "ZY", name: "ZY", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
  { id: "pair-ZZ", piece: "ZZ", name: "ZZ", edgesAlgorithm: "", cornersAlgorithm: "", learned: false },
]

export const defaultBldFlips: BldFlipCase[] = [
  { id: "flip-UB", piece: "UB", name: "UB flip", algorithm: "M' U2 M U R' F' R S R' F R S' U", learned: false },
  { id: "flip-UR", piece: "UR", name: "UR flip", algorithm: "R' E2 R2 E' R' U' R E R2' E2 R U", learned: false },
  { id: "flip-UL", piece: "UL", name: "UL flip", algorithm: "L F' L' U M' U2 M U S' L F L' S", learned: false },
  { id: "flip-LF", piece: "LF", name: "LF flip", algorithm: "F' L' U M' U2 M U S' L F L' S L", learned: false },
  { id: "flip-LD", piece: "LD", name: "LD flip", algorithm: "S L F' L' U M' U2 M U S' L F L'", learned: false },
  { id: "flip-LB", piece: "LB", name: "LB flip", algorithm: "L' S L F' L' U M' U2 M U S' L F", learned: false },
  { id: "flip-FR", piece: "FR", name: "FR flip", algorithm: "F R U' M' U2 M U' S R' F' R S' R'", learned: false },
  { id: "flip-FD", piece: "FD", name: "FD flip", algorithm: "U2 M' U2 M U' S R' F' R S' R' F R U", learned: false },
  { id: "flip-RB", piece: "RB", name: "RB flip", algorithm: "R S' R' F R U' M' U2 M U' S R' F'", learned: false },
  { id: "flip-RD", piece: "RD", name: "RD flip", algorithm: "S' R' F R U' M' U2 M U' S R' F' R", learned: false },
  { id: "flip-BD", piece: "BD", name: "BD flip", algorithm: "U2 M U' S R' F' R S' R' F R U' M'", learned: false },
]

export const defaultBldTwists: BldTwistCase[] = [
  { id: "twist-UBL", piece: "UBL", name: "UBL twist", algorithm1: "(R : (U, R D R' D' R D R'))", algorithm2: "(R : (R D R' D' R D R', U))", learned: false },
  { id: "twist-UBR", piece: "UBR", name: "UBR twist", algorithm1: "(R D R' D' R D R', U')", algorithm2: "(U', R D R' D' R D R')", learned: false },
  { id: "twist-UFL", piece: "UFL", name: "UFL twist", algorithm1: "(U', R' D R D' R' D R)", algorithm2: "(R' D R D' R' D R, U')", learned: false },
  { id: "twist-DFL", piece: "DFL", name: "DFL twist", algorithm1: "(R U R': (R U' R' U R U' R', D))", algorithm2: "(R U R': (D, R U' R' U R U' R'))", learned: false },
  { id: "twist-DFR", piece: "DFR", name: "DFR twist", algorithm1: "(D' : (U', R' D R)) (R' D' R, U')", algorithm2: "(R': (D', R U' R' U R U' R'))", learned: false },
  { id: "twist-DBR", piece: "DBR", name: "DBR twist", algorithm1: "(R U R': (R U' R' U R U' R', D'))", algorithm2: "(R U R': (D', R U' R' U R U' R'))", learned: false },
  { id: "twist-DBL", piece: "DBL", name: "DBL twist", algorithm1: "(U' R: (D', R' U R U' R' U R))", algorithm2: "(U' R:(R' U R U' R' U R, D'))", learned: false },
]
