export type LearningState = "not-learned" | "learning" | "learned";
export interface MethodCase { id: string; title: string; algorithm: string; algorithms?: string[]; image?: string; learningState?: LearningState; }

export const ThreeXThreeF2LCases = [
  { id: "f2l-1", title: "F2L Case 1", algorithm: "U R U' R'", image: "/images/3x3/F2L/f2l1.png" },
  { id: "f2l-2", title: "F2L Case 2", algorithm: "F R' F' R", image: "/images/3x3/F2L/f2l2.png" },
  { id: "f2l-3", title: "F2L Case 3", algorithm: "F' U' F", image: "/images/3x3/F2L/f2l3.png" },
  { id: "f2l-4", title: "F2L Case 4", algorithm: "R U R'", image: "/images/3x3/F2L/f2l4.png" },
  { id: "f2l-5", title: "F2L Case 5", algorithm: "U' R U R' U2 R U' R'", image: "/images/3x3/F2L/f2l5.png" },
  { id: "f2l-6", title: "F2L Case 6", algorithm: "U' Rw U' R' U R U Rw'", image: "/images/3x3/F2L/f2l6.png" },
  { id: "f2l-7", title: "F2L Case 7", algorithm: "U' R U2' R' U2 R U' R'", image: "/images/3x3/F2L/f2l7.png" },
  { id: "f2l-8", title: "F2L Case 8", algorithm: "Dw R' U2' R U R' U2' R", image: "/images/3x3/F2L/f2l8.png" },
  { id: "f2l-9", title: "F2L Case 9", algorithm: "U' R U' R' U F' U' F", image: "/images/3x3/F2L/f2l9.png" },
  { id: "f2l-10", title: "F2L Case 10", algorithm: "U' R U R' U R U R'", image: "/images/3x3/F2L/f2l10.png" },
  { id: "f2l-11", title: "F2L Case 11", algorithm: "U' R U2' R' U F' U' F", image: "/images/3x3/F2L/f2l11.png" },
  { id: "f2l-12", title: "F2L Case 12", algorithm: "R' U2' R2 U R2' U R", image: "/images/3x3/F2L/f2l12.png" },
  { id: "f2l-13", title: "F2L Case 13", algorithm: "R U' R' U R' F R F' R U' R'", image: "/images/3x3/F2L/f2l13.png" },
  { id: "f2l-14", title: "F2L Case 14", algorithm: "U' R U' R' U R U R'", image: "/images/3x3/F2L/f2l14.png" },
  { id: "f2l-15", title: "F2L Case 15", algorithm: "R' D' R U' R' D R U R U' R'", image: "/images/3x3/F2L/f2l15.png" },
  { id: "f2l-16", title: "F2L Case 16", algorithm: "R U' R' U2 F' U' F", image: "/images/3x3/F2L/f2l16.png" },
  { id: "f2l-17", title: "F2L Case 17", algorithm: "R U2' R' U' R U R'", image: "/images/3x3/F2L/f2l17.png" },
  { id: "f2l-18", title: "F2L Case 18", algorithm: "R' F R F' R U' R' U R U' R'", image: "/images/3x3/F2L/f2l18.png" },
  { id: "f2l-19", title: "F2L Case 19", algorithm: "U R U2' R' U R U' R'", image: "/images/3x3/F2L/f2l19.png" },
  { id: "f2l-20", title: "F2L Case 20", algorithm: "U' R U' R2' F R F' R U' R'", image: "/images/3x3/F2L/f2l20.png" },
  { id: "f2l-21", title: "F2L Case 21", algorithm: "U2' R U R' U R U' R'", image: "/images/3x3/F2L/f2l21.png" },
  { id: "f2l-22", title: "F2L Case 22", algorithm: "Rw U' Rw' U2 Rw U Rw'", image: "/images/3x3/F2L/f2l22.png" },
  { id: "f2l-23", title: "F2L Case 23", algorithm: "U R U' R' U' R U' R' U R U' R'", image: "/images/3x3/F2L/f2l23.png",},
  { id: "f2l-24", title: "F2L Case 24", algorithm: "F U R U' R' F' R U' R'", image: "/images/3x3/F2L/f2l24.png" },
  { id: "f2l-25", title: "F2L Case 25", algorithm: "U' R' F R F' R U R'", image: "/images/3x3/F2L/f2l25.png" },
  { id: "f2l-26", title: "F2L Case 26", algorithm: "U R U' R' F R' F' R", image: "/images/3x3/F2L/f2l26.png" },
  { id: "f2l-27", title: "F2L Case 27", algorithm: "R U' R' U R U' R'", image: "/images/3x3/F2L/f2l27.png" },
  { id: "f2l-28", title: "F2L Case 28", algorithm: "R U R' U2' F' U F", image: "/images/3x3/F2L/f2l28.png" },
  { id: "f2l-29", title: "F2L Case 29", algorithm: "M' U R U' R' U R U' Rw'", image: "/images/3x3/F2L/f2l29.png" },
  { id: "f2l-30", title: "F2L Case 30", algorithm: "R U R' U' R U R'", image: "/images/3x3/F2L/f2l30.png" },
  { id: "f2l-31", title: "F2L Case 31", algorithm: "U' R' F R F' R U' R'", image: "/images/3x3/F2L/f2l31.png" },
  { id: "f2l-32", title: "F2L Case 32", algorithm: "U R U' R' U R U' R' U R U' R'", image: "/images/3x3/F2L/f2l32.png",},
  { id: "f2l-33", title: "F2L Case 33", algorithm: "U' R U' R' U2 R U' R'", image: "/images/3x3/F2L/f2l33.png" },
  { id: "f2l-34", title: "F2L Case 34", algorithm: "U R U R' U2 R U R'", image: "/images/3x3/F2L/f2l34.png" },
  { id: "f2l-35", title: "F2L Case 35", algorithm: "U M' U R U' Rw' R U' R'", image: "/images/3x3/F2L/f2l35.png" },
  { id: "f2l-36", title: "F2L Case 36", algorithm: "U2 R' F R F' U2 R U R'", image: "/images/3x3/F2L/f2l36.png" },
  { id: "f2l-37", title: "F2L Case 37", algorithm: "R2' U2' F R2 F' U2' R' U R'", image: "/images/3x3/F2L/f2l37.png" },
  { id: "f2l-38", title: "F2L Case 38", algorithm: "R U' R' U' R U R' U2 R U' R'", image: "/images/3x3/F2L/f2l38.png",},
  { id: "f2l-39", title: "F2L Case 39", algorithm: "R U' R' U R U2' R' U R U' R'", image: "/images/3x3/F2L/f2l39.png",},
  { id: "f2l-40", title: "F2L Case 40", algorithm: "F' L' U2 L F R U R'", image: "/images/3x3/F2L/f2l40.png" },
  { id: "f2l-41", title: "F2L Case 41", algorithm: "R U' R' F' L' U2 L F", image: "/images/3x3/F2L/f2l41.png" },
]


export const ThreeXThreeOLLCases = [
  { id: "oll-1", title: "OLL 1", algorithm: "R U2 R2' F R F' U2 R' F R F'", image: "/images/3x3/oll/oll-1.png" },
  { id: "oll-2", title: "OLL 2", algorithm: "F R U R' U' F' f R U R' U' f'", image: "/images/3x3/oll/oll-2.png" },
  { id: "oll-3", title: "OLL 3", algorithm: "f R U R' U' f' U' F R U R' U' F'", image: "/images/3x3/oll/oll-3.png" },
  { id: "oll-4", title: "OLL 4", algorithm: "f R U R' U' f' U F R U R' U' F'", image: "/images/3x3/oll/oll-4.png" },
  { id: "oll-5", title: "OLL 5", algorithm: "Rw' U2 R U R' U Rw", image: "/images/3x3/oll/oll-5.png" },
  { id: "oll-6", title: "OLL 6", algorithm: "Rw U2 R' U' R U' Rw'", image: "/images/3x3/oll/oll-6.png" },
  { id: "oll-7", title: "OLL 7", algorithm: "Rw U R' U R U2 Rw'", image: "/images/3x3/oll/oll-7.png" },
  { id: "oll-8", title: "OLL 8", algorithm: "Rw' U' R U' R' U2 Rw", image: "/images/3x3/oll/oll-8.png" },
  { id: "oll-9", title: "OLL 9", algorithm: "R U R' U' R' F R R2 U R' U' F'", image: "/images/3x3/oll/oll-9.png" },
  { id: "oll-10", title: "OLL 10", algorithm: "R U R' U R' F R F' R U2 R'", image: "/images/3x3/oll/oll-10.png" },
  { id: "oll-11", title: "OLL 11", algorithm: "Rw U R' U R' F R F' R U2 Rw'", image: "/images/3x3/oll/oll-11.png" },
  { id: "oll-12", title: "OLL 12", algorithm: "M' R' U' R U' R' U2 R U' M", image: "/images/3x3/oll/oll-12.png" },
  { id: "oll-13", title: "OLL 13", algorithm: "F U R U' R2 F' R U R U' R'", image: "/images/3x3/oll/oll-13.png" },
  { id: "oll-14", title: "OLL 14", algorithm: "R' F R U R' F' R Fw U' Rw'", image: "/images/3x3/oll/oll-14.png" },
  { id: "oll-15", title: "OLL 15", algorithm: "Rw' U' Rw R' U' R U Rw' U Rw", image: "/images/3x3/oll/oll-15.png" },
  { id: "oll-16", title: "OLL 16", algorithm: "Rw U Rw' R U R' U' Rw U' Rw'", image: "/images/3x3/oll/oll-16.png" },
  { id: "oll-17", title: "OLL 17", algorithm: "R U R' U R' F R F' U2 R' F R F'", image: "/images/3x3/oll/oll-17.png" },
  { id: "oll-18", title: "OLL 18", algorithm: "Rw U R' U' Rw' R U R U' R' U2 Rw", image: "/images/3x3/oll/oll-18.png" },
  { id: "oll-19", title: "OLL 19", algorithm: "M U R U R' U' M' R' F R F'", image: "/images/3x3/oll/oll-19.png" },
  { id: "oll-20", title: "OLL 20", algorithm: "M U R U R' U' M2' U R U' Rw'", image: "/images/3x3/oll/oll-20.png" },
  { id: "oll-21", title: "OLL 21", algorithm: "R U2 R' U' R U R' U' R U' R'", image: "/images/3x3/oll/oll-21.png" },
  { id: "oll-22", title: "OLL 22", algorithm: "R U2 R2' U' R2 U' R2' U2 R", image: "/images/3x3/oll/oll-22.png" },
  { id: "oll-23", title: "OLL 23", algorithm: "R2 D' R U2 R' D R U2 R", image: "/images/3x3/oll/oll-23.png" },
  { id: "oll-24", title: "OLL 24", algorithm: "Rw U R' U' Rw' F R F'", image: "/images/3x3/oll/oll-24.png" },
  { id: "oll-25", title: "OLL 25", algorithm: "F' Rw U R' U' Rw' F R", image: "/images/3x3/oll/oll-25.png" },
  { id: "oll-26", title: "OLL 26", algorithm: "R U2 R' U' R U' R'", image: "/images/3x3/oll/oll-26.png" },
  { id: "oll-27", title: "OLL 27", algorithm: "R U R' U R U2 R'", image: "/images/3x3/oll/oll-27.png" },
  { id: "oll-28", title: "OLL 28", algorithm: "Rw U R' U' Rw' R U R U' R'", image: "/images/3x3/oll/oll-28.png" },
  { id: "oll-29", title: "OLL 29", algorithm: "M U R U R' U' M' R' F R F'", image: "/images/3x3/oll/oll-29.png" },
  { id: "oll-30", title: "OLL 30", algorithm: "F U R U2 R' U' R U R' F'", image: "/images/3x3/oll/oll-30.png" },
  { id: "oll-31", title: "OLL 31", algorithm: "R' U' F U R U' R' F' R", image: "/images/3x3/oll/oll-31.png" },
  { id: "oll-32", title: "OLL 32", algorithm: "S R U R' U' R' F R f'", image: "/images/3x3/oll/oll-32.png" },
  { id: "oll-33", title: "OLL 33", algorithm: "R U R' U' R' F R F'", image: "/images/3x3/oll/oll-33.png" },
  { id: "oll-34", title: "OLL 34", algorithm: "R U R2' U' R' F R U R U' F'", image: "/images/3x3/oll/oll-34.png" },
  { id: "oll-35", title: "OLL 35", algorithm: "R U2 R2' F R F' R U2 R'", image: "/images/3x3/oll/oll-35.png" },
  { id: "oll-36", title: "OLL 36", algorithm: "R' U' R U' R' U R U Rw B' Rw'", image: "/images/3x3/oll/oll-36.png" },
  { id: "oll-37", title: "OLL 37", algorithm: "F R U' R' U' R U R' F'", image: "/images/3x3/oll/oll-37.png" },
  { id: "oll-38", title: "OLL 38", algorithm: "R U R' U R U' R' U' R' F R F'", image: "/images/3x3/oll/oll-38.png" },
  { id: "oll-39", title: "OLL 39", algorithm: "R U R' F' U' F U R U2 R'", image: "/images/3x3/oll/oll-39.png" },
  { id: "oll-40", title: "OLL 40", algorithm: "R' F R U R' U' F' U R", image: "/images/3x3/oll/oll-40.png" },
  { id: "oll-41", title: "OLL 41", algorithm: "R U R' U R U2 R' F R U R' U' F'", image: "/images/3x3/oll/oll-41.png" },
  { id: "oll-42", title: "OLL 42", algorithm: "R' U' R U' R' U2 R F R U R' U' F'", image: "/images/3x3/oll/oll-42.png",},
  { id: "oll-43", title: "OLL 43", algorithm: "F' U' L' U L F", image: "/images/3x3/oll/oll-43.png" },
  { id: "oll-44", title: "OLL 44", algorithm: "F U R U' R' F'", image: "/images/3x3/oll/oll-44.png" },
  { id: "oll-45", title: "OLL 45", algorithm: "F R U R' U' F'", image: "/images/3x3/oll/oll-45.png" },
  { id: "oll-46", title: "OLL 46", algorithm: "R' U' R' F R F' U R", image: "/images/3x3/oll/oll-46.png" },
  { id: "oll-47", title: "OLL 47", algorithm: "R' U' R' F R F' R' F R F' U R", image: "/images/3x3/oll/oll-47.png" },
  { id: "oll-48", title: "OLL 48", algorithm: "F R U R' U' R U R' U' F'", image: "/images/3x3/oll/oll-48.png" },
  { id: "oll-49", title: "OLL 49", algorithm: "R B' R2 F R2 B R2 F' R", image: "/images/3x3/oll/oll-49.png" },
  { id: "oll-50", title: "OLL 50", algorithm: "R' F R2 B' R2 F' R2 B R'", image: "/images/3x3/oll/oll-50.png" },
  { id: "oll-51", title: "OLL 51", algorithm: "F U R U' R' U R U' R' F'", image: "/images/3x3/oll/oll-51.png" },
  { id: "oll-52", title: "OLL 52", algorithm: "R' U' R U' R' U F' U F R", image: "/images/3x3/oll/oll-52.png" },
  { id: "oll-53", title: "OLL 53", algorithm: "Rw' U2 R U R' U' R U R' U Rw", image: "/images/3x3/oll/oll-53.png" },
  { id: "oll-54", title: "OLL 54", algorithm: "Rw U2 R' U' R U R' U' R U' Rw'", image: "/images/3x3/oll/oll-54.png" },
  { id: "oll-55", title: "OLL 55", algorithm: "R' F R U R U' R2 F' R2 U' R' U R U R'", image: "/images/3x3/oll/oll-55.png",},
  { id: "oll-56", title: "OLL 56", algorithm: "Rw U Rw' U R U' R' U R U' R' Rw U' Rw'", image: "/images/3x3/oll/oll-56.png",},
  { id: "oll-57", title: "OLL 57", algorithm: "R U R' U' M' U R U' Rw'", image: "/images/3x3/oll/oll-57.png" },
]


export const ThreeXThreePLLCases = [
  { id: "pll-1", title: "Aa", algorithm: "x L2 D2' L' U' L D2' L' U L' x'", image: "/images/3x3/pll/pll-1.png" },
  { id: "pll-2", title: "Ab", algorithm: "x L U' L D2' L' U L D2' L2", image: "/images/3x3/pll/pll-2.png" },
  { id: "pll-3", title: "E", algorithm: "x' R U' R' D R U R' D' R U R' D R U' R' D' x", image: "/images/3x3/pll/pll-3.png",},
  { id: "pll-4", title: "F", algorithm: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R", image: "/images/3x3/pll/pll-4.png",},
  { id: "pll-5", title: "Ga", algorithm: "R2 U R' U R' U' R U' R2 D U' R' U R D'", image: "/images/3x3/pll/pll-5.png" },
  { id: "pll-6", title: "Gb", algorithm: "R' U' R U D' R2 U R' U R U' R U' R2 D", image: "/images/3x3/pll/pll-6.png" },
  { id: "pll-7", title: "Gc", algorithm: "R2' Uw' R U' R U R' Uw R2 Fw R' Fw'", image: "/images/3x3/pll/pll-7.png" },
  { id: "pll-8", title: "Gd", algorithm: "R U R' U' D R2 U' R U' R' U R' U R2 D'", image: "/images/3x3/pll/pll-8.png" },
  { id: "pll-9", title: "H", algorithm: "M2' U M2' U2 M2' U M2'", image: "/images/3x3/pll/pll-9.png" },
  { id: "pll-10", title: "Ja", algorithm: "x R2' F R F' R U2' Rw' U Rw U2' x'", image: "/images/3x3/pll/pll-10.png" },
  { id: "pll-11", title: "Jb", algorithm: "R U R' F' R U R' U' R' F R2 U' R'", image: "/images/3x3/pll/pll-11.png" },
  { id: "pll-12", title: "Na", algorithm: "z U R' D R2 U' R U D' R' D R2 U' R D' z'", image: "/images/3x3/pll/pll-12.png",},
  { id: "pll-13", title: "Nb", algorithm: "z U' R D' R2 U R' U' D R D' R2 U R' D z'", image: "/images/3x3/pll/pll-13.png",},
  { id: "pll-14", title: "Ra", algorithm: "L U2 L' U2' L F' L' U' L U L F L2'", image: "/images/3x3/pll/pll-14.png" },
  { id: "pll-15", title: "Rb", algorithm: "R' U2 R U2' R' F R U R' U' R' F' R2", image: "/images/3x3/pll/pll-15.png" },
  { id: "pll-16", title: "T", algorithm: "R U R' U' R' F R2 U' R' U' R U R' F'", image: "/images/3x3/pll/pll-16.png" },
  { id: "pll-17", title: "Ua", algorithm: "M2 U M' U2 M U M2", image: "/images/3x3/pll/pll-17.png" },
  { id: "pll-18", title: "Ub", algorithm: "M2 U' M' U2 M U' M2", image: "/images/3x3/pll/pll-18.png" },
  { id: "pll-19", title: "V", algorithm: "R' U R' U' R D' R' D R' U D' R2 U' R2' D R2", image: "/images/3x3/pll/pll-19.png",},
  { id: "pll-20", title: "Y", algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F'", image: "/images/3x3/pll/pll-20.png",},
  { id: "pll-21", title: "Z", algorithm: "M2 U M2 U M' U2 M2 U2 M'", image: "/images/3x3/pll/pll-21.png" },
]


export const FourXFourF2LCases = [
  { id: "4x4-f2l-1", title: "4x4 Edge Pairing", algorithm: "Uw R U' R' F R F' Uw'" },
  { id: "4x4-f2l-2", title: "Center Building", algorithm: "r U r' F r F' r'" },
  { id: "4x4-f2l-3", title: "3x3 Stage F2L", algorithm: "R U' R' U R U R'" },
]


export const FourXFourOLLCases = [
  { id: "4x4-oll-1", title: "OLL Parity 1", algorithm: "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'", image: "/images/4x4/oll-parity/ollp1.png" },
  { id: "4x4-oll-2", title: "OLL Parity 2", algorithm: "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'", image: "/images/4x4/oll-parity/ollp2.png" },
  { id: "4x4-oll-3", title: "OLL Parity 3", algorithm: "Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw'", image: "/images/4x4/oll-parity/ollp3.png" },
]


export const FourXFourPLLCases = [
  { id: "4x4-pll-1", title: "PLL Parity 1", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp1.png" },
  { id: "4x4-pll-2", title: "PLL Parity 2", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp2.png" },
  { id: "4x4-pll-3", title: "PLL Parity 3", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp3.png" },
  { id: "4x4-pll-4", title: "PLL Parity 4", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp4.png" },
  { id: "4x4-pll-5", title: "PLL Parity 5", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp5.png" },
  { id: "4x4-pll-6", title: "PLL Parity 6", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp6.png" },
  { id: "4x4-pll-7", title: "PLL Parity 7", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp7.png" },
  { id: "4x4-pll-8", title: "PLL Parity 8", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp8.png" },
  { id: "4x4-pll-9", title: "PLL Parity 9", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp9.png" },
  { id: "4x4-pll-10", title: "PLL Parity 10", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp10.png" },
  { id: "4x4-pll-11", title: "PLL Parity 11", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp11.png" },
  { id: "4x4-pll-12", title: "PLL Parity 12", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp12.png" },
  { id: "4x4-pll-13", title: "PLL Parity 13", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp13.png" },
  { id: "4x4-pll-14", title: "PLL Parity 14", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp14.png" },
  { id: "4x4-pll-15", title: "PLL Parity 15", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp15.png" },
  { id: "4x4-pll-16", title: "PLL Parity 16", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp16.png" },
  { id: "4x4-pll-17", title: "PLL Parity 17", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp17.png" },
  { id: "4x4-pll-18", title: "PLL Parity 18", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp18.png" },
  { id: "4x4-pll-19", title: "PLL Parity 19", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp19.png" },
  { id: "4x4-pll-20", title: "PLL Parity 20", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp20.png" },
  { id: "4x4-pll-21", title: "PLL Parity 21", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp21.png" },
  { id: "4x4-pll-22", title: "PLL Parity 22", algorithm: "Rw2 B2 U2 Lw U2 Rw' U2 Rw U2 F2 Rw F2 Lw' B2 Rw2", image: "/images/4x4/pll-parity/pllp22.png" }
]

