export type LearningState = "not-learned" | "learning" | "learned";
export interface MethodOrientation {
  id: string
  title: string
  algorithm: string
  image?: string
}

export interface MethodCase {
  id: string
  title: string
  algorithm: string
  algorithms?: string[]
  orientations?: MethodOrientation[]
  image?: string
  learningState?: LearningState
}

// Every orientation is represented explicitly so algorithms can be filled in independently.

export const F2L1: MethodOrientation[] = [
  { id: "f2l-1-1", title: "F2L Case 1", algorithm: "U R U' R'", image: "/images/3x3/F2L/f2l11.png" },
  { id: "f2l-2-1", title: "F2L Case 2", algorithm: "F R' F' R", image: "/images/3x3/F2L/f2l21.png" },
  { id: "f2l-3-1", title: "F2L Case 3", algorithm: "F' U' F", image: "/images/3x3/F2L/f2l31.png" },
  { id: "f2l-4-1", title: "F2L Case 4", algorithm: "R U R'", image: "/images/3x3/F2L/f2l41.png" },
  { id: "f2l-5-1", title: "F2L Case 5", algorithm: "U' R U R' U2 R U' R'", image: "/images/3x3/F2L/f2l51.png" },
  { id: "f2l-6-1", title: "F2L Case 6", algorithm: "U' Rw U' R' U R U Rw'", image: "/images/3x3/F2L/f2l61.png" },
  { id: "f2l-7-1", title: "F2L Case 7", algorithm: "U' R U2' R' U2 R U' R'", image: "/images/3x3/F2L/f2l71.png" },
  { id: "f2l-8-1", title: "F2L Case 8", algorithm: "Dw R' U2' R U R' U2' R", image: "/images/3x3/F2L/f2l81.png" },
  { id: "f2l-9-1", title: "F2L Case 9", algorithm: "U' R U' R' U F' U' F", image: "/images/3x3/F2L/f2l91.png" },
  { id: "f2l-10-1", title: "F2L Case 10", algorithm: "U' R U R' U R U R'", image: "/images/3x3/F2L/f2l101.png" },
  { id: "f2l-11-1", title: "F2L Case 11", algorithm: "U' R U2' R' U F' U' F", image: "/images/3x3/F2L/f2l111.png" },
  { id: "f2l-12-1", title: "F2L Case 12", algorithm: "R' U2' R2 U R2' U R", image: "/images/3x3/F2L/f2l121.png" },
  { id: "f2l-13-1", title: "F2L Case 13", algorithm: "R U' R' U R' F R F' R U' R'", image: "/images/3x3/F2L/f2l131.png" },
  { id: "f2l-14-1", title: "F2L Case 14", algorithm: "U' R U' R' U R U R'", image: "/images/3x3/F2L/f2l141.png" },
  { id: "f2l-15-1", title: "F2L Case 15", algorithm: "R' D' R U' R' D R U R U' R'", image: "/images/3x3/F2L/f2l151.png" },
  { id: "f2l-16-1", title: "F2L Case 16", algorithm: "R U' R' U2 F' U' F", image: "/images/3x3/F2L/f2l161.png" },
  { id: "f2l-17-1", title: "F2L Case 17", algorithm: "R U2' R' U' R U R'", image: "/images/3x3/F2L/f2l171.png" },
  { id: "f2l-18-1", title: "F2L Case 18", algorithm: "R' F R F' R U' R' U R U' R'", image: "/images/3x3/F2L/f2l181.png" },
  { id: "f2l-19-1", title: "F2L Case 19", algorithm: "U R U2' R' U R U' R'", image: "/images/3x3/F2L/f2l191.png" },
  { id: "f2l-20-1", title: "F2L Case 20", algorithm: "U' R U' R2' F R F' R U' R'", image: "/images/3x3/F2L/f2l201.png" },
  { id: "f2l-21-1", title: "F2L Case 21", algorithm: "U2' R U R' U R U' R'", image: "/images/3x3/F2L/f2l211.png" },
  { id: "f2l-22-1", title: "F2L Case 22", algorithm: "Rw U' Rw' U2 Rw U Rw'", image: "/images/3x3/F2L/f2l221.png" },
  { id: "f2l-23-1", title: "F2L Case 23", algorithm: "U R U' R' U' R U' R' U R U' R'", image: "/images/3x3/F2L/f2l231.png" },
  { id: "f2l-24-1", title: "F2L Case 24", algorithm: "F U R U' R' F' R U' R'", image: "/images/3x3/F2L/f2l241.png" },
  { id: "f2l-25-1", title: "F2L Case 25", algorithm: "U' R' F R F' R U R'", image: "/images/3x3/F2L/f2l251.png" },
  { id: "f2l-26-1", title: "F2L Case 26", algorithm: "U R U' R' F R' F' R", image: "/images/3x3/F2L/f2l261.png" },
  { id: "f2l-27-1", title: "F2L Case 27", algorithm: "R U' R' U R U' R'", image: "/images/3x3/F2L/f2l271.png" },
  { id: "f2l-28-1", title: "F2L Case 28", algorithm: "R U R' U2' F' U F", image: "/images/3x3/F2L/f2l281.png" },
  { id: "f2l-29-1", title: "F2L Case 29", algorithm: "M' U R U' R' U R U' Rw'", image: "/images/3x3/F2L/f2l291.png" },
  { id: "f2l-30-1", title: "F2L Case 30", algorithm: "R U R' U' R U R'", image: "/images/3x3/F2L/f2l301.png" },
  { id: "f2l-31-1", title: "F2L Case 31", algorithm: "U' R' F R F' R U' R'", image: "/images/3x3/F2L/f2l311.png" },
  { id: "f2l-32-1", title: "F2L Case 32", algorithm: "U R U' R' U R U' R' U R U' R'", image: "/images/3x3/F2L/f2l321.png" },
  { id: "f2l-33-1", title: "F2L Case 33", algorithm: "U' R U' R' U2 R U' R'", image: "/images/3x3/F2L/f2l331.png" },
  { id: "f2l-34-1", title: "F2L Case 34", algorithm: "U R U R' U2 R U R'", image: "/images/3x3/F2L/f2l341.png" },
  { id: "f2l-35-1", title: "F2L Case 35", algorithm: "U M' U R U' Rw' R U' R'", image: "/images/3x3/F2L/f2l351.png" },
  { id: "f2l-36-1", title: "F2L Case 36", algorithm: "U2 R' F R F' U2 R U R'", image: "/images/3x3/F2L/f2l361.png" },
  { id: "f2l-37-1", title: "F2L Case 37", algorithm: "R2' U2' F R2 F' U2' R' U R'", image: "/images/3x3/F2L/f2l371.png" },
  { id: "f2l-38-1", title: "F2L Case 38", algorithm: "R U' R' U' R U R' U2 R U' R'", image: "/images/3x3/F2L/f2l381.png" },
  { id: "f2l-39-1", title: "F2L Case 39", algorithm: "R U' R' U R U2' R' U R U' R'", image: "/images/3x3/F2L/f2l391.png" },
  { id: "f2l-40-1", title: "F2L Case 40", algorithm: "F' L' U2 L F R U R'", image: "/images/3x3/F2L/f2l401.png" },
  { id: "f2l-41-1", title: "F2L Case 41", algorithm: "R U' R' F' L' U2 L F", image: "/images/3x3/F2L/f2l411.png" },
]

export const F2L2: MethodOrientation[] = [
  { id: "f2l-1-2", title: "F2L Case 1", algorithm: "", image: "/images/3x3/F2L/f2l12.png" },
  { id: "f2l-2-2", title: "F2L Case 2", algorithm: "", image: "/images/3x3/F2L/f2l22.png" },
  { id: "f2l-3-2", title: "F2L Case 3", algorithm: "", image: "/images/3x3/F2L/f2l32.png" },
  { id: "f2l-4-2", title: "F2L Case 4", algorithm: "", image: "/images/3x3/F2L/f2l42.png" },
  { id: "f2l-5-2", title: "F2L Case 5", algorithm: "", image: "/images/3x3/F2L/f2l52.png" },
  { id: "f2l-6-2", title: "F2L Case 6", algorithm: "", image: "/images/3x3/F2L/f2l62.png" },
  { id: "f2l-7-2", title: "F2L Case 7", algorithm: "", image: "/images/3x3/F2L/f2l72.png" },
  { id: "f2l-8-2", title: "F2L Case 8", algorithm: "", image: "/images/3x3/F2L/f2l82.png" },
  { id: "f2l-9-2", title: "F2L Case 9", algorithm: "", image: "/images/3x3/F2L/f2l92.png" },
  { id: "f2l-10-2", title: "F2L Case 10", algorithm: "", image: "/images/3x3/F2L/f2l102.png" },
  { id: "f2l-11-2", title: "F2L Case 11", algorithm: "", image: "/images/3x3/F2L/f2l112.png" },
  { id: "f2l-12-2", title: "F2L Case 12", algorithm: "", image: "/images/3x3/F2L/f2l122.png" },
  { id: "f2l-13-2", title: "F2L Case 13", algorithm: "", image: "/images/3x3/F2L/f2l132.png" },
  { id: "f2l-14-2", title: "F2L Case 14", algorithm: "", image: "/images/3x3/F2L/f2l142.png" },
  { id: "f2l-15-2", title: "F2L Case 15", algorithm: "", image: "/images/3x3/F2L/f2l152.png" },
  { id: "f2l-16-2", title: "F2L Case 16", algorithm: "", image: "/images/3x3/F2L/f2l162.png" },
  { id: "f2l-17-2", title: "F2L Case 17", algorithm: "", image: "/images/3x3/F2L/f2l172.png" },
  { id: "f2l-18-2", title: "F2L Case 18", algorithm: "", image: "/images/3x3/F2L/f2l182.png" },
  { id: "f2l-19-2", title: "F2L Case 19", algorithm: "", image: "/images/3x3/F2L/f2l192.png" },
  { id: "f2l-20-2", title: "F2L Case 20", algorithm: "", image: "/images/3x3/F2L/f2l202.png" },
  { id: "f2l-21-2", title: "F2L Case 21", algorithm: "", image: "/images/3x3/F2L/f2l212.png" },
  { id: "f2l-22-2", title: "F2L Case 22", algorithm: "", image: "/images/3x3/F2L/f2l222.png" },
  { id: "f2l-23-2", title: "F2L Case 23", algorithm: "", image: "/images/3x3/F2L/f2l232.png" },
  { id: "f2l-24-2", title: "F2L Case 24", algorithm: "", image: "/images/3x3/F2L/f2l242.png" },
  { id: "f2l-25-2", title: "F2L Case 25", algorithm: "", image: "/images/3x3/F2L/f2l252.png" },
  { id: "f2l-26-2", title: "F2L Case 26", algorithm: "", image: "/images/3x3/F2L/f2l262.png" },
  { id: "f2l-27-2", title: "F2L Case 27", algorithm: "", image: "/images/3x3/F2L/f2l272.png" },
  { id: "f2l-28-2", title: "F2L Case 28", algorithm: "", image: "/images/3x3/F2L/f2l282.png" },
  { id: "f2l-29-2", title: "F2L Case 29", algorithm: "", image: "/images/3x3/F2L/f2l292.png" },
  { id: "f2l-30-2", title: "F2L Case 30", algorithm: "", image: "/images/3x3/F2L/f2l302.png" },
  { id: "f2l-31-2", title: "F2L Case 31", algorithm: "", image: "/images/3x3/F2L/f2l312.png" },
  { id: "f2l-32-2", title: "F2L Case 32", algorithm: "", image: "/images/3x3/F2L/f2l322.png" },
  { id: "f2l-33-2", title: "F2L Case 33", algorithm: "", image: "/images/3x3/F2L/f2l332.png" },
  { id: "f2l-34-2", title: "F2L Case 34", algorithm: "", image: "/images/3x3/F2L/f2l342.png" },
  { id: "f2l-35-2", title: "F2L Case 35", algorithm: "", image: "/images/3x3/F2L/f2l352.png" },
  { id: "f2l-36-2", title: "F2L Case 36", algorithm: "", image: "/images/3x3/F2L/f2l362.png" },
  { id: "f2l-37-2", title: "F2L Case 37", algorithm: "", image: "/images/3x3/F2L/f2l372.png" },
  { id: "f2l-38-2", title: "F2L Case 38", algorithm: "", image: "/images/3x3/F2L/f2l382.png" },
  { id: "f2l-39-2", title: "F2L Case 39", algorithm: "", image: "/images/3x3/F2L/f2l392.png" },
  { id: "f2l-40-2", title: "F2L Case 40", algorithm: "", image: "/images/3x3/F2L/f2l402.png" },
  { id: "f2l-41-2", title: "F2L Case 41", algorithm: "", image: "/images/3x3/F2L/f2l412.png" },
]

export const F2L3: MethodOrientation[] = [
  { id: "f2l-1-3", title: "F2L Case 1", algorithm: "", image: "/images/3x3/F2L/f2l13.png" },
  { id: "f2l-2-3", title: "F2L Case 2", algorithm: "", image: "/images/3x3/F2L/f2l23.png" },
  { id: "f2l-3-3", title: "F2L Case 3", algorithm: "", image: "/images/3x3/F2L/f2l33.png" },
  { id: "f2l-4-3", title: "F2L Case 4", algorithm: "", image: "/images/3x3/F2L/f2l43.png" },
  { id: "f2l-5-3", title: "F2L Case 5", algorithm: "", image: "/images/3x3/F2L/f2l53.png" },
  { id: "f2l-6-3", title: "F2L Case 6", algorithm: "", image: "/images/3x3/F2L/f2l63.png" },
  { id: "f2l-7-3", title: "F2L Case 7", algorithm: "", image: "/images/3x3/F2L/f2l73.png" },
  { id: "f2l-8-3", title: "F2L Case 8", algorithm: "", image: "/images/3x3/F2L/f2l83.png" },
  { id: "f2l-9-3", title: "F2L Case 9", algorithm: "", image: "/images/3x3/F2L/f2l93.png" },
  { id: "f2l-10-3", title: "F2L Case 10", algorithm: "", image: "/images/3x3/F2L/f2l103.png" },
  { id: "f2l-11-3", title: "F2L Case 11", algorithm: "", image: "/images/3x3/F2L/f2l113.png" },
  { id: "f2l-12-3", title: "F2L Case 12", algorithm: "", image: "/images/3x3/F2L/f2l123.png" },
  { id: "f2l-13-3", title: "F2L Case 13", algorithm: "", image: "/images/3x3/F2L/f2l133.png" },
  { id: "f2l-14-3", title: "F2L Case 14", algorithm: "", image: "/images/3x3/F2L/f2l143.png" },
  { id: "f2l-15-3", title: "F2L Case 15", algorithm: "", image: "/images/3x3/F2L/f2l153.png" },
  { id: "f2l-16-3", title: "F2L Case 16", algorithm: "", image: "/images/3x3/F2L/f2l163.png" },
  { id: "f2l-17-3", title: "F2L Case 17", algorithm: "", image: "/images/3x3/F2L/f2l173.png" },
  { id: "f2l-18-3", title: "F2L Case 18", algorithm: "", image: "/images/3x3/F2L/f2l183.png" },
  { id: "f2l-19-3", title: "F2L Case 19", algorithm: "", image: "/images/3x3/F2L/f2l193.png" },
  { id: "f2l-20-3", title: "F2L Case 20", algorithm: "", image: "/images/3x3/F2L/f2l203.png" },
  { id: "f2l-21-3", title: "F2L Case 21", algorithm: "", image: "/images/3x3/F2L/f2l213.png" },
  { id: "f2l-22-3", title: "F2L Case 22", algorithm: "", image: "/images/3x3/F2L/f2l223.png" },
  { id: "f2l-23-3", title: "F2L Case 23", algorithm: "", image: "/images/3x3/F2L/f2l233.png" },
  { id: "f2l-24-3", title: "F2L Case 24", algorithm: "", image: "/images/3x3/F2L/f2l243.png" },
  { id: "f2l-25-3", title: "F2L Case 25", algorithm: "", image: "/images/3x3/F2L/f2l253.png" },
  { id: "f2l-26-3", title: "F2L Case 26", algorithm: "", image: "/images/3x3/F2L/f2l263.png" },
  { id: "f2l-27-3", title: "F2L Case 27", algorithm: "", image: "/images/3x3/F2L/f2l273.png" },
  { id: "f2l-28-3", title: "F2L Case 28", algorithm: "", image: "/images/3x3/F2L/f2l283.png" },
  { id: "f2l-29-3", title: "F2L Case 29", algorithm: "", image: "/images/3x3/F2L/f2l293.png" },
  { id: "f2l-30-3", title: "F2L Case 30", algorithm: "", image: "/images/3x3/F2L/f2l303.png" },
  { id: "f2l-31-3", title: "F2L Case 31", algorithm: "", image: "/images/3x3/F2L/f2l313.png" },
  { id: "f2l-32-3", title: "F2L Case 32", algorithm: "", image: "/images/3x3/F2L/f2l323.png" },
  { id: "f2l-33-3", title: "F2L Case 33", algorithm: "", image: "/images/3x3/F2L/f2l333.png" },
  { id: "f2l-34-3", title: "F2L Case 34", algorithm: "", image: "/images/3x3/F2L/f2l343.png" },
  { id: "f2l-35-3", title: "F2L Case 35", algorithm: "", image: "/images/3x3/F2L/f2l353.png" },
  { id: "f2l-36-3", title: "F2L Case 36", algorithm: "", image: "/images/3x3/F2L/f2l363.png" },
  { id: "f2l-37-3", title: "F2L Case 37", algorithm: "", image: "/images/3x3/F2L/f2l373.png" },
  { id: "f2l-38-3", title: "F2L Case 38", algorithm: "", image: "/images/3x3/F2L/f2l383.png" },
  { id: "f2l-39-3", title: "F2L Case 39", algorithm: "", image: "/images/3x3/F2L/f2l393.png" },
  { id: "f2l-40-3", title: "F2L Case 40", algorithm: "", image: "/images/3x3/F2L/f2l403.png" },
  { id: "f2l-41-3", title: "F2L Case 41", algorithm: "", image: "/images/3x3/F2L/f2l413.png" },
]

export const F2L4: MethodOrientation[] = [
  { id: "f2l-1-4", title: "F2L Case 1", algorithm: "", image: "/images/3x3/F2L/f2l14.png" },
  { id: "f2l-2-4", title: "F2L Case 2", algorithm: "", image: "/images/3x3/F2L/f2l24.png" },
  { id: "f2l-3-4", title: "F2L Case 3", algorithm: "", image: "/images/3x3/F2L/f2l34.png" },
  { id: "f2l-4-4", title: "F2L Case 4", algorithm: "", image: "/images/3x3/F2L/f2l44.png" },
  { id: "f2l-5-4", title: "F2L Case 5", algorithm: "", image: "/images/3x3/F2L/f2l54.png" },
  { id: "f2l-6-4", title: "F2L Case 6", algorithm: "", image: "/images/3x3/F2L/f2l64.png" },
  { id: "f2l-7-4", title: "F2L Case 7", algorithm: "", image: "/images/3x3/F2L/f2l74.png" },
  { id: "f2l-8-4", title: "F2L Case 8", algorithm: "", image: "/images/3x3/F2L/f2l84.png" },
  { id: "f2l-9-4", title: "F2L Case 9", algorithm: "", image: "/images/3x3/F2L/f2l94.png" },
  { id: "f2l-10-4", title: "F2L Case 10", algorithm: "", image: "/images/3x3/F2L/f2l104.png" },
  { id: "f2l-11-4", title: "F2L Case 11", algorithm: "", image: "/images/3x3/F2L/f2l114.png" },
  { id: "f2l-12-4", title: "F2L Case 12", algorithm: "", image: "/images/3x3/F2L/f2l124.png" },
  { id: "f2l-13-4", title: "F2L Case 13", algorithm: "", image: "/images/3x3/F2L/f2l134.png" },
  { id: "f2l-14-4", title: "F2L Case 14", algorithm: "", image: "/images/3x3/F2L/f2l144.png" },
  { id: "f2l-15-4", title: "F2L Case 15", algorithm: "", image: "/images/3x3/F2L/f2l154.png" },
  { id: "f2l-16-4", title: "F2L Case 16", algorithm: "", image: "/images/3x3/F2L/f2l164.png" },
  { id: "f2l-17-4", title: "F2L Case 17", algorithm: "", image: "/images/3x3/F2L/f2l174.png" },
  { id: "f2l-18-4", title: "F2L Case 18", algorithm: "", image: "/images/3x3/F2L/f2l184.png" },
  { id: "f2l-19-4", title: "F2L Case 19", algorithm: "", image: "/images/3x3/F2L/f2l194.png" },
  { id: "f2l-20-4", title: "F2L Case 20", algorithm: "", image: "/images/3x3/F2L/f2l204.png" },
  { id: "f2l-21-4", title: "F2L Case 21", algorithm: "", image: "/images/3x3/F2L/f2l214.png" },
  { id: "f2l-22-4", title: "F2L Case 22", algorithm: "", image: "/images/3x3/F2L/f2l224.png" },
  { id: "f2l-23-4", title: "F2L Case 23", algorithm: "", image: "/images/3x3/F2L/f2l234.png" },
  { id: "f2l-24-4", title: "F2L Case 24", algorithm: "", image: "/images/3x3/F2L/f2l244.png" },
  { id: "f2l-25-4", title: "F2L Case 25", algorithm: "", image: "/images/3x3/F2L/f2l254.png" },
  { id: "f2l-26-4", title: "F2L Case 26", algorithm: "", image: "/images/3x3/F2L/f2l264.png" },
  { id: "f2l-27-4", title: "F2L Case 27", algorithm: "", image: "/images/3x3/F2L/f2l274.png" },
  { id: "f2l-28-4", title: "F2L Case 28", algorithm: "", image: "/images/3x3/F2L/f2l284.png" },
  { id: "f2l-29-4", title: "F2L Case 29", algorithm: "", image: "/images/3x3/F2L/f2l294.png" },
  { id: "f2l-30-4", title: "F2L Case 30", algorithm: "", image: "/images/3x3/F2L/f2l304.png" },
  { id: "f2l-31-4", title: "F2L Case 31", algorithm: "", image: "/images/3x3/F2L/f2l314.png" },
  { id: "f2l-32-4", title: "F2L Case 32", algorithm: "", image: "/images/3x3/F2L/f2l324.png" },
  { id: "f2l-33-4", title: "F2L Case 33", algorithm: "", image: "/images/3x3/F2L/f2l334.png" },
  { id: "f2l-34-4", title: "F2L Case 34", algorithm: "", image: "/images/3x3/F2L/f2l344.png" },
  { id: "f2l-35-4", title: "F2L Case 35", algorithm: "", image: "/images/3x3/F2L/f2l354.png" },
  { id: "f2l-36-4", title: "F2L Case 36", algorithm: "", image: "/images/3x3/F2L/f2l364.png" },
  { id: "f2l-37-4", title: "F2L Case 37", algorithm: "", image: "/images/3x3/F2L/f2l374.png" },
  { id: "f2l-38-4", title: "F2L Case 38", algorithm: "", image: "/images/3x3/F2L/f2l384.png" },
  { id: "f2l-39-4", title: "F2L Case 39", algorithm: "", image: "/images/3x3/F2L/f2l394.png" },
  { id: "f2l-40-4", title: "F2L Case 40", algorithm: "", image: "/images/3x3/F2L/f2l404.png" },
  { id: "f2l-41-4", title: "F2L Case 41", algorithm: "", image: "/images/3x3/F2L/f2l414.png" },
]

export const ThreeXThreeF2LCases: MethodCase[] = F2L1.map((item, index) => ({
  ...item,
  algorithm: F2L1[index].algorithm,
  algorithms: [F2L1[index].algorithm, F2L2[index].algorithm, F2L3[index].algorithm, F2L4[index].algorithm],
  orientations: [F2L1[index], F2L2[index], F2L3[index], F2L4[index]],
}))

const threeXThreeOLLBase: MethodCase[] = [
  { id: "oll-1", title: "OLL 1", algorithm: "R U2' R2' F R F' U2 R' F R F'", image: "/images/3x3/oll/oll-1.png" },
  { id: "oll-2", title: "OLL 2", algorithm: "r U r' U2 r U2 R' U2 R U' r'", image: "/images/3x3/oll/oll-2.png" },
  { id: "oll-3", title: "OLL 3", algorithm: "r' R2 U R' U r U2' r' U M'", image: "/images/3x3/oll/oll-3.png" },
  { id: "oll-4", title: "OLL 4", algorithm: "l L2 U' L U' l' U2 l U' M'", image: "/images/3x3/oll/oll-4.png" },
  { id: "oll-5", title: "OLL 5", algorithm: "r' U2' R U R' U r", image: "/images/3x3/oll/oll-5.png" },
  { id: "oll-6", title: "OLL 6", algorithm: "r U2' R' U' R U' r'", image: "/images/3x3/oll/oll-6.png" },
  { id: "oll-7", title: "OLL 7", algorithm: "r U R' U R U2' r'", image: "/images/3x3/oll/oll-7.png" },
  { id: "oll-8", title: "OLL 8", algorithm: "r' U' R U' R' U2 r",   image: "/images/3x3/oll/oll-8.png" },
  { id: "oll-9", title: "OLL 9", algorithm: "R U R' U' R' F R2 U R' U' F'", image: "/images/3x3/oll/oll-9.png" },
  { id: "oll-10", title: "OLL 10", algorithm: "r R2' U2' R U R' U R U R r'", image: "/images/3x3/oll/oll-10.png" },
  { id: "oll-11", title: "OLL 11", algorithm: "r U R' U R' F R F' R U2' r'", image: "/images/3x3/oll/oll-11.png" },
  { id: "oll-12", title: "OLL 12", algorithm: "M' R' U' R U' R' U2 R U' R r'", image: "/images/3x3/oll/oll-12.png" },
  { id: "oll-13", title: "OLL 13", algorithm: "r U' r' U' r U r' F' U F", image: "/images/3x3/oll/oll-13.png" },
  { id: "oll-14", title: "OLL 14", algorithm: "R' F R U R' F' R F U' F'", image: "/images/3x3/oll/oll-14.png" },
  { id: "oll-15", title: "OLL 15", algorithm: "l' U' l L' U' L U l' U l", image: "/images/3x3/oll/oll-15.png" },
  { id: "oll-16", title: "OLL 16", algorithm: "r U r' R U R' U' r U' r'", image: "/images/3x3/oll/oll-16.png" },
  { id: "oll-17", title: "OLL 17", algorithm: "F R' F' R2 r' U R U' R' U' M'", image: "/images/3x3/oll/oll-17.png" },
  { id: "oll-18", title: "OLL 18", algorithm: "r U R' U R U2' r2' U' R U' R' U2 r", image: "/images/3x3/oll/oll-18.png" },
  { id: "oll-19", title: "OLL 19", algorithm: "M U R U R' U' M' R' F R F'", image: "/images/3x3/oll/oll-19.png" },
  { id: "oll-20", title: "OLL 20", algorithm: "M U R U R' U' M2' U R U' r'", image: "/images/3x3/oll/oll-20.png" },
  { id: "oll-21", title: "OLL 21", algorithm: "R U2' R' U' R U R' U' R U' R'", image: "/images/3x3/oll/oll-21.png" },
  { id: "oll-22", title: "OLL 22", algorithm: "R U2' R2' U' R2 U' R2' U2' R", image: "/images/3x3/oll/oll-22.png" },
  { id: "oll-23", title: "OLL 23", algorithm: "R2 D R' U2 R D' R' U2 R'", image: "/images/3x3/oll/oll-23.png" },
  { id: "oll-24", title: "OLL 24", algorithm: "r U R' U' r' F R F'", image: "/images/3x3/oll/oll-24.png" },
  { id: "oll-25", title: "OLL 25", algorithm: "F R' F' r U R U' r'", image: "/images/3x3/oll/oll-25.png" },
  { id: "oll-26", title: "OLL 26", algorithm: "R' U' R U' R' U2 R", image: "/images/3x3/oll/oll-26.png" },
  { id: "oll-27", title: "OLL 27", algorithm: "R U R' U R U2' R'", image: "/images/3x3/oll/oll-27.png" },
  { id: "oll-28", title: "OLL 28", algorithm: "r U R' U' M U R U' R'", image: "/images/3x3/oll/oll-28.png" },
  { id: "oll-29", title: "OLL 29", algorithm: "R U R' U' R U' R' F' U' F R U R'", image: "/images/3x3/oll/oll-29.png" },
  { id: "oll-30", title: "OLL 30", algorithm: "F R' F R2 U' R' U' R U R' F2'", image: "/images/3x3/oll/oll-30.png" },
  { id: "oll-31", title: "OLL 31", algorithm: "R' U' F U R U' R' F' R", image: "/images/3x3/oll/oll-31.png" },
  { id: "oll-32", title: "OLL 32", algorithm: "S R U R' U' R' F R f'", image: "/images/3x3/oll/oll-32.png" },
  { id: "oll-33", title: "OLL 33", algorithm: "R U R' U' R' F R F'", image: "/images/3x3/oll/oll-33.png" },
  { id: "oll-34", title: "OLL 34", algorithm: "R U R2' U' R' F R U R U' F'", image: "/images/3x3/oll/oll-34.png" },
  { id: "oll-35", title: "OLL 35", algorithm: "R U2' R2' F R F' R U2' R'", image: "/images/3x3/oll/oll-35.png" },
  { id: "oll-36", title: "OLL 36", algorithm: "L' U' L U' L' U L U L F' L' F", image: "/images/3x3/oll/oll-36.png" },
  { id: "oll-37", title: "OLL 37", algorithm: "F R' F' R U R U' R'", image: "/images/3x3/oll/oll-37.png" },
  { id: "oll-38", title: "OLL 38", algorithm: "R U R' U R U' R' U' R' F R F'", image: "/images/3x3/oll/oll-38.png" },
  { id: "oll-39", title: "OLL 39", algorithm: "R B' R' U' R U B U' R'", image: "/images/3x3/oll/oll-39.png" },
  { id: "oll-40", title: "OLL 40", algorithm: "R' F R U R' U' F' U R", image: "/images/3x3/oll/oll-40.png" },
  { id: "oll-41", title: "OLL 41", algorithm: "R U R' U R U2 R' F R U R' U' F'", image: "/images/3x3/oll/oll-41.png" },
  { id: "oll-42", title: "OLL 42", algorithm: "R' U' R U' R' U2 R F R U R' U' F'", image: "/images/3x3/oll/oll-42.png",},
  { id: "oll-43", title: "OLL 43", algorithm: "f' L' U' L U f", image: "/images/3x3/oll/oll-43.png" },
  { id: "oll-44", title: "OLL 44", algorithm: "F U R U' R' F'", image: "/images/3x3/oll/oll-44.png" },
  { id: "oll-45", title: "OLL 45", algorithm: "F R U R' U' F'", image: "/images/3x3/oll/oll-45.png" },
  { id: "oll-46", title: "OLL 46", algorithm: "R' U' R' F R F' U R", image: "/images/3x3/oll/oll-46.png" },
  { id: "oll-47", title: "OLL 47", algorithm: "F' L' U' L U L' U' L U F", image: "/images/3x3/oll/oll-47.png" },
  { id: "oll-48", title: "OLL 48", algorithm: "F R U R' U' R U R' U' F'", image: "/images/3x3/oll/oll-48.png" },
  { id: "oll-49", title: "OLL 49", algorithm: "r U' r2' U r2 U r2' U' r", image: "/images/3x3/oll/oll-49.png" },
  { id: "oll-50", title: "OLL 50", algorithm: "r' U r2 U' r2' U' r2 U r'", image: "/images/3x3/oll/oll-50.png" },
  { id: "oll-51", title: "OLL 51", algorithm: "F U R U' R' U R U' R' F'", image: "/images/3x3/oll/oll-51.png" },
  { id: "oll-52", title: "OLL 52", algorithm: "R U R' U R U' B U' B' R'", image: "/images/3x3/oll/oll-52.png" },
  { id: "oll-53", title: "OLL 53", algorithm: "l' U2 L U L' U' L U L' U l", image: "/images/3x3/oll/oll-53.png" },
  { id: "oll-54", title: "OLL 54", algorithm: "r U2' R' U' R U R' U' R U' r'", image: "/images/3x3/oll/oll-54.png" },
  { id: "oll-55", title: "OLL 55", algorithm: "R' F R U R U' R2' F' R2 U' R' U R U R'", image: "/images/3x3/oll/oll-55.png",},
  { id: "oll-56", title: "OLL 56", algorithm: "r U r' (U R U' R') U R U' M' U' r'", image: "/images/3x3/oll/oll-56.png",},
  { id: "oll-57", title: "OLL 57", algorithm: "R U R' U' M' U R U' r'", image: "/images/3x3/oll/oll-57.png" },
]


const threeXThreePLLBase: MethodCase[] = [
  { id: "pll-1", title: "Aa", algorithm: "x L2 D2' L' U' L D2' L' U L' x'", image: "/images/3x3/pll/pll-1.png" },
  { id: "pll-2", title: "Ab", algorithm: "x L U' L D2' L' U L D2' L2", image: "/images/3x3/pll/pll-2.png" },
  { id: "pll-3", title: "E", algorithm: "x' R U' R' D R U R' D' R U R' D R U' R' D' x", image: "/images/3x3/pll/pll-3.png",},
  { id: "pll-4", title: "F", algorithm: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R", image: "/images/3x3/pll/pll-4.png",},
  { id: "pll-5", title: "Ga", algorithm: "R2 U R' U R' U' R U' R2 D U' R' U R D'", image: "/images/3x3/pll/pll-5.png" },
  { id: "pll-6", title: "Gb", algorithm: "R' U' R U D' R2 U R' U R U' R U' R2 D", image: "/images/3x3/pll/pll-6.png" },
  { id: "pll-7", title: "Gc", algorithm: "R2' Uw' R U' R U R' Uw R2 Fw R' Fw'", image: "/images/3x3/pll/pll-7.png" },
  { id: "pll-8", title: "Gd", algorithm: "R U R' U' D R2 U' R U' R' U R' U R2 D'", image: "/images/3x3/pll/pll-8.png" },
  { id: "pll-9", title: "H", algorithm: "M2' U M2' U2 M2' U M2'", image: "/images/3x3/pll/pll-9.png" },
  { id: "pll-10", title: "Ja", algorithm: "x R2' F R F' R U2' Rw' U Rw U2' x'", image: "/images/3x3/pll/pll-10.png" },
  { id: "pll-11", title: "Jb", algorithm: "R U R' F' R U R' U' R' F R2 U' R'", image: "/images/3x3/pll/pll-11.png" },
  { id: "pll-12", title: "Na", algorithm: "z U R' D R2 U' R U D' R' D R2 U' R D' z'", image: "/images/3x3/pll/pll-12.png",},
  { id: "pll-13", title: "Nb", algorithm: "z U' R D' R2 U R' U' D R D' R2 U R' D z'", image: "/images/3x3/pll/pll-13.png",},
  { id: "pll-14", title: "Ra", algorithm: "L U2 L' U2' L F' L' U' L U L F L2'", image: "/images/3x3/pll/pll-14.png" },
  { id: "pll-15", title: "Rb", algorithm: "R' U2 R U2' R' F R U R' U' R' F' R2", image: "/images/3x3/pll/pll-15.png" },
  { id: "pll-16", title: "T", algorithm: "R U R' U' R' F R2 U' R' U' R U R' F'", image: "/images/3x3/pll/pll-16.png" },
  { id: "pll-17", title: "Ua", algorithm: "M2 U M' U2 M U M2", image: "/images/3x3/pll/pll-17.png" },
  { id: "pll-18", title: "Ub", algorithm: "M2 U' M' U2 M U' M2", image: "/images/3x3/pll/pll-18.png" },
  { id: "pll-19", title: "V", algorithm: "R' U R' U' R D' R' D R' U D' R2 U' R2' D R2", image: "/images/3x3/pll/pll-19.png",},
  { id: "pll-20", title: "Y", algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F'", image: "/images/3x3/pll/pll-20.png",},
  { id: "pll-21", title: "Z", algorithm: "M2 U M2 U M' U2 M2 U2 M'", image: "/images/3x3/pll/pll-21.png" },
]


export const OLL1: MethodOrientation[] = [
  { id: "oll-1-1", title: "OLL 1", algorithm: "R U2' R2' F R F' U2 R' F R F'", image: "/images/3x3/oll/oll-1.png" },
  { id: "oll-2-1", title: "OLL 2", algorithm: "r U r' U2 r U2 R' U2 R U' r'", image: "/images/3x3/oll/oll-2.png" },
  { id: "oll-3-1", title: "OLL 3", algorithm: "r' R2 U R' U r U2' r' U M'", image: "/images/3x3/oll/oll-3.png" },
  { id: "oll-4-1", title: "OLL 4", algorithm: "l L2 U' L U' l' U2 l U' M'", image: "/images/3x3/oll/oll-4.png" },
  { id: "oll-5-1", title: "OLL 5", algorithm: "r' U2' R U R' U r", image: "/images/3x3/oll/oll-5.png" },
  { id: "oll-6-1", title: "OLL 6", algorithm: "r U2' R' U' R U' r'", image: "/images/3x3/oll/oll-6.png" },
  { id: "oll-7-1", title: "OLL 7", algorithm: "r U R' U R U2' r'", image: "/images/3x3/oll/oll-7.png" },
  { id: "oll-9-1", title: "OLL 9", algorithm: "R U R' U' R' F R2 U R' U' F'", image: "/images/3x3/oll/oll-9.png" },
  { id: "oll-10-1", title: "OLL 10", algorithm: "r R2' U2' R U R' U R U R r'", image: "/images/3x3/oll/oll-10.png" },
  { id: "oll-11-1", title: "OLL 11", algorithm: "r U R' U R' F R F' R U2' r'", image: "/images/3x3/oll/oll-11.png" },
  { id: "oll-12-1", title: "OLL 12", algorithm: "M' R' U' R U' R' U2 R U' R r'", image: "/images/3x3/oll/oll-12.png" },
  { id: "oll-13-1", title: "OLL 13", algorithm: "r U' r' U' r U r' F' U F", image: "/images/3x3/oll/oll-13.png" },
  { id: "oll-14-1", title: "OLL 14", algorithm: "R' F R U R' F' R F U' F'", image: "/images/3x3/oll/oll-14.png" },
  { id: "oll-15-1", title: "OLL 15", algorithm: "l' U' l L' U' L U l' U l", image: "/images/3x3/oll/oll-15.png" },
  { id: "oll-16-1", title: "OLL 16", algorithm: "r U r' R U R' U' r U' r'", image: "/images/3x3/oll/oll-16.png" },
  { id: "oll-17-1", title: "OLL 17", algorithm: "F R' F' R2 r' U R U' R' U' M'", image: "/images/3x3/oll/oll-17.png" },
  { id: "oll-18-1", title: "OLL 18", algorithm: "r U R' U R U2' r2' U' R U' R' U2 r", image: "/images/3x3/oll/oll-18.png" },
  { id: "oll-19-1", title: "OLL 19", algorithm: "M U R U R' U' M' R' F R F'", image: "/images/3x3/oll/oll-19.png" },
  { id: "oll-20-1", title: "OLL 20", algorithm: "M U R U R' U' M2' U R U' r'", image: "/images/3x3/oll/oll-20.png" },
  { id: "oll-21-1", title: "OLL 21", algorithm: "R U2' R' U' R U R' U' R U' R'", image: "/images/3x3/oll/oll-21.png" },
  { id: "oll-22-1", title: "OLL 22", algorithm: "R U2' R2' U' R2 U' R2' U2' R", image: "/images/3x3/oll/oll-22.png" },
  { id: "oll-23-1", title: "OLL 23", algorithm: "R2 D R' U2 R D' R' U2 R'", image: "/images/3x3/oll/oll-23.png" },
  { id: "oll-24-1", title: "OLL 24", algorithm: "r U R' U' r' F R F'", image: "/images/3x3/oll/oll-24.png" },
  { id: "oll-25-1", title: "OLL 25", algorithm: "F R' F' r U R U' r'", image: "/images/3x3/oll/oll-25.png" },
  { id: "oll-26-1", title: "OLL 26", algorithm: "R' U' R U' R' U2 R", image: "/images/3x3/oll/oll-26.png" },
  { id: "oll-27-1", title: "OLL 27", algorithm: "R U R' U R U2' R'", image: "/images/3x3/oll/oll-27.png" },
  { id: "oll-28-1", title: "OLL 28", algorithm: "r U R' U' M U R U' R'", image: "/images/3x3/oll/oll-28.png" },
  { id: "oll-29-1", title: "OLL 29", algorithm: "R U R' U' R U' R' F' U' F R U R'", image: "/images/3x3/oll/oll-29.png" },
  { id: "oll-30-1", title: "OLL 30", algorithm: "F R' F R2 U' R' U' R U R' F2'", image: "/images/3x3/oll/oll-30.png" },
  { id: "oll-31-1", title: "OLL 31", algorithm: "R' U' F U R U' R' F' R", image: "/images/3x3/oll/oll-31.png" },
  { id: "oll-32-1", title: "OLL 32", algorithm: "S R U R' U' R' F R f'", image: "/images/3x3/oll/oll-32.png" },
  { id: "oll-33-1", title: "OLL 33", algorithm: "R U R' U' R' F R F'", image: "/images/3x3/oll/oll-33.png" },
  { id: "oll-34-1", title: "OLL 34", algorithm: "R U R2' U' R' F R U R U' F'", image: "/images/3x3/oll/oll-34.png" },
  { id: "oll-35-1", title: "OLL 35", algorithm: "R U2' R2' F R F' R U2' R'", image: "/images/3x3/oll/oll-35.png" },
  { id: "oll-36-1", title: "OLL 36", algorithm: "L' U' L U' L' U L U L F' L' F", image: "/images/3x3/oll/oll-36.png" },
  { id: "oll-37-1", title: "OLL 37", algorithm: "F R' F' R U R U' R'", image: "/images/3x3/oll/oll-37.png" },
  { id: "oll-38-1", title: "OLL 38", algorithm: "R U R' U R U' R' U' R' F R F'", image: "/images/3x3/oll/oll-38.png" },
  { id: "oll-39-1", title: "OLL 39", algorithm: "R B' R' U' R U B U' R'", image: "/images/3x3/oll/oll-39.png" },
  { id: "oll-40-1", title: "OLL 40", algorithm: "R' F R U R' U' F' U R", image: "/images/3x3/oll/oll-40.png" },
  { id: "oll-41-1", title: "OLL 41", algorithm: "R U R' U R U2 R' F R U R' U' F'", image: "/images/3x3/oll/oll-41.png" },
  { id: "oll-42-1", title: "OLL 42", algorithm: "R' U' R U' R' U2 R F R U R' U' F'", image: "/images/3x3/oll/oll-42.png" },
  { id: "oll-43-1", title: "OLL 43", algorithm: "f' L' U' L U f", image: "/images/3x3/oll/oll-43.png" },
  { id: "oll-44-1", title: "OLL 44", algorithm: "F U R U' R' F'", image: "/images/3x3/oll/oll-44.png" },
  { id: "oll-45-1", title: "OLL 45", algorithm: "F R U R' U' F'", image: "/images/3x3/oll/oll-45.png" },
  { id: "oll-46-1", title: "OLL 46", algorithm: "R' U' R' F R F' U R", image: "/images/3x3/oll/oll-46.png" },
  { id: "oll-47-1", title: "OLL 47", algorithm: "F' L' U' L U L' U' L U F", image: "/images/3x3/oll/oll-47.png" },
  { id: "oll-48-1", title: "OLL 48", algorithm: "F R U R' U' R U R' U' F'", image: "/images/3x3/oll/oll-48.png" },
  { id: "oll-49-1", title: "OLL 49", algorithm: "r U' r2' U r2 U r2' U' r", image: "/images/3x3/oll/oll-49.png" },
  { id: "oll-50-1", title: "OLL 50", algorithm: "r' U r2 U' r2' U' r2 U r'", image: "/images/3x3/oll/oll-50.png" },
  { id: "oll-51-1", title: "OLL 51", algorithm: "F U R U' R' U R U' R' F'", image: "/images/3x3/oll/oll-51.png" },
  { id: "oll-52-1", title: "OLL 52", algorithm: "R U R' U R U' B U' B' R'", image: "/images/3x3/oll/oll-52.png" },
  { id: "oll-53-1", title: "OLL 53", algorithm: "l' U2 L U L' U' L U L' U l", image: "/images/3x3/oll/oll-53.png" },
  { id: "oll-54-1", title: "OLL 54", algorithm: "r U2' R' U' R U R' U' R U' r'", image: "/images/3x3/oll/oll-54.png" },
  { id: "oll-55-1", title: "OLL 55", algorithm: "R' F R U R U' R2' F' R2 U' R' U R U R'", image: "/images/3x3/oll/oll-55.png" },
  { id: "oll-56-1", title: "OLL 56", algorithm: "r U r' (U R U' R') U R U' M' U' r'", image: "/images/3x3/oll/oll-56.png" },
  { id: "oll-57-1", title: "OLL 57", algorithm: "R U R' U' M' U R U' r'", image: "/images/3x3/oll/oll-57.png" },
]

export const OLL2: MethodOrientation[] = [
  { id: "oll-1-2", title: "OLL 1", algorithm: "oll2", image: "/images/3x3/oll/oll-1.png" },
  { id: "oll-2-2", title: "OLL 2", algorithm: "", image: "/images/3x3/oll/oll-2.png" },
  { id: "oll-3-2", title: "OLL 3", algorithm: "", image: "/images/3x3/oll/oll-3.png" },
  { id: "oll-4-2", title: "OLL 4", algorithm: "", image: "/images/3x3/oll/oll-4.png" },
  { id: "oll-5-2", title: "OLL 5", algorithm: "", image: "/images/3x3/oll/oll-5.png" },
  { id: "oll-6-2", title: "OLL 6", algorithm: "", image: "/images/3x3/oll/oll-6.png" },
  { id: "oll-7-2", title: "OLL 7", algorithm: "", image: "/images/3x3/oll/oll-7.png" },
  { id: "oll-9-2", title: "OLL 9", algorithm: "", image: "/images/3x3/oll/oll-9.png" },
  { id: "oll-10-2", title: "OLL 10", algorithm: "", image: "/images/3x3/oll/oll-10.png" },
  { id: "oll-11-2", title: "OLL 11", algorithm: "", image: "/images/3x3/oll/oll-11.png" },
  { id: "oll-12-2", title: "OLL 12", algorithm: "", image: "/images/3x3/oll/oll-12.png" },
  { id: "oll-13-2", title: "OLL 13", algorithm: "", image: "/images/3x3/oll/oll-13.png" },
  { id: "oll-14-2", title: "OLL 14", algorithm: "", image: "/images/3x3/oll/oll-14.png" },
  { id: "oll-15-2", title: "OLL 15", algorithm: "", image: "/images/3x3/oll/oll-15.png" },
  { id: "oll-16-2", title: "OLL 16", algorithm: "", image: "/images/3x3/oll/oll-16.png" },
  { id: "oll-17-2", title: "OLL 17", algorithm: "", image: "/images/3x3/oll/oll-17.png" },
  { id: "oll-18-2", title: "OLL 18", algorithm: "", image: "/images/3x3/oll/oll-18.png" },
  { id: "oll-19-2", title: "OLL 19", algorithm: "", image: "/images/3x3/oll/oll-19.png" },
  { id: "oll-20-2", title: "OLL 20", algorithm: "", image: "/images/3x3/oll/oll-20.png" },
  { id: "oll-21-2", title: "OLL 21", algorithm: "", image: "/images/3x3/oll/oll-21.png" },
  { id: "oll-22-2", title: "OLL 22", algorithm: "", image: "/images/3x3/oll/oll-22.png" },
  { id: "oll-23-2", title: "OLL 23", algorithm: "", image: "/images/3x3/oll/oll-23.png" },
  { id: "oll-24-2", title: "OLL 24", algorithm: "", image: "/images/3x3/oll/oll-24.png" },
  { id: "oll-25-2", title: "OLL 25", algorithm: "", image: "/images/3x3/oll/oll-25.png" },
  { id: "oll-26-2", title: "OLL 26", algorithm: "", image: "/images/3x3/oll/oll-26.png" },
  { id: "oll-27-2", title: "OLL 27", algorithm: "", image: "/images/3x3/oll/oll-27.png" },
  { id: "oll-28-2", title: "OLL 28", algorithm: "", image: "/images/3x3/oll/oll-28.png" },
  { id: "oll-29-2", title: "OLL 29", algorithm: "", image: "/images/3x3/oll/oll-29.png" },
  { id: "oll-30-2", title: "OLL 30", algorithm: "", image: "/images/3x3/oll/oll-30.png" },
  { id: "oll-31-2", title: "OLL 31", algorithm: "", image: "/images/3x3/oll/oll-31.png" },
  { id: "oll-32-2", title: "OLL 32", algorithm: "", image: "/images/3x3/oll/oll-32.png" },
  { id: "oll-33-2", title: "OLL 33", algorithm: "", image: "/images/3x3/oll/oll-33.png" },
  { id: "oll-34-2", title: "OLL 34", algorithm: "", image: "/images/3x3/oll/oll-34.png" },
  { id: "oll-35-2", title: "OLL 35", algorithm: "", image: "/images/3x3/oll/oll-35.png" },
  { id: "oll-36-2", title: "OLL 36", algorithm: "", image: "/images/3x3/oll/oll-36.png" },
  { id: "oll-37-2", title: "OLL 37", algorithm: "", image: "/images/3x3/oll/oll-37.png" },
  { id: "oll-38-2", title: "OLL 38", algorithm: "", image: "/images/3x3/oll/oll-38.png" },
  { id: "oll-39-2", title: "OLL 39", algorithm: "", image: "/images/3x3/oll/oll-39.png" },
  { id: "oll-40-2", title: "OLL 40", algorithm: "", image: "/images/3x3/oll/oll-40.png" },
  { id: "oll-41-2", title: "OLL 41", algorithm: "", image: "/images/3x3/oll/oll-41.png" },
  { id: "oll-42-2", title: "OLL 42", algorithm: "", image: "/images/3x3/oll/oll-42.png" },
  { id: "oll-43-2", title: "OLL 43", algorithm: "", image: "/images/3x3/oll/oll-43.png" },
  { id: "oll-44-2", title: "OLL 44", algorithm: "", image: "/images/3x3/oll/oll-44.png" },
  { id: "oll-45-2", title: "OLL 45", algorithm: "", image: "/images/3x3/oll/oll-45.png" },
  { id: "oll-46-2", title: "OLL 46", algorithm: "", image: "/images/3x3/oll/oll-46.png" },
  { id: "oll-47-2", title: "OLL 47", algorithm: "", image: "/images/3x3/oll/oll-47.png" },
  { id: "oll-48-2", title: "OLL 48", algorithm: "", image: "/images/3x3/oll/oll-48.png" },
  { id: "oll-49-2", title: "OLL 49", algorithm: "", image: "/images/3x3/oll/oll-49.png" },
  { id: "oll-50-2", title: "OLL 50", algorithm: "", image: "/images/3x3/oll/oll-50.png" },
  { id: "oll-51-2", title: "OLL 51", algorithm: "", image: "/images/3x3/oll/oll-51.png" },
  { id: "oll-52-2", title: "OLL 52", algorithm: "", image: "/images/3x3/oll/oll-52.png" },
  { id: "oll-53-2", title: "OLL 53", algorithm: "", image: "/images/3x3/oll/oll-53.png" },
  { id: "oll-54-2", title: "OLL 54", algorithm: "", image: "/images/3x3/oll/oll-54.png" },
  { id: "oll-55-2", title: "OLL 55", algorithm: "", image: "/images/3x3/oll/oll-55.png" },
  { id: "oll-56-2", title: "OLL 56", algorithm: "", image: "/images/3x3/oll/oll-56.png" },
  { id: "oll-57-2", title: "OLL 57", algorithm: "", image: "/images/3x3/oll/oll-57.png" },
]

export const OLL3: MethodOrientation[] = [
  { id: "oll-1-3", title: "OLL 1", algorithm: "oll3", image: "/images/3x3/oll/oll-1.png" },
  { id: "oll-2-3", title: "OLL 2", algorithm: "", image: "/images/3x3/oll/oll-2.png" },
  { id: "oll-3-3", title: "OLL 3", algorithm: "", image: "/images/3x3/oll/oll-3.png" },
  { id: "oll-4-3", title: "OLL 4", algorithm: "", image: "/images/3x3/oll/oll-4.png" },
  { id: "oll-5-3", title: "OLL 5", algorithm: "", image: "/images/3x3/oll/oll-5.png" },
  { id: "oll-6-3", title: "OLL 6", algorithm: "", image: "/images/3x3/oll/oll-6.png" },
  { id: "oll-7-3", title: "OLL 7", algorithm: "", image: "/images/3x3/oll/oll-7.png" },
  { id: "oll-9-3", title: "OLL 9", algorithm: "", image: "/images/3x3/oll/oll-9.png" },
  { id: "oll-10-3", title: "OLL 10", algorithm: "", image: "/images/3x3/oll/oll-10.png" },
  { id: "oll-11-3", title: "OLL 11", algorithm: "", image: "/images/3x3/oll/oll-11.png" },
  { id: "oll-12-3", title: "OLL 12", algorithm: "", image: "/images/3x3/oll/oll-12.png" },
  { id: "oll-13-3", title: "OLL 13", algorithm: "", image: "/images/3x3/oll/oll-13.png" },
  { id: "oll-14-3", title: "OLL 14", algorithm: "", image: "/images/3x3/oll/oll-14.png" },
  { id: "oll-15-3", title: "OLL 15", algorithm: "", image: "/images/3x3/oll/oll-15.png" },
  { id: "oll-16-3", title: "OLL 16", algorithm: "", image: "/images/3x3/oll/oll-16.png" },
  { id: "oll-17-3", title: "OLL 17", algorithm: "", image: "/images/3x3/oll/oll-17.png" },
  { id: "oll-18-3", title: "OLL 18", algorithm: "", image: "/images/3x3/oll/oll-18.png" },
  { id: "oll-19-3", title: "OLL 19", algorithm: "", image: "/images/3x3/oll/oll-19.png" },
  { id: "oll-20-3", title: "OLL 20", algorithm: "", image: "/images/3x3/oll/oll-20.png" },
  { id: "oll-21-3", title: "OLL 21", algorithm: "", image: "/images/3x3/oll/oll-21.png" },
  { id: "oll-22-3", title: "OLL 22", algorithm: "", image: "/images/3x3/oll/oll-22.png" },
  { id: "oll-23-3", title: "OLL 23", algorithm: "", image: "/images/3x3/oll/oll-23.png" },
  { id: "oll-24-3", title: "OLL 24", algorithm: "", image: "/images/3x3/oll/oll-24.png" },
  { id: "oll-25-3", title: "OLL 25", algorithm: "", image: "/images/3x3/oll/oll-25.png" },
  { id: "oll-26-3", title: "OLL 26", algorithm: "", image: "/images/3x3/oll/oll-26.png" },
  { id: "oll-27-3", title: "OLL 27", algorithm: "", image: "/images/3x3/oll/oll-27.png" },
  { id: "oll-28-3", title: "OLL 28", algorithm: "", image: "/images/3x3/oll/oll-28.png" },
  { id: "oll-29-3", title: "OLL 29", algorithm: "", image: "/images/3x3/oll/oll-29.png" },
  { id: "oll-30-3", title: "OLL 30", algorithm: "", image: "/images/3x3/oll/oll-30.png" },
  { id: "oll-31-3", title: "OLL 31", algorithm: "", image: "/images/3x3/oll/oll-31.png" },
  { id: "oll-32-3", title: "OLL 32", algorithm: "", image: "/images/3x3/oll/oll-32.png" },
  { id: "oll-33-3", title: "OLL 33", algorithm: "", image: "/images/3x3/oll/oll-33.png" },
  { id: "oll-34-3", title: "OLL 34", algorithm: "", image: "/images/3x3/oll/oll-34.png" },
  { id: "oll-35-3", title: "OLL 35", algorithm: "", image: "/images/3x3/oll/oll-35.png" },
  { id: "oll-36-3", title: "OLL 36", algorithm: "", image: "/images/3x3/oll/oll-36.png" },
  { id: "oll-37-3", title: "OLL 37", algorithm: "", image: "/images/3x3/oll/oll-37.png" },
  { id: "oll-38-3", title: "OLL 38", algorithm: "", image: "/images/3x3/oll/oll-38.png" },
  { id: "oll-39-3", title: "OLL 39", algorithm: "", image: "/images/3x3/oll/oll-39.png" },
  { id: "oll-40-3", title: "OLL 40", algorithm: "", image: "/images/3x3/oll/oll-40.png" },
  { id: "oll-41-3", title: "OLL 41", algorithm: "", image: "/images/3x3/oll/oll-41.png" },
  { id: "oll-42-3", title: "OLL 42", algorithm: "", image: "/images/3x3/oll/oll-42.png" },
  { id: "oll-43-3", title: "OLL 43", algorithm: "", image: "/images/3x3/oll/oll-43.png" },
  { id: "oll-44-3", title: "OLL 44", algorithm: "", image: "/images/3x3/oll/oll-44.png" },
  { id: "oll-45-3", title: "OLL 45", algorithm: "", image: "/images/3x3/oll/oll-45.png" },
  { id: "oll-46-3", title: "OLL 46", algorithm: "", image: "/images/3x3/oll/oll-46.png" },
  { id: "oll-47-3", title: "OLL 47", algorithm: "", image: "/images/3x3/oll/oll-47.png" },
  { id: "oll-48-3", title: "OLL 48", algorithm: "", image: "/images/3x3/oll/oll-48.png" },
  { id: "oll-49-3", title: "OLL 49", algorithm: "", image: "/images/3x3/oll/oll-49.png" },
  { id: "oll-50-3", title: "OLL 50", algorithm: "", image: "/images/3x3/oll/oll-50.png" },
  { id: "oll-51-3", title: "OLL 51", algorithm: "", image: "/images/3x3/oll/oll-51.png" },
  { id: "oll-52-3", title: "OLL 52", algorithm: "", image: "/images/3x3/oll/oll-52.png" },
  { id: "oll-53-3", title: "OLL 53", algorithm: "", image: "/images/3x3/oll/oll-53.png" },
  { id: "oll-54-3", title: "OLL 54", algorithm: "", image: "/images/3x3/oll/oll-54.png" },
  { id: "oll-55-3", title: "OLL 55", algorithm: "", image: "/images/3x3/oll/oll-55.png" },
  { id: "oll-56-3", title: "OLL 56", algorithm: "", image: "/images/3x3/oll/oll-56.png" },
  { id: "oll-57-3", title: "OLL 57", algorithm: "", image: "/images/3x3/oll/oll-57.png" },
]

export const OLL4: MethodOrientation[] = [
  { id: "oll-1-4", title: "OLL 1", algorithm: "oll4", image: "/images/3x3/oll/oll-1.png" },
  { id: "oll-2-4", title: "OLL 2", algorithm: "", image: "/images/3x3/oll/oll-2.png" },
  { id: "oll-3-4", title: "OLL 3", algorithm: "", image: "/images/3x3/oll/oll-3.png" },
  { id: "oll-4-4", title: "OLL 4", algorithm: "", image: "/images/3x3/oll/oll-4.png" },
  { id: "oll-5-4", title: "OLL 5", algorithm: "", image: "/images/3x3/oll/oll-5.png" },
  { id: "oll-6-4", title: "OLL 6", algorithm: "", image: "/images/3x3/oll/oll-6.png" },
  { id: "oll-7-4", title: "OLL 7", algorithm: "", image: "/images/3x3/oll/oll-7.png" },
  { id: "oll-9-4", title: "OLL 9", algorithm: "", image: "/images/3x3/oll/oll-9.png" },
  { id: "oll-10-4", title: "OLL 10", algorithm: "", image: "/images/3x3/oll/oll-10.png" },
  { id: "oll-11-4", title: "OLL 11", algorithm: "", image: "/images/3x3/oll/oll-11.png" },
  { id: "oll-12-4", title: "OLL 12", algorithm: "", image: "/images/3x3/oll/oll-12.png" },
  { id: "oll-13-4", title: "OLL 13", algorithm: "", image: "/images/3x3/oll/oll-13.png" },
  { id: "oll-14-4", title: "OLL 14", algorithm: "", image: "/images/3x3/oll/oll-14.png" },
  { id: "oll-15-4", title: "OLL 15", algorithm: "", image: "/images/3x3/oll/oll-15.png" },
  { id: "oll-16-4", title: "OLL 16", algorithm: "", image: "/images/3x3/oll/oll-16.png" },
  { id: "oll-17-4", title: "OLL 17", algorithm: "", image: "/images/3x3/oll/oll-17.png" },
  { id: "oll-18-4", title: "OLL 18", algorithm: "", image: "/images/3x3/oll/oll-18.png" },
  { id: "oll-19-4", title: "OLL 19", algorithm: "", image: "/images/3x3/oll/oll-19.png" },
  { id: "oll-20-4", title: "OLL 20", algorithm: "", image: "/images/3x3/oll/oll-20.png" },
  { id: "oll-21-4", title: "OLL 21", algorithm: "", image: "/images/3x3/oll/oll-21.png" },
  { id: "oll-22-4", title: "OLL 22", algorithm: "", image: "/images/3x3/oll/oll-22.png" },
  { id: "oll-23-4", title: "OLL 23", algorithm: "", image: "/images/3x3/oll/oll-23.png" },
  { id: "oll-24-4", title: "OLL 24", algorithm: "", image: "/images/3x3/oll/oll-24.png" },
  { id: "oll-25-4", title: "OLL 25", algorithm: "", image: "/images/3x3/oll/oll-25.png" },
  { id: "oll-26-4", title: "OLL 26", algorithm: "", image: "/images/3x3/oll/oll-26.png" },
  { id: "oll-27-4", title: "OLL 27", algorithm: "", image: "/images/3x3/oll/oll-27.png" },
  { id: "oll-28-4", title: "OLL 28", algorithm: "", image: "/images/3x3/oll/oll-28.png" },
  { id: "oll-29-4", title: "OLL 29", algorithm: "", image: "/images/3x3/oll/oll-29.png" },
  { id: "oll-30-4", title: "OLL 30", algorithm: "", image: "/images/3x3/oll/oll-30.png" },
  { id: "oll-31-4", title: "OLL 31", algorithm: "", image: "/images/3x3/oll/oll-31.png" },
  { id: "oll-32-4", title: "OLL 32", algorithm: "", image: "/images/3x3/oll/oll-32.png" },
  { id: "oll-33-4", title: "OLL 33", algorithm: "", image: "/images/3x3/oll/oll-33.png" },
  { id: "oll-34-4", title: "OLL 34", algorithm: "", image: "/images/3x3/oll/oll-34.png" },
  { id: "oll-35-4", title: "OLL 35", algorithm: "", image: "/images/3x3/oll/oll-35.png" },
  { id: "oll-36-4", title: "OLL 36", algorithm: "", image: "/images/3x3/oll/oll-36.png" },
  { id: "oll-37-4", title: "OLL 37", algorithm: "", image: "/images/3x3/oll/oll-37.png" },
  { id: "oll-38-4", title: "OLL 38", algorithm: "", image: "/images/3x3/oll/oll-38.png" },
  { id: "oll-39-4", title: "OLL 39", algorithm: "", image: "/images/3x3/oll/oll-39.png" },
  { id: "oll-40-4", title: "OLL 40", algorithm: "", image: "/images/3x3/oll/oll-40.png" },
  { id: "oll-41-4", title: "OLL 41", algorithm: "", image: "/images/3x3/oll/oll-41.png" },
  { id: "oll-42-4", title: "OLL 42", algorithm: "", image: "/images/3x3/oll/oll-42.png" },
  { id: "oll-43-4", title: "OLL 43", algorithm: "", image: "/images/3x3/oll/oll-43.png" },
  { id: "oll-44-4", title: "OLL 44", algorithm: "", image: "/images/3x3/oll/oll-44.png" },
  { id: "oll-45-4", title: "OLL 45", algorithm: "", image: "/images/3x3/oll/oll-45.png" },
  { id: "oll-46-4", title: "OLL 46", algorithm: "", image: "/images/3x3/oll/oll-46.png" },
  { id: "oll-47-4", title: "OLL 47", algorithm: "", image: "/images/3x3/oll/oll-47.png" },
  { id: "oll-48-4", title: "OLL 48", algorithm: "", image: "/images/3x3/oll/oll-48.png" },
  { id: "oll-49-4", title: "OLL 49", algorithm: "", image: "/images/3x3/oll/oll-49.png" },
  { id: "oll-50-4", title: "OLL 50", algorithm: "", image: "/images/3x3/oll/oll-50.png" },
  { id: "oll-51-4", title: "OLL 51", algorithm: "", image: "/images/3x3/oll/oll-51.png" },
  { id: "oll-52-4", title: "OLL 52", algorithm: "", image: "/images/3x3/oll/oll-52.png" },
  { id: "oll-53-4", title: "OLL 53", algorithm: "", image: "/images/3x3/oll/oll-53.png" },
  { id: "oll-54-4", title: "OLL 54", algorithm: "", image: "/images/3x3/oll/oll-54.png" },
  { id: "oll-55-4", title: "OLL 55", algorithm: "", image: "/images/3x3/oll/oll-55.png" },
  { id: "oll-56-4", title: "OLL 56", algorithm: "", image: "/images/3x3/oll/oll-56.png" },
  { id: "oll-57-4", title: "OLL 57", algorithm: "", image: "/images/3x3/oll/oll-57.png" },
]

export const PLL1: MethodOrientation[] = [
  { id: "pll-1-1", title: "Aa", algorithm: "x L2 D2' L' U' L D2' L' U L' x'", image: "/images/3x3/pll/pll-1.png" },
  { id: "pll-2-1", title: "Ab", algorithm: "x L U' L D2' L' U L D2' L2", image: "/images/3x3/pll/pll-2.png" },
  { id: "pll-3-1", title: "E", algorithm: "x' R U' R' D R U R' D' R U R' D R U' R' D' x", image: "/images/3x3/pll/pll-3.png" },
  { id: "pll-4-1", title: "F", algorithm: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R", image: "/images/3x3/pll/pll-4.png" },
  { id: "pll-5-1", title: "Ga", algorithm: "R2 U R' U R' U' R U' R2 D U' R' U R D'", image: "/images/3x3/pll/pll-5.png" },
  { id: "pll-6-1", title: "Gb", algorithm: "R' U' R U D' R2 U R' U R U' R U' R2 D", image: "/images/3x3/pll/pll-6.png" },
  { id: "pll-7-1", title: "Gc", algorithm: "R2' Uw' R U' R U R' Uw R2 Fw R' Fw'", image: "/images/3x3/pll/pll-7.png" },
  { id: "pll-8-1", title: "Gd", algorithm: "R U R' U' D R2 U' R U' R' U R' U R2 D'", image: "/images/3x3/pll/pll-8.png" },
  { id: "pll-9-1", title: "H", algorithm: "M2' U M2' U2 M2' U M2'", image: "/images/3x3/pll/pll-9.png" },
  { id: "pll-10-1", title: "Ja", algorithm: "x R2' F R F' R U2' Rw' U Rw U2' x'", image: "/images/3x3/pll/pll-10.png" },
  { id: "pll-11-1", title: "Jb", algorithm: "R U R' F' R U R' U' R' F R2 U' R'", image: "/images/3x3/pll/pll-11.png" },
  { id: "pll-12-1", title: "Na", algorithm: "z U R' D R2 U' R U D' R' D R2 U' R D' z'", image: "/images/3x3/pll/pll-12.png" },
  { id: "pll-13-1", title: "Nb", algorithm: "z U' R D' R2 U R' U' D R D' R2 U R' D z'", image: "/images/3x3/pll/pll-13.png" },
  { id: "pll-14-1", title: "Ra", algorithm: "L U2 L' U2' L F' L' U' L U L F L2'", image: "/images/3x3/pll/pll-14.png" },
  { id: "pll-15-1", title: "Rb", algorithm: "R' U2 R U2' R' F R U R' U' R' F' R2", image: "/images/3x3/pll/pll-15.png" },
  { id: "pll-16-1", title: "T", algorithm: "R U R' U' R' F R2 U' R' U' R U R' F'", image: "/images/3x3/pll/pll-16.png" },
  { id: "pll-17-1", title: "Ua", algorithm: "M2 U M' U2 M U M2", image: "/images/3x3/pll/pll-17.png" },
  { id: "pll-18-1", title: "Ub", algorithm: "M2 U' M' U2 M U' M2", image: "/images/3x3/pll/pll-18.png" },
  { id: "pll-19-1", title: "V", algorithm: "R' U R' U' R D' R' D R' U D' R2 U' R2' D R2", image: "/images/3x3/pll/pll-19.png" },
  { id: "pll-20-1", title: "Y", algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F'", image: "/images/3x3/pll/pll-20.png" },
  { id: "pll-21-1", title: "Z", algorithm: "M2 U M2 U M' U2 M2 U2 M'", image: "/images/3x3/pll/pll-21.png" },
]

export const PLL2: MethodOrientation[] = [
  { id: "pll-1-2", title: "Aa", algorithm: "aa pll2", image: "/images/3x3/pll/pll-1.png" },
  { id: "pll-2-2", title: "Ab", algorithm: "", image: "/images/3x3/pll/pll-2.png" },
  { id: "pll-3-2", title: "E", algorithm: "", image: "/images/3x3/pll/pll-3.png" },
  { id: "pll-4-2", title: "F", algorithm: "", image: "/images/3x3/pll/pll-4.png" },
  { id: "pll-5-2", title: "Ga", algorithm: "", image: "/images/3x3/pll/pll-5.png" },
  { id: "pll-6-2", title: "Gb", algorithm: "", image: "/images/3x3/pll/pll-6.png" },
  { id: "pll-7-2", title: "Gc", algorithm: "", image: "/images/3x3/pll/pll-7.png" },
  { id: "pll-8-2", title: "Gd", algorithm: "", image: "/images/3x3/pll/pll-8.png" },
  { id: "pll-9-2", title: "H", algorithm: "", image: "/images/3x3/pll/pll-9.png" },
  { id: "pll-10-2", title: "Ja", algorithm: "", image: "/images/3x3/pll/pll-10.png" },
  { id: "pll-11-2", title: "Jb", algorithm: "", image: "/images/3x3/pll/pll-11.png" },
  { id: "pll-12-2", title: "Na", algorithm: "", image: "/images/3x3/pll/pll-12.png" },
  { id: "pll-13-2", title: "Nb", algorithm: "", image: "/images/3x3/pll/pll-13.png" },
  { id: "pll-14-2", title: "Ra", algorithm: "", image: "/images/3x3/pll/pll-14.png" },
  { id: "pll-15-2", title: "Rb", algorithm: "", image: "/images/3x3/pll/pll-15.png" },
  { id: "pll-16-2", title: "T", algorithm: "", image: "/images/3x3/pll/pll-16.png" },
  { id: "pll-17-2", title: "Ua", algorithm: "", image: "/images/3x3/pll/pll-17.png" },
  { id: "pll-18-2", title: "Ub", algorithm: "", image: "/images/3x3/pll/pll-18.png" },
  { id: "pll-19-2", title: "V", algorithm: "", image: "/images/3x3/pll/pll-19.png" },
  { id: "pll-20-2", title: "Y", algorithm: "", image: "/images/3x3/pll/pll-20.png" },
  { id: "pll-21-2", title: "Z", algorithm: "", image: "/images/3x3/pll/pll-21.png" },
]

export const PLL3: MethodOrientation[] = [
  { id: "pll-1-3", title: "Aa", algorithm: "aa pll3", image: "/images/3x3/pll/pll-1.png" },
  { id: "pll-2-3", title: "Ab", algorithm: "", image: "/images/3x3/pll/pll-2.png" },
  { id: "pll-3-3", title: "E", algorithm: "", image: "/images/3x3/pll/pll-3.png" },
  { id: "pll-4-3", title: "F", algorithm: "", image: "/images/3x3/pll/pll-4.png" },
  { id: "pll-5-3", title: "Ga", algorithm: "", image: "/images/3x3/pll/pll-5.png" },
  { id: "pll-6-3", title: "Gb", algorithm: "", image: "/images/3x3/pll/pll-6.png" },
  { id: "pll-7-3", title: "Gc", algorithm: "", image: "/images/3x3/pll/pll-7.png" },
  { id: "pll-8-3", title: "Gd", algorithm: "", image: "/images/3x3/pll/pll-8.png" },
  { id: "pll-9-3", title: "H", algorithm: "", image: "/images/3x3/pll/pll-9.png" },
  { id: "pll-10-3", title: "Ja", algorithm: "", image: "/images/3x3/pll/pll-10.png" },
  { id: "pll-11-3", title: "Jb", algorithm: "", image: "/images/3x3/pll/pll-11.png" },
  { id: "pll-12-3", title: "Na", algorithm: "", image: "/images/3x3/pll/pll-12.png" },
  { id: "pll-13-3", title: "Nb", algorithm: "", image: "/images/3x3/pll/pll-13.png" },
  { id: "pll-14-3", title: "Ra", algorithm: "", image: "/images/3x3/pll/pll-14.png" },
  { id: "pll-15-3", title: "Rb", algorithm: "", image: "/images/3x3/pll/pll-15.png" },
  { id: "pll-16-3", title: "T", algorithm: "", image: "/images/3x3/pll/pll-16.png" },
  { id: "pll-17-3", title: "Ua", algorithm: "", image: "/images/3x3/pll/pll-17.png" },
  { id: "pll-18-3", title: "Ub", algorithm: "", image: "/images/3x3/pll/pll-18.png" },
  { id: "pll-19-3", title: "V", algorithm: "", image: "/images/3x3/pll/pll-19.png" },
  { id: "pll-20-3", title: "Y", algorithm: "", image: "/images/3x3/pll/pll-20.png" },
  { id: "pll-21-3", title: "Z", algorithm: "", image: "/images/3x3/pll/pll-21.png" },
]

export const PLL4: MethodOrientation[] = [
  { id: "pll-1-4", title: "Aa", algorithm: "aa pll4", image: "/images/3x3/pll/pll-1.png" },
  { id: "pll-2-4", title: "Ab", algorithm: "", image: "/images/3x3/pll/pll-2.png" },
  { id: "pll-3-4", title: "E", algorithm: "", image: "/images/3x3/pll/pll-3.png" },
  { id: "pll-4-4", title: "F", algorithm: "", image: "/images/3x3/pll/pll-4.png" },
  { id: "pll-5-4", title: "Ga", algorithm: "", image: "/images/3x3/pll/pll-5.png" },
  { id: "pll-6-4", title: "Gb", algorithm: "", image: "/images/3x3/pll/pll-6.png" },
  { id: "pll-7-4", title: "Gc", algorithm: "", image: "/images/3x3/pll/pll-7.png" },
  { id: "pll-8-4", title: "Gd", algorithm: "", image: "/images/3x3/pll/pll-8.png" },
  { id: "pll-9-4", title: "H", algorithm: "", image: "/images/3x3/pll/pll-9.png" },
  { id: "pll-10-4", title: "Ja", algorithm: "", image: "/images/3x3/pll/pll-10.png" },
  { id: "pll-11-4", title: "Jb", algorithm: "", image: "/images/3x3/pll/pll-11.png" },
  { id: "pll-12-4", title: "Na", algorithm: "", image: "/images/3x3/pll/pll-12.png" },
  { id: "pll-13-4", title: "Nb", algorithm: "", image: "/images/3x3/pll/pll-13.png" },
  { id: "pll-14-4", title: "Ra", algorithm: "", image: "/images/3x3/pll/pll-14.png" },
  { id: "pll-15-4", title: "Rb", algorithm: "", image: "/images/3x3/pll/pll-15.png" },
  { id: "pll-16-4", title: "T", algorithm: "", image: "/images/3x3/pll/pll-16.png" },
  { id: "pll-17-4", title: "Ua", algorithm: "", image: "/images/3x3/pll/pll-17.png" },
  { id: "pll-18-4", title: "Ub", algorithm: "", image: "/images/3x3/pll/pll-18.png" },
  { id: "pll-19-4", title: "V", algorithm: "", image: "/images/3x3/pll/pll-19.png" },
  { id: "pll-20-4", title: "Y", algorithm: "", image: "/images/3x3/pll/pll-20.png" },
  { id: "pll-21-4", title: "Z", algorithm: "", image: "/images/3x3/pll/pll-21.png" },
]

export const ThreeXThreeOLLCases: MethodCase[] = OLL1.map((item, index) => ({ ...item, algorithms: [OLL1[index].algorithm, OLL2[index].algorithm, OLL3[index].algorithm, OLL4[index].algorithm], orientations: [OLL1[index], OLL2[index], OLL3[index], OLL4[index]] }))
export const ThreeXThreePLLCases: MethodCase[] = PLL1.map((item, index) => ({ ...item, algorithms: [PLL1[index].algorithm, PLL2[index].algorithm, PLL3[index].algorithm, PLL4[index].algorithm], orientations: [PLL1[index], PLL2[index], PLL3[index], PLL4[index]] }))

export const FourXFourOLLCases = [
  { id: "4x4-oll-1", title: "OLL Parity 1", algorithm: "Rw' U2' Rw U2 Rw U2' Rw2' F2 Rw' U2 Rw' U2' F2 Rw2' F2'", image: "/images/4x4/oll-parity/ollp1.png" },
  { id: "4x4-oll-2", title: "OLL Parity 2", algorithm: "2R' U2 2L F2 2L' F2 2R2 U2 2R U2 2R' U2 F2 2R2 F2", image: "/images/4x4/oll-parity/ollp2.png" },
  { id: "4x4-oll-3", title: "OLL Parity 3", algorithm: "M Rw U2 x Rw U2 Rw U2 Rw' U2 Lw U2 Rw' U2 Rw U2 Rw' U2 Rw' M'", image: "/images/4x4/oll-parity/ollp3.png" },
]


export const FourXFourPLLCases = [
  { id: "4x4-pll-1", title: "PLL Parity 1", algorithm: "2R2 U2 2R2 Uw2 2R2 Uw2", image: "/images/4x4/pll-parity/pllp1.png" },
  { id: "4x4-pll-2", title: "PLL Parity 2", algorithm: "R U R' U' (2R2 U2 2R2 Uw2 2R2 Uw2) U' R U' R'", image: "/images/4x4/pll-parity/pllp2.png" },
  { id: "4x4-pll-3", title: "PLL Parity 3", algorithm: "M2 U M2 U M' U2 M2 U2 M' U (2L2 U2 2L2 Uw2 2L2 Uw2)", image: "/images/4x4/pll-parity/pllp3.png" },
  { id: "4x4-pll-4", title: "PLL Parity 4", algorithm: "M2 U M2 U M' U2 M2 U2 M' (2L2 U2 2L2 Uw2 2L2 Uw2)", image: "/images/4x4/pll-parity/pllp4.png" },
  { id: "4x4-pll-5", title: "PLL Parity 5", algorithm: "R' U R' U' R' U' R3 U R U R2 (2L2 U2 2L2 Uw2 2L2 Uw2)", image: "/images/4x4/pll-parity/pllp5.png" },
  { id: "4x4-pll-6", title: "PLL Parity 6", algorithm: "R U R' U' R' F R2 U' R' U' R U R' F' U' (2R2 U2 2R2 Uw2 2R2 Uw2)", image: "/images/4x4/pll-parity/pllp6.png" },
  { id: "4x4-pll-7", title: "PLL Parity 7", algorithm: "x' Rw2 U2 Rw2 Uw2 2R2 Uw2 F 3Rw U' R U2 L' U R'", image: "/images/4x4/pll-parity/pllp7.png" },
  { id: "4x4-pll-8", title: "PLL Parity 8", algorithm: "R U R' U' R' F R2 U' R' (2R2 U2 2R2 Uw2 2R2 Uw2) U R U R' F'", image: "/images/4x4/pll-parity/pllp8.png" },
  { id: "4x4-pll-9", title: "PLL Parity 9", algorithm: "(2R2 U2 2R2 Uw2 2R2 Uw2) U R' U2 R U2 R' F R U R' U' R' F' R2", image: "/images/4x4/pll-parity/pllp9.png" },
  { id: "4x4-pll-10", title: "PLL Parity 10", algorithm: "(2R2 U2 2R2 Uw2 2R2 Uw2) R U R' F' R U2 R' U2 R' F R U R U2 R'", image: "/images/4x4/pll-parity/pllp10.png" },
  { id: "4x4-pll-11", title: "PLL Parity 11", algorithm: "R' U L' U2 R U' R' U2 R L U' (2R2 U2 2R2 Uw2 2R2 Uw2)", image: "/images/4x4/pll-parity/pllp11.png" },
  { id: "4x4-pll-12", title: "PLL Parity 12", algorithm: "R U R' F' R U R' U' R' F R2 U' R' (2R2 U2 2R2 Uw2 2R2 Uw2)", image: "/images/4x4/pll-parity/pllp12.png" },
  { id: "4x4-pll-13", title: "PLL Parity 13", algorithm: "(2R2 U2 2R2 Uw2 2R2 Uw2) x R2 D2 R U R' D2 R U' R x'", image: "/images/4x4/pll-parity/pllp13.png" },
  { id: "4x4-pll-14", title: "PLL Parity 14", algorithm: "(2R2 U2 2R2 Uw2 2R2 Uw2) U x R' U R' D2 R U' R' D2 R2 x'", image: "/images/4x4/pll-parity/pllp14.png" },
  { id: "4x4-pll-15", title: "PLL Parity 15", algorithm: "R U R' U' R' F R2 U' R' U' R U R' F' (2R2 U2 2R2 Uw2 2R2 Uw2)", image: "/images/4x4/pll-parity/pllp15.png" },
  { id: "4x4-pll-16", title: "PLL Parity 16", algorithm: "R U R' F' R U R' U' R' F R2 U' R' U' (2R2 U2 2R2 Uw2 2R2 Uw2)", image: "/images/4x4/pll-parity/pllp16.png" },
  { id: "4x4-pll-17", title: "PLL Parity 17", algorithm: "(2R2 U2 2R2 Uw2 2R2 Uw2) R U R' F' R U R' U' R' F R2 U' R'", image: "/images/4x4/pll-parity/pllp17.png" },
  { id: "4x4-pll-18", title: "PLL Parity 18", algorithm: "F R U' R' U' R U R' F' U' (2R2 U2 2R2 Uw2 2R2 Uw2) U' R U R' U' R' F R F'", image: "/images/4x4/pll-parity/pllp18.png" },
  { id: "4x4-pll-19", title: "PLL Parity 19", algorithm: "z Rw2 Uw2' R2' Uw2' F R U R' U' R U R' U' R U R' U' F' U2' R2 Uw2' Rw2' z'", image: "/images/4x4/pll-parity/pllp19.png" },
  { id: "4x4-pll-20", title: "PLL Parity 20", algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F' U' (2R2 U2 2R2 Uw2 2R2 Uw2)", image: "/images/4x4/pll-parity/pllp20.png" },
  { id: "4x4-pll-21", title: "PLL Parity 21", algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F' (2R2 U2 2R2 Uw2 2R2 Uw2)", image: "/images/4x4/pll-parity/pllp21.png" },
  { id: "4x4-pll-22", title: "PLL Parity 22", algorithm: "Rw2 F2 U2 Rw2 F' U' R' U R U' R' U R U' R' U R F R2 U2 F2 Rw2", image: "/images/4x4/pll-parity/pllp22.png" }
]
